// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA350m9ZjhBzdkh-0UXuwUnNtyWWAiRtM4',
    appId: '1:344246672553:web:3e17ff57109ae3093c5db8',
    messagingSenderId: '344246672553',
    projectId: 'mastervape-163a7',
    authDomain: 'mastervape-163a7.firebaseapp.com',
    storageBucket: 'mastervape-163a7.appspot.com',
    measurementId: 'G-0SQ3KW4TZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqL3hv7X62mOmEU7Ibm6QGRib7Fr4bIuA',
    appId: '1:344246672553:android:bd0cffaed2804aba3c5db8',
    messagingSenderId: '344246672553',
    projectId: 'mastervape-163a7',
    storageBucket: 'mastervape-163a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxOhTs_37XL1yfToMXBDS7-nF2ptWjxKc',
    appId: '1:344246672553:ios:fd87eb77ac3c9ded3c5db8',
    messagingSenderId: '344246672553',
    projectId: 'mastervape-163a7',
    storageBucket: 'mastervape-163a7.appspot.com',
    androidClientId: '344246672553-d7i9rlb8nigfnuditvn2m7kr5pj6fr5b.apps.googleusercontent.com',
    iosClientId: '344246672553-tan21nq124ijaolii7mr9a99ea5stsic.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanelEgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxOhTs_37XL1yfToMXBDS7-nF2ptWjxKc',
    appId: '1:344246672553:ios:fd87eb77ac3c9ded3c5db8',
    messagingSenderId: '344246672553',
    projectId: 'mastervape-163a7',
    storageBucket: 'mastervape-163a7.appspot.com',
    androidClientId: '344246672553-d7i9rlb8nigfnuditvn2m7kr5pj6fr5b.apps.googleusercontent.com',
    iosClientId: '344246672553-tan21nq124ijaolii7mr9a99ea5stsic.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanelEgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBDuR9jFZAbYTUz6ujcgzKbn9_mngszMw',
    appId: '1:344246672553:web:773d0b78fb9b43183c5db8',
    messagingSenderId: '344246672553',
    projectId: 'mastervape-163a7',
    authDomain: 'mastervape-163a7.firebaseapp.com',
    storageBucket: 'mastervape-163a7.appspot.com',
    measurementId: 'G-76H2LZJ5BJ',
  );
}
