const Map<String, String> ar = {
  // App General
  'app_name': 'لوحة تحكم إيجو ستور',
  'dashboard': 'لوحة الإحصائيات',
  'products': 'كتالوج الفيب',
  'categories': 'الأقسام والماركات',
  'brands': 'العلامات التجارية',
  'orders': 'الطلبات والشحن',
  'banners': 'البانرات الترويجية',
  'coupons': 'أكواد الخصم',
  'customers': 'بيانات العملاء',
  'notifications': 'الإشعارات الجماعية',
  'settings': 'إعدادات المتجر',
  'logout': 'تسجيل الخروج',
  'search': 'بحث سريع...',
  'quick_stats': 'مؤشرات المتجر المباشرة',
  'admin': 'المدير العام',
  'admin_email': 'admin@egostore.com',
  'english': 'English',
  'arabic': 'العربية',
  'switch_to_arabic': 'التحويل للعربية',
  'switch_to_english': 'Switch to English',
  'dark_theme': 'الوضع الليلي',
  'light_theme': 'الوضع النهاري',
  'collapse_sidebar': 'طي القائمة',
  'expand_sidebar': 'توسيع القائمة',
  'all_items': 'جميع الأصناف',
  'all_categories': 'جميع الأقسام',
  'reload': 'إعادة التحميل',
  'showing_entries': 'عرض {start}-{end} من {total} سجل',
  'page_x_of_y': 'صفحة {page} من {total}',
  'no_records_found': 'لا توجد سجلات مطابقة في قاعدة البيانات',
  'clear_search': 'مسح البحث',
  'items_count': '{count} عنصر',
  'products_count_label': '{count} منتج',
  'times_used': '{count} مرة',
  'devices_count': '{count} جهاز',
  'featured': 'مميز',
  'active': 'مفعل',
  'inactive': 'معطل',
  'is_online': 'نشر في تطبيق المتجر أونلاين',
  'is_online_desc': 'إذا تم الإيقاف، سيظهر المنتج في الكاشير والفرع فقط ولن يظهر لعملاء التطبيق',
  'online_status': 'حالة النشر أونلاين',
  'published_online': 'منشور في التطبيق أونلاين',
  'pos_only': 'كاشير / فرع فقط',
  'online_and_pos': 'أونلاين وكاشير',
  'sales_channel': 'قناة البيع',
  'all_channels': 'جميع القنوات',
  'workspace_mode': 'مساحة العمل',
  'mode_all': 'الكل',
  'mode_ecommerce': 'المتجر الإلكتروني',
  'mode_erp': 'نظام ERP',
  'ecommerce_section': 'التجارة الإلكترونية',
  'erp_section': 'إدارة العمليات و ERP',
  'system_section': 'النظام والإعدادات',

  // Search Hints
  'search_hint_general': 'بحث سريع...',
  'search_products_hint': 'بحث باسم المنتج، الماركة، النكهة، أو الـ SKU...',
  'search_orders_hint': 'بحث برقم الطلب، اسم العميل، الهاتف، أو المدينة...',
  'search_customers_hint': 'بحث باسم العميل، البريد، الهاتف، أو المدينة...',
  'search_categories_hint': 'بحث في الأقسام...',
  'search_brands_hint': 'بحث في الماركات...',
  'search_coupons_hint': 'بحث بأكواد الخصم...',
  'search_banners_hint': 'بحث في البانرات...',
  'search_broadcasts_hint': 'بحث في الإشعارات الجماعية...',

  // Dashboard Screen
  'executive_overview': 'نظرة عامة تنفيذية',
  'executive_overview_sub':
      'متابعة حية للعمليات، صحة مخزون الفيب، والمؤشرات المالية',
  'kpi_total_revenue': 'إجمالي الإيرادات',
  'kpi_net_profit': 'صافي الأرباح',
  'kpi_supplier_payables': 'مستحقات الموردين (ديون آجلة)',
  'kpi_supplier_purchases': 'تكلفة مشتريات التوريد',
  'kpi_supplier_paid': 'المسدد للموردين',
  'kpi_cogs': 'تكلفة البضاعة المباعة',
  'kpi_profit_margin': 'هامش الربح',
  'cost_price': 'سعر التكلفة',
  'profit_margin': 'هامش الربح',
  'net_profit': 'صافي الربح',
  'kpi_today_orders': 'طلبات اليوم',
  'kpi_active_customers': 'العملاء النشطون',
  'kpi_avg_order_val': 'متوسط قيمة الطلب',
  'kpi_low_stock_alerts': 'تنبيهات انخفاض المخزون',
  'kpi_pending_dispatch': 'طلبات بانتظار الشحن',
  'supplier_financials_title': 'الموقف المالي للموردين والتوريدات',
  'supplier_financials_subtitle':
      'متابعة تكلفة مشتريات المخزون، المبالغ المسددة، والمستحقات الآجلة على الإدارة',
  'supplier_balance_due_desc':
      'إجمالي المبالغ المستحقة للموردين الواجب سدادها من الإدارة',
  'top_due_suppliers': 'أعلى الموردين المستحق لهم أرصدة',
  'all_suppliers_settled':
      'جميع حسابات الموردين مسددة بالكامل ولا توجد أي مديونيات معلقة',
  'pay_supplier_btn': 'سداد دفعة للمورّد',
  'view_suppliers_hub': 'فتح دليل الموردين والفواتير',
  'revenue_analytics': 'مؤشرات المبيعات والإيرادات',
  'best_selling_categories': 'المبيعات حسب القسم',
  'brand_market_share': 'حصة الماركات (أجهزة وسوائل)',
  'recent_orders': 'أحدث الطلبات الواردة',
  'export_csv': 'تصدير التقرير',

  // Dashboard Sub-components & Analytics
  'dashboard_date_filter_title': 'تحديد فترة المبيعات والأرباح:',
  'kpi_status_active': 'نشط',
  'kpi_status_opex': 'مصاريف تشغيلية',
  'kpi_status_due': 'مستحق',
  'kpi_status_settled': 'مسدد',
  'kpi_orders_count_today': '{count} طلب اليوم',
  'kpi_orders_count_badge': '{count} طلب',
  'kpi_low_stock_urgent': '{count} حرج',
  'kpi_low_stock_healthy': 'آمن ومثالي',
  'kpi_items_count_badge': '{count} أصناف',
  'sales_channel_title': 'مقارنة المبيعات وصافي الأرباح (القنوات)',
  'sales_channel_subtitle': 'فصل مبيعات وأرباح تطبيق الأونلاين عن كاشير الفرع مع الإجمالي',
  'channel_online_share': 'تطبيق الأونلاين: {percent}%',
  'channel_pos_share': 'كاشير الفرع: {percent}%',
  'channel_online_title': 'تطبيق الأونلاين (App)',
  'channel_online_subtitle': 'طلبات التوصيل والشحن',
  'channel_pos_title': 'كاشير الفرع (POS)',
  'channel_pos_subtitle': 'مبيعات مباشرة بالمتجر',
  'channel_total_title': 'الإجمالي المجمّع (Total)',
  'channel_total_subtitle': 'أونلاين + كاشير الفرع',
  'transactions_count_badge': '{count} عملية',
  'metric_total_sales_label': 'إجمالي المبيعات:',
  'metric_cogs_label': 'تكلفة البضاعة (COGS):',
  'metric_net_profit_label': 'صافي المكسب (Net Profit):',
  'metric_avg_ticket_label': 'متوسط العملية:',
  'metric_refunds_label': 'مرتجعات ومبالغ مستردة ({count}):',
  'btn_view_product_sales': 'عرض تفاصيل مبيعات المنتجات والأصناف',
  'products_sold_count_badge': '{count} منتج مباع',
  'btn_view_product_sales_subtitle': 'عرض كميات كل صنف مباع في التطبيق والفرع، التكلفة، وصافي الربح لكل منتج',
  'revenue_chart_title': 'حركة الإيرادات والمبيعات',
  'revenue_chart_subtitle': 'متابعة أداء الإيرادات اليومية بالجنيه المصري (EGP)',
  'last_7_days': 'آخر 7 أيام',
  'no_revenue_history_7_days': 'لا توجد سجلات إيرادات لآخر 7 أيام حتى الآن',
  'brand_share_title': 'توزيع الحصص السوقية للعلامات التجارية',
  'brand_share_subtitle': 'نسبة تمثيل الماركات في الكتالوج والأجهزة والسوائل',
  'no_brand_distribution_data': 'لا توجد بيانات توزيع للماركات حالياً',
  'live_orders_feed_title': 'البث المباشر للطلبات والشحن',
  'real_time_stream_badge': 'بث لحظي مباشر',
  'order_items_summary': '{count} صنف • {method} • {city}',
  'product_sales_report_title': 'تقرير تفاصيل مبيعات المنتجات والأصناف',
  'product_sales_report_subtitle': 'تفاصيل الكميات المباعة، التكلفة، وصافي الربح لكل منتج',
  'total_units_sold_title': 'إجمالي القطع المباعة',
  'units_count_label': '{count} قطعة',
  'from_x_products': 'من {count} منتج مختلف',
  'total_product_sales_title': 'إجمالي مبيعات المنتجات',
  'total_cost_subtitle': 'التكلفة: {cost}',
  'total_product_profit_title': 'صافي أرباح المنتجات',
  'profit_margin_subtitle': 'هامش الربح: {margin}%',
  'search_product_sales_hint': 'بحث بالاسم، كود الصنف SKU، أو الماركة...',
  'filter_channel_all': 'جميع القنوات',
  'filter_channel_online': 'تطبيق الأونلاين فقط',
  'filter_channel_pos': 'كاشير الفرع فقط',
  'col_product_and_sku': 'المنتج وكود الصنف',
  'col_units_sold': 'الكمية المباعة',
  'col_sales_revenue': 'إجمالي المبيعات',
  'col_sales_cost': 'التكلفة (COGS)',
  'col_sales_profit': 'صافي الربح',
  'col_sales_margin': 'هامش الربح',
  'col_sales_actions': 'الطلبات',
  'view_orders_btn': 'عرض الطلبات',
  'no_product_sales_found': 'لم يتم العثور على مبيعات منتجات في هذه الفترة',
  'try_changing_date_or_filters': 'جرّب تغيير الفترة الزمنية بالتقويم أو إزالة الفلاتر',
  'total_sold_label': 'إجمالي المباع',
  'total_sales_label': 'إجمالي المبيعات',
  'net_profit_label': 'صافي الربح',
  'orders_count_badge': 'الطلبات ({count})',
  'online_badge_with_count': '📱 أونلاين: {count}',
  'pos_badge_with_count': '🏪 الفرع: {count}',
  'item_qty_count': 'الكمية: {qty} قطعة',
  'orders_and_invoices_for': 'طلبات وفواتير: {title}',
  'total_matching_orders': 'إجمالي {count} طلب / فاتورة',
  'no_orders_for_product': 'لا توجد طلبات مسجلة لهذا المنتج',
  'order_num_badge': 'طلب #{id}',
  'pos_invoice_badge': 'فاتورة فرع #{id}',
  'summary_report_badge': 'مؤشرات واتجاهات الأداء',
  'orders_manifest_badge': '{count} طلبات مسجلة',
  'inventory_report_badge': '{count} منتجات في المخزن',
  'master_report_badge': 'جميع سجلات النظام',
  'executive_summary_file': 'الملخص التنفيذي',
  'orders_manifest_file': 'سجل المبيعات والطلبات',
  'inventory_status_file': 'حالة المخزون والنواقص',
  'master_full_file': 'التقرير الشامل المجمع',

  // Products & Variation Matrix
  'products_subtitle':
      'إدارة السوائل الإلكترونية، الأجهزة والمودات، البودات، والكويلات مع مصفوفات المتغيرات',
  'add_product': 'إضافة منتج جديد',
  'edit_product': 'تعديل المنتج',
  'delete_product': 'حذف الصنف',
  'delete_product_confirm':
      'هل أنت متأكد من حذف هذا الصنف من الكتالوج وقاعدة البيانات؟',
  'product_title': 'الصنف / Product',
  'product_type_col': 'النوع (Type)',
  'product_brand_col': 'الماركة / Brand',
  'product_price_col': 'السعر (ج.م)',
  'price_range': 'نطاق الأسعار',
  'min_max_price': 'أقل وأعلى سعر',
  'product_stock_col': 'المخزون',
  'product_vars_col': 'المتغيرات',
  'product_actions_col': 'الإجراءات',
  'view_product_details': 'عرض تفاصيل الصنف',
  'no_products_found': 'لا توجد منتجات مسجلة في الكتالوج حتى الآن',
  'flavors_label': 'نكهات:',
  'simple_product': 'بسيط (Simple)',
  'skus_count': '{count} SKUs',
  'product_desc': 'الوصف',
  'category': 'القسم',
  'brand': 'الماركة',
  'base_price': 'السعر الأساسي (ج.م)',
  'sale_price': 'سعر العرض (ج.م)',
  'total_stock': 'إجمالي المخزون',
  'sku': 'كود الصنف (SKU)',
  'is_featured': 'منتج مميز',
  'product_type': 'نوع المنتج',
  'simple': 'بسيط',
  'variable': 'متعدد المتغيرات (مصفوفة الفيب)',
  'liquid_matrix': 'مصفوفة الليكويد (النيكوتين والحجم)',
  'hardware_matrix': 'مصفوفة الأجهزة (اللون والمقاومة)',
  'nicotine_levels': 'نسب النيكوتين',
  'bottle_sizes': 'أحجام العبوات',
  'device_colors': 'ألوان الجهاز',
  'coil_resistances': 'مقاومات الكويل',
  'generate_matrix': 'توليد مصفوفة المتغيرات',
  'stock_status': 'حالة المخزون',
  'in_stock': 'متوفر',
  'low_stock': 'مخزون منخفض',
  'out_of_stock': 'نفد المخزون',
  'actions': 'الإجراءات',
  'delete': 'حذف',
  'edit': 'تعديل',
  'save': 'حفظ التغييرات',
  'cancel': 'إلغاء',
  'confirm': 'تأكيد',
  'confirm_delete': 'هل أنت متأكد من حذف هذا العنصر؟',
  'type_liquid': 'سوائل إلكترونية (E-Liquids)',
  'type_liquid_short': 'سوائل (Liquids)',
  'type_liquid_desc': 'سولت نيكوتين وفري بيز مع النكهات وسحب MTL/DL',
  'type_device': 'أجهزة ومودات (Devices & Mods)',
  'type_device_short': 'أجهزة (Devices)',
  'type_device_desc': 'أجهزة فيب وبود كيت مع خيارات الألوان والبطارية',
  'type_pod': 'بودات وخراطيش (Pods & Cartridges)',
  'type_pod_short': 'بودات (Pods)',
  'type_pod_desc': 'بودات وخراطيش أجهزة مع خيارات المقاومة والسعة',
  'type_coil': 'كويلات (Replacement Coils)',
  'type_coil_short': 'كويلات (Coils)',
  'type_coil_desc': 'كويلات مقاومة للشبكات مع خيارات المقاومة ونوع السلك',
  'type_accessory': 'إكسسوارات ومستلزمات (Accessories)',
  'type_accessory_short': 'إكسسوارات',
  'type_accessory_desc': 'بطاريات وشواحن وقطن وزجاج وأدوات الصيانة',
  'step_type': '١. اختيار النوع',
  'step_specs': '٢. المواصفات الديناميكية',
  'step_matrix': '٣. مصفوفة المتغيرات',
  'step_review': '٤. المراجعة والحفظ',
  'flavor': 'النكهة',
  'add_flavor': 'أضف نكهة جديدة',
  'new_flavor_title': 'إضافة نكهة جديدة',
  'vape_style': 'نوع السحبة (Vaping Style)',
  'style_mtl': 'MTL (سحبة سيجارة)',
  'style_dl': 'DL (سحبة شيشة مباشرة)',
  'style_both': 'كلاهما (MTL & DL)',
  'max_wattage': 'أقصى قدرة وات (Max Wattage)',
  'battery_type': 'نوع البطارية',
  'battery_integrated': 'بطارية مدمجة (Built-in)',
  'battery_external': 'بطاريات خارجية (18650 / 21700)',
  'pod_capacity': 'سعة البود (مل)',
  'pack_size': 'عدد القطع بالعلبة',
  'wire_material': 'نوع السلك',
  'accessory_sub': 'نوع الملحق',

  // Categories & Brands
  'vape_categories_title': 'أقسام الفيب',
  'categories_subtitle':
      'إدارة أنظمة البود، السولت نيكوتين، الأجهزة والمستلزمات',
  'no_categories_found': 'لا توجد أقسام مسجلة. أضف قسمك الأول.',
  'add_category': 'إضافة قسم',
  'edit_category': 'تعديل القسم',
  'category_name': 'اسم القسم',
  'products_count': 'عدد المنتجات',
  'vape_brands_title': 'ماركات الفيب الرسمية',
  'brands_subtitle': 'الشركات المصنعة للأجهزة وماركات السوائل الإلكترونية',
  'no_brands_found': 'لا توجد ماركات مسجلة. أضف ماركتك الأولى.',
  'add_brand': 'إضافة ماركة',
  'edit_brand': 'تعديل الماركة',
  'brand_name': 'اسم الماركة',
  'brand_id_exists': 'الماركة موجودة بالفعل بنفس المعرف ({id})',
  'brand_name_exists': 'اسم الماركة "{name}" موجود بالفعل!',
  'brand_name_used': 'اسم الماركة "{name}" مستخدم بالفعل لماركة أخرى!',
  'catalog_items': 'أصناف الكتالوج',
  'sort_order': 'ترتيب العرض',
  'sort_order_hint': 'ترتيب الظهور في تطبيق العميل (الأرقام الأقل تظهر أولاً)',
  'sort_by': 'ترتيب حسب',
  'sort_name': 'اسم الماركة',
  'sort_products_count': 'أصناف الكتالوج',
  'sort_status': 'الحالة',
  'sort_asc': 'تصاعدي',
  'sort_desc': 'تنازلي',
  'playlist_reorder_mode': 'ترتيب البلاي ليست (سحب وإفلات)',
  'table_mode': 'عرض الجدول',
  'drag_to_reorder': 'امسك الأيقونة واسحب لأعلى أو لأسفل لإعادة الترتيب',
  'delete_brand_title': 'حذف الماركة',
  'delete_brand_confirm':
      'هل أنت متأكد من حذف ماركة "{name}"؟ سيتم إلغاء ربطها بالمنتجات.',
  'brand_logo_url': 'رابط شعار الماركة (URL)',
  'brand_name_hint': 'مثال: Vaporesso, GeekVape, Voopoo',
  'total_registered_brands': 'إجمالي الماركات المسجلة',
  'featured_active_brands': 'الماركات المميزة / النشطة',
  'total_linked_products': 'إجمالي المنتجات المرتبطة',
  'brands_unit': 'ماركة',
  'featured_unit': 'نشطة',
  'products_unit': 'منتج',
  'required': 'مطلوب',

  // Orders Screen
  'orders_title': 'إدارة وشحن طلبات الفيب',
  'orders_subtitle':
      'متابعة الطلبات المباشرة مع عناوين العملاء وأرقام الهواتف وتفاصيل الأصناف',
  'no_orders_found':
      'لا توجد طلبات مسجلة. ستظهر طلبات العملاء الجديدة هنا مباشرة.',
  'order_id': 'رقم الطلب',
  'order_number': 'طلب رقم #{id}',
  'current_status': 'الحالة الحالية',
  'customer': 'العميل',
  'customer_delivery_address': 'بيانات العميل وعنوان التوصيل',
  'payment': 'طريقة الدفع',
  'status': 'الحالة',
  'total': 'الإجمالي (ج.م)',
  'date': 'التاريخ',
  'items_ordered_count': '{count} صنف',
  'dispatch_action': 'تجهيز وشحن',
  'status_all': 'جميع الطلبات',
  'status_pending': 'قيد الانتظار',
  'status_processing': 'جاري التجهيز',
  'status_shipped': 'تم الشحن',
  'status_delivered': 'تم التسليم',
  'status_cancelled': 'ملغي',
  'update_status': 'تحديث حالة الطلب',
  'order_details': 'تفاصيل الطلب',
  'shipping_address': 'عنوان الشحن',
  'ordered_items': 'المنتجات المطلوبة',
  'ordered_items_label': 'الأصناف المطلوبة',
  'subtotal': 'المجموع الفرعي',
  'shipping_fee': 'مصاريف الشحن',
  'delivery_fee': 'مصاريف التوصيل',
  'free_delivery_notice': 'شحن مجاني',
  'discount': 'الخصم',
  'discount_applied': 'خصم ترويجي',
  'tax_fee': 'الضريبة / القيمة المضافة',
  'grand_total': 'الإجمالي النهائي',
  'phone': 'رقم الهاتف',
  'city': 'المدينة',
  'free_shipping_applied': 'شحن مجاني (للطلبات >= 2000 ج.م)',
  'copy_order_id': 'نسخ رقم الطلب',
  'copy_phone': 'نسخ الهاتف',
  'whatsapp_chat': 'محادثة واتساب',
  'customer_notes': 'ملاحظات العميل الخاصة',
  'no_customer_notes': 'لا توجد ملاحظات إضافية من العميل',
  'item_subtotal': 'الإجمالي: {amount}',
  'item_sku': 'كود: {sku}',
  'item_brand': 'الماركة: {brand}',
  'print_invoice': 'طباعة الفاتورة',
  'invoice_title': 'فاتورة طلب مبيعات',
  'payment_status_label': 'حالة السداد',
  'paid': 'تم السداد',
  'unpaid': 'غير مسدد',
  'cash_on_delivery': 'الدفع عند الاستلام',
  'raw_data_inspector': 'البيانات التقنية للطلب (Firestore)',
  'order_time': 'وقت إنشاء الطلب',
  'delivery_date_label': 'تاريخ التوصيل',
  'tracking_number_label': 'رقم التتبع والشحن',
  'copied_to_clipboard': 'تم النسخ إلى الحافظة',
  'no_items_in_order': 'لم يتم العثور على قائمة أصناف مفصلة لهذا الطلب',
  'view_order_details': 'عرض تفاصيل الطلب',
  'coupon_code_label': 'كود الخصم المستخدم',
  'share_with_courier': 'مشاركة مع المندوب',
  'share_order': 'مشاركة الطلب',
  'courier_share_title': 'مشاركة بيانات الطلب مع المندوب',
  'courier_share_subtitle': 'تجهيز وإرسال تفاصيل الطلب، العنوان، ورابط الخريطة',
  'send_via_whatsapp': 'إرسال عبر واتساب',
  'share_via_whatsapp_contacts': 'إرسال لواتساب (اختيار المندوب)',
  'select_courier_whatsapp': 'فتح واتساب لاختيار المندوب وإرسال الطلب فوراً',
  'share_via_system': 'مشاركة عبر التطبيقات الأخرى',
  'copy_courier_slip': 'نسخ ملخص التوصيل',

  'open_in_google_maps': 'فتح في خرائط جوجل',
  'call_customer': 'اتصال بالعميل',
  'courier_phone_hint': 'رقم هاتف المندوب (اختياري)...',
  'courier_phone_label': 'رقم المندوب',
  'share_slip_copied': 'تم نسخ ملخص التوصيل بنجاح',
  'preview_courier_slip': 'معاينة رسالة المندوب',
  'maps_link': 'رابط موقع الخريطة',
  'amount_to_collect': 'المبلغ المطلوب تحصيله',
  'open_maps': 'الخريطة',

  // Banners & Coupons
  'banners_title': 'البانرات الترويجية الرئيسية',
  'banners_subtitle':
      'سلايدر العروض الترويجية المعروض في تطبيق وموقع إيجو ستور',
  'no_banners_found': 'لا توجد بانرات ترويجية. أنشئ بانرك الترويجي الأول.',
  'add_banner': 'إضافة بانر',
  'preview': 'المعاينة',
  'delete_banner': 'حذف البانر',
  'remove_banner': 'إزالة البانر',
  'delete_banner_title': 'حذف البانر الترويجي',
  'delete_banner_confirm':
      'هل أنت متأكد من رغبتك في حذف هذا البانر الترويجي؟ لا يمكن التراجع عن هذا الإجراء.',
  'delete_banner_confirm_with_title':
      'هل أنت متأكد من رغبتك في حذف البانر الترويجي "{title}"؟ لا يمكن التراجع عن هذا الإجراء.',
  'invalid_image_url': 'رابط الصورة غير صالح',
  'banner_title_hint': 'مثال: عرض خاص على فابوريسو XROS 4',
  'banner_title_col': 'عنوان البانر',
  'target_destination': 'وجهة التحويل',
  'banner_image': 'رابط صورة البانر',
  'target_screen': 'وجهة التحويل',
  'target_type': 'نوع الوجهة',
  'target_sale': 'العروض والتخفيضات',
  'target_new_arrivals': 'المنتجات الجديدة',
  'target_popular': 'الأكثر طلباً',
  'target_product': 'منتج محدد (تفاصيل المنتج)',
  'target_custom_screen': 'شاشة أو رابط مخصص',
  'select_product': 'اختر المنتج المراد رعايته',
  'select_product_hint': 'اختر منتجاً من قائمة المنتجات...',
  'selected_product': 'المنتج المروّج له',
  'change_product': 'تغيير المنتج',
  'no_product_selected': 'يرجى اختيار منتج لربطه بالبانر',
  'product_details_dest': 'صفحة تفاصيل المنتج',
  'fill_from_product': 'ملء تلقائي من بيانات المنتج',
  'coupons_title': 'أكواد الخصم والعروض الترويجية',
  'coupons_subtitle': 'إدارة نسب الخصم والحد الأدنى للطلب وتواريخ الصلاحية',
  'no_coupons_found': 'لا توجد أكواد خصم. أنشئ كود خصم جديد.',
  'add_coupon': 'إنشاء كود خصم',
  'edit_coupon': 'تعديل كود الخصم',
  'edit_cupon': 'تعديل كود الخصم',
  'delete_coupon': 'حذف كود الخصم',
  'delete_cupon': 'حذف كود الخصم',
  'delete_coupon_title': 'حذف كود الخصم',
  'delete_coupon_confirm':
      'هل أنت متأكد من رغبتك في حذف كود الخصم هذا؟ لا يمكن التراجع عن هذا الإجراء.',
  'delete_coupon_confirm_with_code':
      'هل أنت متأكد من رغبتك في حذف كود الخصم "{code}"؟ لا يمكن التراجع عن هذا الإجراء.',
  'coupon_code': 'كود الخصم',
  'coupon_preview': 'معاينة مباشرة لكود الخصم',
  'generate_code': 'توليد كود',
  'generate_random_code': 'توليد كود عشوائي',
  'preset_discounts': 'نسب خصم سريعة',
  'active_status_desc': 'نشط — يمكن للعملاء استخدام هذا الكود عند إتمام الطلب',
  'inactive_status_desc': 'معطل — هذا الكود متوقف مؤقتاً ولا يمكن استخدامه',
  'discount_percentage': 'نسبة الخصم',
  'min_cart_requirement': 'الحد الأدنى لقيمة المشتريات (جنيه)',
  'min_purchase_amount': 'الحد الأدنى لمشتريات العميل لاستخدام الكود',
  'min_purchase_hint': 'مثال: 500',
  'min_purchase_help':
      'المبلغ الذي يجب أن يشتري به العميل حتى يتمكن من استخدام كود الخصم (اتركه فارغاً أو 0 إذا كان متاحاً لأي مبلغ)',
  'redemptions': 'مرات الاستخدام',
  'start_date': 'تاريخ البداية',
  'end_date': 'تاريخ النهاية',
  'expiry_date': 'تاريخ الانتهاء',
  'expired': 'منتهي الصلاحية',
  'scheduled': 'مجدول',
  'invalid_date_range': 'تاريخ النهاية يجب أن يكون بعد تاريخ البداية',
  'no_minimum': 'بدون حد أدنى',
  'off_discount': '{percent}% خصم',
  'valid_duration': 'صالح لمدة {days} يوماً',
  'duration_days': '{days} يوم',
  'one_year': 'سنة واحدة',
  'no_min_threshold': 'بدون حد أدنى للطلب',
  'min_order_threshold': 'الحد الأدنى: {amount} جنيه',
  'save_coupon': 'حفظ كود الخصم',
  'used_times_count': 'استُخدم {count} مرة',

  // Notifications & Broadcasts
  'broadcasts_title': 'إشعارات FCM الجماعية',
  'broadcasts_subtitle':
      'إرسال إعلانات مباشرة، عروض ترويجية وتنبيهات توفر المخزون للهواتف',
  'no_broadcasts_found': 'لم يتم إرسال إشعارات جماعية حتى الآن.',
  'compose_broadcast': 'إنشاء إشعار جماعي',
  'broadcast_title': 'عنوان الإشعار',
  'broadcast_body': 'نص رسالة الإشعار',
  'target_audience': 'الجمهور المستهدف',
  'devices_reached': 'الأجهزة المستلمة',
  'all_users': 'جميع مستخدمي التطبيق',
  'topic_salt_nic': 'محبو السالت نيكوتين',
  'topic_hardware': 'عروض الأجهزة والمودات',
  'send_broadcast': 'إرسال الإشعار الآن',
  'sent_history': 'سجل الإشعارات المرسلة',
  'sent_at': 'وقت الإرسال',

  // Customers Screen
  'customers_title': 'سجل وبيانات العملاء (CRM)',
  'customers_subtitle':
      'سجل مشتريات العملاء، العناوين، إجمالي الإنفاق والصلاحيات',
  'no_customers_found': 'لا يوجد عملاء مسجلون في قاعدة البيانات.',
  'customer_name': 'اسم العميل',
  'email': 'البريد الإلكتروني',
  'city_col': 'المدينة',
  'total_orders': 'إجمالي الطلبات',
  'lifetime_spend': 'إجمالي الإنفاق (ج.م)',
  'customer_role': 'الدور',
  'view_profile': 'عرض الملف الشخصي',

  // Settings
  'settings_title': 'إعدادات وتكوين المتجر',
  'settings_subtitle':
      'إدارة قنوات التواصل الرسمية، وأسعار التوصيل، وشارات المنتجات، والسياسات التنظيمية',
  'contact_support_title': 'بيانات التواصل الرسمية للمتجر',
  'contact_support_subtitle':
      'قنوات خدمة العملاء ومقر المتجر الرسمي للتواصل المباشر',
  'store_phone': 'هاتف خدمة العملاء',
  'store_phone_hint': '+20 100 123 4567',
  'whatsapp_number': 'رقم الواتساب الرسمي',
  'whatsapp_number_hint': '+20 100 123 4567',
  'support_email': 'البريد الإلكتروني للدعم',
  'support_email_hint': 'support@egostore.com',
  'store_address': 'مقر المتجر الرئيسي',
  'store_address_hint': 'مدينة نصر، القاهرة، مصر',
  'shipping_delivery_title': 'إعدادات الشحن والتوصيل',
  'shipping_delivery_subtitle':
      'التحكم في رسوم التوصيل الثابتة والحد الأدنى للطلب للحصول على شحن مجاني',
  'flat_delivery_fee': 'رسوم التوصيل الثابتة (ج.م)',
  'flat_delivery_fee_hint': '60',
  'flat_delivery_fee_help':
      'تكلفة الشحن الأساسية المطبقة عند عدم توفر الشحن المجاني.',
  'free_shipping_threshold': 'الحد الأدنى للشحن المجاني (ج.م)',
  'free_shipping_threshold_hint': '2000',
  'free_shipping_threshold_help':
      'الطلبات التي تبلغ هذه القيمة أو أكثر تحصل على توصيل مجاني تلقائياً (0 ج.م).',
  'estimated_delivery_time': 'المدة المتوقعة للتوصيل',
  'estimated_delivery_time_hint': 'مثال: 24 - 48 ساعة',
  'estimated_delivery_time_help':
      'متوسط وقت التوصيل الذي يظهر للعميل في صفحة الدفع وتتبع الطلبات.',
  'regulatory_settings': 'الامتثال الصحي واللوائح القانونية',
  'regulatory_subtitle': 'سياسات تقييد السن وتحذيرات النيكوتين الإلزامية',
  'age_verification': 'التحقق الإلزامي من العمر (18+)',
  'age_verification_desc':
      'تفعيل نافذة التحقق الإلزامي من العمر للزوار قبل تصفح المتجر',
  'nicotine_warning_banner': 'شريط التحذير الصحي الإلزامي للنيكوتين',
  'nicotine_warning_banner_desc':
      'عرض شريط التنبيه الصحي الإلزامي في صفحات تفاصيل المنتجات',
  'badges_card_desc':
      'تكوين وتخصيص شارات ووسوم المنتجات مثل SALE و NEW و EXCLUSIVE لتمييز المنتجات في التطبيق.',
  'firestore_sync_title': 'مزامنة بيانات فايرستور',
  'firestore_sync_desc': 'متزامن مع الكولكشن: /Settings/store_settings',
  'check_sync_status': 'فحص حالة المزامنة',
  'firestore_sync_active': 'إعدادات فايرستور متصلة وتعمل بنجاح.',
  'save_settings': 'حفظ إعدادات المتجر',
  'reload_settings': 'إعادة تحميل الإعدادات',
  'required_field': 'هذا الحقل مطلوب',

  // Badges Management
  'badges': 'شارات ووسوم المنتجات',
  'manage_badges': 'إدارة الشارات',
  'badges_subtitle':
      'التحكم في الشارات والعلامات الترويجية المعروضة على المنتجات',
  'add_badge': 'إضافة شارة جديدة',
  'edit_badge': 'تعديل الشارة',
  'delete_badge': 'حذف الشارة',
  'delete_badge_confirm': 'هل أنت متأكد من حذف هذه الشارة؟',
  'badge_preview': 'المعاينة',
  'badge_name_en': 'الاسم بالإنجليزية',
  'badge_name_ar': 'الاسم بالعربية',
  'badge_color': 'لون الشارة',
  'badge_status': 'الحالة',
  'badge_active': 'مفعلة',
  'badge_inactive': 'معطلة',
  'badge_status_app_hint':
      'الشارات المفعلة فقط هي التي يمكن اختيارها للمنتجات وتظهر في التطبيق.',
  'no_badges_found': 'لا توجد شارات مسجلة حتى الآن',
  'no_badges_desc':
      'قم بإضافة شارات مثل SALE أو NEW لتمييز المنتجات في التطبيق.',
  'choose_preset_or_custom': 'اختر من الأنواع الشائعة أو اكتب اسماً مخصصاً:',
  'save_badge_changes': 'حفظ التعديلات',
  'badge_name_required': 'يرجى إدخال اسم الشارة',

  // Feedback Alerts
  'success': 'تم بنجاح',
  'error': 'خطأ',
  'warning': 'تنبيه',
  'item_created': 'تم إنشاء العنصر بنجاح!',
  'item_updated': 'تم تحديث العنصر بنجاح!',
  'item_deleted': 'تم حذف العنصر بنجاح!',
  'order_status_updated': 'تم تحديث حالة الطلب وإرسال إشعار للعميل!',
  'broadcast_sent': 'تم إرسال الإشعار لجميع الأجهزة المستهدفة!',
  'settings_saved': 'تم حفظ إعدادات المتجر بنجاح!',

  // Additional UI & Navigation Keys
  'close': 'إغلاق',
  'remove': 'إزالة',
  'previous_page': 'الصفحة السابقة',
  'next_page': 'الصفحة التالية',
  'edit_banner': 'تعديل البانر الترويجي',
  'target_product_short': 'منتج محدد',
  'vape_admin_suite': 'منظومة إدارة الفيب',
  'version_pro_suite': 'v1.2.0 • النسخة الاحترافية',
  'route_shop': 'المتجر الرئيسي',
  'route_categories': 'الأقسام والتصنيفات',
  'route_brands': 'العلامات التجارية',
  'route_cart': 'سلة المشتريات',
  'route_profile': 'الملف الشخصي',
  'route_deals': 'العروض والتخفيضات',
  'route_new_arrivals': 'أحدث المنتجات',
  'route_popular': 'الأكثر طلباً',
  'route_custom': 'رابط مخصص',
  'add_brand_subtitle': 'تسجيل مصنّع جديد أو ماركة سوائل إلكترونية',
  'edit_brand_subtitle': 'تحديث اسم الماركة، الشعار وحالة التمييز',
  'brand_logo_url_hint': 'https://example.com/logo.png',
  'error_occurred': 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
  'featured_brand_desc':
      'إظهار الماركة بشكل بارز في الأقسام المميزة بتطبيق العميل',
  'flavors_available_label': 'النكهات المتوفرة:',
  'member_since': 'عضو منذ {date}',
  'notification_body_col': 'نص الإشعار',
  'product_description_col': 'الوصف',
  'stock': 'المخزون',
  'store_settings_saved': 'تم حفظ إعدادات المتجر بنجاح!',
  'technical_specs': 'المواصفات الفنية',
  'variation_matrix': 'مصفوفة المتغيرات',
  'orders_selected': 'تم تحديد {count} طلب',
  'bulk_status_update': 'تغيير الحالة المجمّع',
  'bulk_share_courier': 'كشف شحن المندوب',
  'clear_selection': 'إلغاء التحديد',
  'bulk_update_success': 'تم تحديث حالة {count} طلبات بنجاح',
  'select_bulk_status_prompt': 'اختر الحالة الجديدة للطلبات المحددة:',
  'bulk_courier_copied': 'تم نسخ كشف الشحن المجمع لـ {count} طلبات بنجاح',

  // Store Branches & Locations
  'store_branches': 'فروع ومواقع المتجر',
  'store_branches_subtitle':
      'إدارة عناوين الفروع، أرقام التواصل، وروابط خرائط جوجل مع خاصية تحديد الموقع اللحظي',
  'add_branch': 'إضافة فرع جديد',
  'edit_branch': 'تعديل بيانات الفرع',
  'delete_branch': 'حذف الفرع',
  'delete_branch_confirm': 'هل أنت متأكد من حذف هذا الفرع؟',
  'branch_name': 'اسم الفرع',
  'branch_name_hint': 'مثال: فرع المعادي / الفرع الرئيسي',
  'branch_phone': 'رقم هاتف الفرع',
  'branch_phone_hint': 'مثال: 01012345678',
  'branch_address': 'عنوان الفرع بالتفصيل',
  'branch_address_hint': 'مثال: شارع النصر، المعادي، القاهرة',
  'maps_link_hint': 'https://maps.google.com/?q=lat,lng',
  'get_live_location': 'تحديد موقعي الحالي الآن (GPS)',
  'locating': 'جاري تحديد موقعك...',
  'location_acquired': 'تم تحديد موقعك بنجاح!',
  'preview_map': 'معاينة على الخريطة',
  'is_primary_branch': 'تعيين كفرع رئيسي',
  'no_branches_added': 'لم يتم إضافة فروع بعد',
  'no_branches_desc':
      'أضف فروع المتجر ليتمكن العملاء من معرفة مواقعكم والتواصل المباشر والوصول عبر خرائط جوجل.',
  'primary_branch_badge': 'فرع رئيسي',

  // Egyptian Governorates & Delivery Pricing
  'governorates_delivery_title': 'محافظات مصر وأسعار التوصيل',
  'governorates_delivery_subtitle':
      'تحديد المحافظات المتاحة للشحن وتسعير خدمة التوصيل لكل محافظة على حدة',
  'search_governorates_hint': 'بحث باسم المحافظة (بالعربية أو الإنجليزية)...',
  'active_delivery_zones': '{active} من {total} محافظة مفعّلة',
  'enable_all_governorates': 'تفعيل الكل',
  'disable_all_governorates': 'تعطيل الكل',
  'set_bulk_fee': 'سعر موحد',
  'reset_governorates_default': 'استعادة الافتراضي',
  'bulk_fee_title': 'تحديد سعر شحن موحد',
  'bulk_fee_desc':
      'أدخل سعر الشحن الجديد ليتم تطبيقه على جميع المحافظات المفعّلة:',
  'apply': 'تطبيق',
  'delivery_available': 'متاح للشحن',
  'delivery_unavailable': 'الشحن معطل',
  'shipping_fee_egp': 'سعر التوصيل',
  'egp_currency': 'ج.م',
  'no_governorates_match': 'لا توجد محافظات مطابقة لبحثك',
  // Roles & Permissions System
  'super_admin': 'سوبر أدمن (المالك)',
  'super_admin_desc':
      'صلاحيات كاملة وشاملة على جميع الإحصائيات، المنتجات، الإعدادات، وإدارة المشرفين',
  'admin_role': 'أدمن (مدير)',
  'admin_role_desc':
      'إدارة كتالوج المنتجات، الماركات، البانرات، الكوبونات، ومعالجة الطلبات بدون الإعدادات الحساسة',
  'staff_role': 'موظف المتجر (Guest Staff)',
  'staff_role_desc':
      'الوصول للطلبات فقط لمعالجة ومتابعة الشحن وحالات التسليم للعملاء',
  'roles_permissions': 'الصلاحيات والمشرفين',
  'roles_management_subtitle':
      'تخصيص صلاحيات كل دور والتحكم الكامل في ظهور الأقسام لكل مستخدم',
  'permissions_matrix': 'جدول الصلاحيات',
  'team_members_roles': 'فريق العمل والمشرفين',
  'module_permission': 'القسم / الصلاحية',
  'super_admin_full_access':
      'السوبر أدمن يمتلك وصولاً كاملاً غير مقيد لجميع الخصائص',
  'current_active_role': 'الدور النشط حالياً',
  'switch_role': 'تبديل الدور النشط',
  'reset_defaults': 'استعادة الافتراضي',
  'save_changes': 'حفظ التعديلات',
  'role_assigned_success': 'تم تحديث الصلاحيات بنجاح',
  'permissions_saved_desc':
      'تم حفظ مصفوفة الصلاحيات في قاعدة البيانات وتطبيقها فوراً',
  'permissions_reset_desc': 'تم استعادة توزيع الصلاحيات الافتراضي',
  'search_staff_hint': 'بحث في المشرفين وفريق العمل...',
  'all_roles': 'الكل',
  'no_staff_found': 'لا يوجد مشرفون أو أعضاء يطابقون البحث',
  'permission_dashboard': 'لوحة الإحصائيات والأرباح المالية',
  'pos_cashier': 'الكاشير',
  'permission_pos': 'الكاشير ومبيعات المتجر',
  'permission_products': 'كتالوج المنتجات والمخزون',
  'permission_brands': 'العلامات التجارية والأقسام',
  'permission_orders': 'الطلبات والشحن والتوصيل',
  'permission_banners': 'البانرات والعروض الترويجية',
  'permission_coupons': 'أكواد وكوبونات الخصم',
  'permission_customers': 'بيانات وسجل العملاء',
  'permission_notifications': 'الإشعارات الجماعية',
  'permission_settings': 'إعدادات المتجر والشحن والمحافظات',
  'permission_roles': 'إدارة الصلاحيات والمشرفين',
  'permission_view_cost_price': 'رؤية سعر الشراء والتكلفة في الكاشير والمنتجات',
  'access_denied_title': 'وصول غير مصرّح به',
  'access_denied_desc':
      'حسابك الحالي لا يمتلك صلاحية للوصول إلى هذا القسم. يرجى التواصل مع السوبر أدمن.',

  'security_passcodes_tab': 'رموز المرور والحماية',
  'security_passcodes_title': 'رموز المرور وحماية الأدوار',
  'security_passcodes_subtitle':
      'تعيين كلمات المرور المطلوبة لترقية الحساب من موظف متجر إلى أدمن مدير أو سوبر أدمن',
  'super_admin_passcode_label': 'رمز مرور السوبر أدمن (Master PIN)',
  'super_admin_passcode_hint': 'مثال: 999999',
  'super_admin_passcode_desc':
      'يمنح وصولاً كاملاً غير مقيد لجميع إحصائيات المتجر والإعدادات وحسابات المشرفين',
  'admin_passcode_label': 'رمز مرور الأدمن المدير (Manager PIN)',
  'admin_passcode_hint': 'مثال: 123456',
  'admin_passcode_desc':
      'يسمح بإدارة المنتجات والطلبات والماركات والكوبونات بدون الإعدادات الحساسة',
  'default_to_staff_label':
      'القفل التلقائي كـ موظف متجر (Guest) عند فتح الموقع',
  'default_to_staff_desc':
      'يضمن فتح لوحة التحكم دائماً بوضع موظف المتجر (الطلبات فقط) حتى يتم إدخال رمز المرور',
  'enter_passcode_title': 'إدخال رمز المرور للترقية',
  'enter_passcode_prompt': 'أدخل رمز المرور للترقية إلى {role}:',
  'passcode_hint': 'رمز المرور...',
  'invalid_passcode': 'رمز المرور غير صحيح! يرجى المحاولة مرة أخرى.',
  'role_elevated_success': 'تم إلغاء القفل وترقية الحساب بنجاح إلى {role} 🔓',
  'lock_to_staff': 'قفل الجلسة (العودة لموظف المتجر)',
  'session_locked': 'تم قفل الجلسة والعودة لوضع موظف المتجر (الطلبات فقط) 🔒',
  'unlock_elevate': 'إلغاء القفل وتأكيد',
  'elevate_role': 'ترقية الدور وإلغاء القفل',
  'passcodes_saved_success':
      'تم حفظ وتحديث رموز المرور بنجاح في قاعدة البيانات',
  'inventory_stock_settings': 'المخزون وتنبيهات النواقص',
  'inventory_stock_settings_subtitle':
      'تحديد الحد الأدنى للمخزون لتنبيهات النواقص وإعادة التوريد في لوحة التحكم',
  'low_stock_threshold_label': 'حد تنبيه نقص المخزون (بالقطع)',
  'low_stock_threshold_hint': 'مثال: 10',
  'low_stock_threshold_help':
      'المنتجات التي يصل مخزونها الإجمالي لهذا الحد أو أقل ستظهر فوراً في تنبيهات النواقص بالداشبورد ومؤشرات الأداء.',
  'quick_restock': 'إعادة شحن المخزون السريع',
  'quick_restock_desc': 'إضافة كميات للمخزون مباشرة لهذا المنتج',
  'add_units': 'إضافة كمية',
  'enter_quantity_to_add': 'الكمية المراد إضافتها للمخزون',
  'stock_updated_success': 'تم تحديث كمية المخزون بنجاح!',
  'open_full_editor': 'فتح التعديل الكامل للمنتج',
  'healthy_stock_desc':
      'جميع مستويات المخزون ممتازة (المخزون أكبر من {threshold} قطعة)',
  'current_stock_is': 'المخزون الحالي: {count} قطعة',
  'warning_threshold_is': 'حد التنبيه: {count} قطعة',
  'export_report_title': 'تصدير التقارير الإحصائية',
  'export_report_desc':
      'اختر التقرير المطلوب تنزيله بصيغة CSV المتوافقة مع برنامج Excel وتحليل البيانات',
  'export_executive_summary': 'ملخص الأداء والمؤشرات التنفيذية',
  'export_executive_summary_desc':
      'المؤشرات المالية، حركة الإيرادات الأسبوعية، وحصص العلامات التجارية',
  'export_orders_report': 'سجل المبيعات والطلبات المفصل',
  'export_orders_report_desc':
      'سجل شامل لجميع الطلبات، بيانات العملاء، المحافظات، العناوين وحالات الدفع',
  'export_inventory_report': 'تقرير المخزون وحالة النواقص',
  'export_inventory_report_desc':
      'كميات المخزون لكل منتج، التصنيفات، الأسعار، وحالة تنبيهات نقص الكميات',
  'export_master_report': 'التقرير الشامل المجمع (Master Report)',
  'export_master_report_desc':
      'ملف متكامل يشمل المؤشرات المالية، سجل المبيعات والطلبات، وحالة المخزون بالكامل',
  'export_download_success': 'تم تنزيل التقرير "{name}" بنجاح!',
  'download_csv': 'تنزيل CSV',

  // Stock Movements & Restock Engine
  'stock_movements_title': 'سجل حركات المخزون والتوريدات',
  'stock_movements_subtitle':
      'تتبع تفصيلي لجميع عمليات التوريد، مبيعات الطلبات، التالف، والتسويات الجردية',
  'stock_audit_log': 'سجل الحركات والتوريدات',
  'quick_restock_title': 'إعادة توريد المخزون الذكي',
  'batch_restock': 'توريد مجمّع',
  'single_restock': 'توريد مفرد',
  'supplier_name_label': 'اسم المورّد / المصدر',
  'invoice_number_label': 'رقم الفاتورة / المرجع',
  'batch_cost_price': 'سعر تكلفة الدفعة الواردة (ج.م)',
  'total_inflow_capital': 'إجمالي رأس مال التوريدات',
  'total_restocked_units': 'إجمالي القطع المورّدة',
  'total_outflow_units': 'إجمالي المنصرف (مبيعات وهالك)',

  // Suppliers & Purchase Invoices Hub
  'suppliers': 'الموردين',
  'permission_suppliers': 'إدارة الموردين وفواتير الشراء',
  'suppliers_title': 'منظومة إدارة الموردين وفواتير الشراء',
  'suppliers_subtitle':
      'دليل الموردين، أوامر الشراء، وتتبع مستحقات وسندات الصرف',
  'add_supplier': 'إضافة مورّد جديد',
  'edit_supplier': 'تعديل بيانات المورّد',
  'create_invoice': 'إنشاء فاتورة شراء جديدة',
  'record_payment': 'تسجيل سند صرف / سداد',
  'statement_of_account': 'كشف حساب المورّد',
  'balance_due': 'الرصيد المستحق (آجل)',
  'total_purchases': 'إجمالي المشتريات',
  'total_paid': 'إجمالي المسدد',
  'payment_terms': 'شروط الدفع',
  'supplier_name': 'اسم المورّد / الشركة',
  'contact_person': 'المسؤول / جهة الاتصال',
  'phone_whatsapp': 'الهاتف / الواتساب',
  'invoice_number': 'رقم الفاتورة',
  'invoice_date': 'تاريخ الفاتورة',
  'due_date': 'تاريخ الاستحقاق',
  'auto_stock_inflow': 'إيداع فوري في المخزون وتحديث أرصدة الكتالوج',
  'status_paid': 'مدفوعة بالكامل',
  'status_partial': 'مدفوعة جزئياً',
  'status_unpaid': 'غير مدفوعة (آجلة)',
  'status_overdue': 'متأخرة السداد',

  // POS & Cashier Register
  'pos_register': 'الكاشير',
  'pos_register_title': 'الكاشير',
  'pos_register_subtitle': 'البيع المباشر وقارئ الباركود',
  'shortcut_f2_scan': 'مسح باركود',
  'shortcut_f4_pay': 'إتمام ودفع',
  'shortcut_f8_returns': 'مرتجع فواتير',
  'shortcut_f9_clear': 'تفريغ السلة',
  'current_bill_cart': 'سلة الفاتورة الحالية',
  'items_pieces_count': '{count} قطع',
  'clear_cart': 'تفريغ السلة',
  'empty_cart_title': 'السلة فارغة حالياً',
  'empty_cart_desc':
      'امسح باركود المنتج أو اضغط عليه من قائمة المنتجات لإضافته للفاتورة',
  'barcode_search_hint': 'امسح الباركود أو ابحث باسم المنتج (F2)...',
  'walk_in_customer': 'عميل مباشر (Walk-in)',
  'customer_name_optional': 'اسم العميل (اختياري)',
  'customer_phone_optional': 'رقم هاتف العميل (اختياري)',
  'payment_cash': 'نقداً (Cash)',
  'payment_card': 'بطاقة بنكية / فيزا (Card)',
  'payment_instapay': 'إنستاباي / محفظة إلكترونية (InstaPay)',
  'payment_split': 'دفع مختلط (Split)',
  'paid_amount_label': 'المبلغ المدفوع نقداً (ج.م)',
  'change_amount_label': 'المتبقي للعميل (الباقي)',
  'complete_sale_btn': 'إتمام البيع وطباعة الإيصال',
  'sale_completed_success': 'تم تسجيل عملية البيع بنجاح',
  'pos_returns_title': 'مرتجع واسترداد فواتير الكاشير',
  'pos_returns_subtitle':
      'ابحث برقم الفاتورة، حدد الأصناف المرتجعة واسترد المبلغ للعميل',
  'lookup_invoice_hint': 'أدخل رقم الفاتورة أو امسح الباركود...',
  'search_invoice_btn': 'بحث عن الفاتورة',
  'return_items_selected': 'إرجاع الأصناف المحددة',
  'total_refund_due': 'المبلغ المسترد للعميل',
  'process_refund_btn': 'تنفيذ الاسترداد وإعادة للمخزون',
  'refund_completed_success': 'تمت معالجة المرتجع وإعادة الأصناف للمخزون بنجاح',
  'print_thermal_receipt_label': 'إيصال حراري (80mm)',
  'print_a4_invoice_label': 'فاتورة A4',

  // Barcode Label Stickers Printing
  'print_barcode_stickers_title': 'طباعة استيكرات وملصقات الباركود',
  'print_barcode_stickers_subtitle':
      'توليد باركودات Code-128 عالية الدقة للطباعة على طابعات الملصقات الحرارية',
  'label_paper_size': 'مقاس الملصق / نوع الورق:',
  'compact_roll_38x25': 'رول حراري صغير (38 x 25 مم)',
  'standard_roll_50x30': 'رول حراري قياسي (50 x 30 مم)',
  'large_roll_58x40': 'رول حراري كبير (58 x 40 مم)',
  'a4_sheet_grid': 'شيت ورق A4 (24 استيكر - شبكة 3x8)',
  'number_of_copies': 'عدد النسخ للطباعة:',
  'variations_and_quantities': 'التنوعات والكميات:',
  'select_all': 'تحديد الكل',
  'by_stock_level': 'حسب المخزون',
  'live_sticker_preview': 'معاينة الاستيكر المباشرة:',
  'barcode_scanner_compatible_note':
      'الباركود متوافق 100% مع أجهزة قراءة الباركود اليدوية والكاميرا (Code-128).',
  'print_stickers_btn': 'طباعة ({count} ملصق)',
  'print_job_dispatched': 'جاري طباعة {count} ملصق باركود على {size}',
  'please_select_at_least_one_item':
      'يرجى تحديد صنف واحد على الأقل مع عدد نسخ أكبر من 0',

  // Order Returns & Sharing
  'order_return_title': 'تسجيل مرتجع / استرداد للأصناف',
  'order_return_subtitle': 'حدد الأصناف والكميات المراد إرجاعها وسبب الإرجاع',
  'return_reason_label': 'سبب الإرجاع:',
  'reason_defective': 'عيب بالمنتج / تالف',
  'reason_wrong_item': 'صنف غير مطابق للطلب',
  'reason_customer_changed_mind': 'تغيير رأي العميل',
  'reason_delivery_error': 'خطأ في التوصيل أو الشحن',
  'reason_unwanted': 'منتج غير مرغوب / غير مناسب',
  'reason_other': 'أخرى (توضيح في الملاحظات)',
  'return_notes_hint': 'ملاحظات إضافية حول المرتجع أو حالة الطرد...',
  'restock_to_inventory_label': 'إعادة الأصناف المسترجعة للمخزون تلقائياً',
  'refund_amount_label': 'المبلغ المسترد للعميل (ج.م):',
  'confirm_return_submission': 'تأكيد تسجيل المرتجع والاسترداد',
  'order_return_recorded_success': 'تم تسجيل المرتجع وتحديث الحساب بنجاح',
  'share_order_title': 'مشاركة بيانات الطلب مع المندوب',
  'share_order_subtitle':
      'إرسال بوليصة الشحن للمندوب أو العميل عبر واتساب أو نسخ النص',
  'copy_slip_text': 'نسخ بيانات الشحن',
  'open_whatsapp': 'إرسال عبر الواتساب',

  // Suppliers & Ledger
  'tab_suppliers': 'دليل الموردين',
  'tab_invoices': 'فواتير الشراء',
  'tab_payments': 'سندات الصرف',
  'supplier_rating_label': 'تقييم المورّد',
  'supplier_supplied_categories': 'التصنيفات المورّدة (مفصولة بفاصلة)',
  'supplier_tax_number': 'السجل التجاري / البطاقة الضريبية',
  'supplier_address': 'العنوان / المقر الرئيسي',
  'supplier_contact_name': 'اسم المسؤول / جهة الاتصال',
  'supplier_saved_success': 'تم حفظ بيانات المورّد بنجاح',
  'delete_supplier_confirm': 'هل أنت متأكد من حذف هذا المورّد؟',
  'item_deleted_success': 'تم الحذف بنجاح',
  'add_purchase_item_btn': 'إضافة صنف للفاتورة',
  'select_product_prompt': 'اختر المنتج من الكتالوج',
  'unit_cost_price': 'سعر تكلفة القطعة (ج.م)',
  'invoice_total_amount': 'إجمالي قيمة الفاتورة',
  'payment_voucher_record': 'تسجيل سند صرف / سداد',
  'amount_paid_egp': 'المبلغ المسدد (ج.م)',
  'payment_source': 'حساب / وسيلة الدفع',
  'payment_reference_hint': 'رقم الإيصال / مرجع التحويل البنكي...',
  'voucher_recorded_success': 'تم تسجيل سند الصرف بنجاح',
  'statement_ledger_title': 'كشف الحساب والعمليات المالية',
  'financial_transactions_history': 'سجل الفواتير وسندات الصرف المتبادلة',

  // Additional Detailed POS & Scanner Keys
  'pos_barcode_search_bar_hint':
      'امسح الباركود بجهاز الماسح، أو ابحث باسم الصنف / الـ SKU...',
  'enter_key_submit': 'إدخال (Enter)',
  'barcode_scanned_title': 'مسح الباركود',
  'barcode_scan_alert': 'تنبيه المسح',
  'pos_sale_error': 'خطأ في عملية البيع',
  'checkout_sale_title': 'إتمام عملية البيع والدفع',
  'items_count_total_meta': 'عدد الأصناف: {count} • الإجمالي: {total}',
  'payment_method_label': 'طريقة الدفع:',
  'payment_cash_tab': 'نقدي (Cash)',
  'payment_card_tab': 'فيزا (Card)',
  'payment_instapay_tab': 'إنستاباي / محفظة',
  'cash_change_calculator': 'حاسبة النقدية والباقي',
  'exact_amount': 'المبلغ بالضبط',
  'cash_received_from_customer': 'المبلغ المستلم من العميل (ج.م)',
  'remaining_amount_to_pay': 'المتبقي مطلوب سداده:',
  'change_to_customer': 'الباقي للعميل (Change):',
  'auto_print_receipt_after_sale': 'طباعة إيصال الكاشير تلقائياً بعد الإتمام',
  'processing_sale': 'جاري الإتمام والخصم...',
  'pos_branch_returns_title': 'مرتجع مبيعات الفرع (POS Returns & Refund)',
  'pos_branch_returns_desc':
      'استرجاع أصناف الفاتورة وإعادة الكميات للمخزون واسترداد المبلغ للعميل',
  'scan_or_type_invoice_hint':
      'امسح باركود الفاتورة أو اكتب رقمها (مثال: POS-12345)...',
  'invoice_not_found_err':
      'لم يتم العثور على فاتورة برقم: {query}. تأكد من صحة رقم الفاتورة أو امسح الباركود.',
  'search_error_prefix': 'خطأ أثناء البحث: {error}',
  'invoice_title_num': 'فاتورة #{id}',
  'invoice_date_prefix': 'التاريخ: {date} • العميل: {customer}',
  'original_total': 'الإجمالي الأصلي: {amount}',
  'select_items_quantities_to_return': 'اختر الأصناف والكميات المطلوب إرجاعها:',
  'item_price_and_purchased_qty': 'السعر: {price} • الكمية المشراة: {qty}',
  'refund_payment_method': 'طريقة استرداد المبلغ:',
  'refund_cash': 'استرداد نقدي (Cash Refund)',
  'refund_card': 'استرداد بنكي / بطاقة (Card)',
  'refund_store_credit': 'رصيد مشتريات (Store Credit)',
  'restock_items_to_inventory': 'إعادة المنتجات للمخزون',
  'print_thermal_return_receipt': 'طباعة إيصال مرتجع حراري',
  'refund_amount_summary': 'المبلغ المسترد: {amount}',
  'confirm_return_and_print': 'تأكيد المرتجع وطباعة الإيصال',
  'pos_return_initial_prompt':
      'امسح باركود الفاتورة أو اكتب رقمها لبدء معالجة المرتجع',
  'pos_return_success_title': 'تم تسجيل المرتجع بنجاح',
  'pos_return_success_msg':
      'تم إرجاع {count} صنف بمبلغ {amount} وتحديث المخزون بنجاح!',
  'pos_return_failed_title': 'فشل معالجة المرتجع',
  'select_at_least_one_item_return': 'يرجى اختيار صنف واحد على الأقل لإرجاعه',
  'available_stock_count': 'المتاح بالمخزون: {count}',
  'max_quantity': 'أقصى كمية',
  'add_discount': 'إضافة خصم',
  'item_discount_badge': 'خصم: {amount} ج.م',
  'item_discount_title': 'خصم الصنف',
  'item_discount_input_label': 'قيمة الخصم للقطعة (ج.م)',
  'apply_discount': 'تطبيق الخصم',
  'items_subtotal': 'إجمالي الأصناف:',
  'total_discount_label': 'إجمالي الخصم:',
  'net_grand_total': 'المجموع الصافي:',
  'complete_sale_pay_amount': 'إتمام البيع والدفع ({amount})',
  'confirm_clear_cart_title': 'تفريغ السلة',
  'confirm_clear_cart_msg': 'هل أنت متأكد من تفريغ كافة محتويات السلة الحالية؟',
  'clear': 'تفريغ',
  'available_options_count': '{count} خيار متاح',
  'search_variations_hint':
      'ابحث في الخيارات (النكهة، النيكوتين، اللون، الـ SKU)...',
  'all_variations_count': 'الكل ({count})',
  'filtered_of_total_options': '{filtered} من أصل {total} خيار',
  'no_matching_variations': 'لا توجد خيارات مطابقة لبحثك',
  'show_all_variations': 'إظهار كافة الخيارات',
  'no_matching_products': 'لم يتم العثور على منتجات مطابقة',
  'no_matching_products_desc':
      'تأكد من كتابة الكلمة بشكل صحيح أو قم بتغيير القسم المختار.',
  'matching_vars_count': 'مطابق {count} من {total}',
  'options_count_badge': '{count} خيارات',

  // Barcode Printing & Order Share
  'total_requested_labels': 'الإجمالي المطلوب: {count} ملصق',
  'print_labels_count_btn': 'طباعة ({count} ملصق)',
  'stock_and_price_label': 'المخزون: {stock} • السعر: {price}',
  'store_brand_tag': 'EGO VAPE STORE',
  'process_order_return_title': 'معالجة مرتجع الطلب #{id}',
  'order_return_customer_meta': 'العميل: {name} • إجمالي الطلب: {amount}',
  'unit_price_and_shipped_qty': 'سعر الوحدة: {price} • الكمية المشحونة: {qty}',
  'unselect_all': 'إلغاء التحديد',
  'return_reason_and_notes': 'سبب الإرجاع وملاحظات العملية:',
  'return_notes_detail_hint':
      'تفاصيل أو ملاحظات إضافية عن حالة الصنف أو شكوى العميل...',
  'restock_title': 'إعادة للمخزون',
  'restock_desc': 'إضافة الكميات تلقائياً إلى رصيد المنتج',
  'selected_items_total': 'إجمالي الأصناف المحددة: {amount}',
  'full_return_type': 'نوع العملية: إرجاع كامل الطلب',
  'partial_return_type': 'نوع العملية: إرجاع جزئي',
  'whatsapp_copied_slip_msg': 'تم فتح الواتساب ونسخ تفاصيل الطلب للحافظة',
  'slip_copied_to_clipboard_msg':
      'تم نسخ نص الطلب للحافظة (يمكنك لصقه مباشرة في محادثة الواتساب)',

  // Suppliers & Hub Keys
  'suppliers_inflow_hub': 'منظومة إدارة الموردين وفواتير الشراء',
  'suppliers_inflow_desc':
      'دليل الموردين، إدارة فواتير الشراء، سندات الصرف ومتابعة الحسابات الآجلة',
  'btn_new_supplier': '+ إضافة مورّد',
  'btn_new_invoice': '+ فاتورة شراء',
  'btn_pay_vendor': 'سداد دفعة',
  'kpi_active_vendors': 'الموردين النشطين',
  'kpi_authorized_suppliers': 'مورّد معتمد في النظام',
  'kpi_purchases_volume': 'إجمالي المشتريات والتوريد',
  'kpi_invoices_logged': '{count} فواتير مسجلة',
  'kpi_total_paid_out': 'إجمالي المبالغ المسددة',
  'kpi_payment_vouchers': '{count} سندات صرف',
  'kpi_outstanding_payables': 'المستحقات والديون المتبقية',
  'kpi_pending_invoices': '{count} فواتير غير مكتملة',
  'tab_suppliers_dir_count': 'دليل الموردين ({count})',
  'tab_invoices_count': 'فواتير الشراء والتوريدات ({count})',
  'tab_payments_count': 'سجل المدفوعات وسندات الصرف ({count})',
  'suppliers_table_title': 'دليل الشركات والموردين',
  'suppliers_table_subtitle': 'عرض وإدارة جهات الاتصال والأرصدة المستحقة',
  'suppliers_search_hint': 'بحث بالاسم، المسؤول، الهاتف...',
  'no_suppliers_found': 'لا يوجد موردين مطابقين للبحث',
  'col_supplier_name': 'المورّد / الشركة',
  'col_contact_person': 'المسؤول',
  'col_phone': 'الهاتف',
  'col_payment_terms': 'شروط الدفع',
  'col_purchases': 'إجمالي المشتريات',
  'col_balance_due': 'المستحق (آجل)',
  'col_rating': 'التقييم',
  'col_status': 'الحالة',
  'status_active': 'نشط',
  'status_inactive': 'معطل',
  'tooltip_statement': 'كشف الحساب',
  'tooltip_print_statement': 'طباعة كشف الحساب',
  'confirm_delete_supplier_title': 'تأكيد حذف المورّد',
  'confirm_delete_supplier_msg': 'هل أنت متأكد من حذف المورّد "{name}"؟',
  'invoices_table_title': 'فواتير الشراء وأوامر التوريد',
  'invoices_table_subtitle': 'متابعة شحنات التوريد والتكاليف وأرصدة السداد',
  'invoices_search_hint': 'بحث برقم الفاتورة، اسم المورّد، الأصناف...',
  'filter_all': 'الكل',
  'filter_unpaid': 'غير مدفوعة',
  'filter_partial': 'جزئية',
  'filter_paid': 'مدفوعة',
  'no_invoices_found': 'لا توجد فواتير مطابقة',
  'col_invoice_number': 'رقم الفاتورة',
  'col_date': 'التاريخ',
  'col_items_count': 'عدد الأصناف',
  'col_total': 'الإجمالي',
  'col_paid': 'المسدد',
  'col_remaining': 'المتبقي',
  'col_payment_status': 'حالة السداد',
  'tooltip_view_details': 'عرض التفاصيل',
  'tooltip_print_invoice': 'طباعة الفاتورة',
  'confirm_delete_invoice_title': 'تأكيد حذف الفاتورة',
  'confirm_delete_invoice_msg':
      'هل أنت متأكد من حذف فاتورة الشراء رقم "{number}"؟',
  'payments_table_title': 'سجل المدفوعات وسندات الصرف للموردين',
  'payments_table_subtitle':
      'توثيق الحوالات البنكية والسداد النقدي ومستندات الدفع',
  'payments_search_hint': 'بحث باسم المورّد، رقم العملية...',
  'no_payments_found': 'لا توجد سندات صرف مسجلة',
  'col_payment_date': 'التاريخ',
  'col_linked_invoice': 'الفاتورة المرتبطة',
  'col_payment_method': 'طريقة الدفع',
  'col_ref_num': 'رقم المرجع / الحوالة',
  'col_amount_paid': 'المبلغ المسدد',
  'general_account_payout': 'سداد عام',
  'tooltip_print_voucher': 'طباعة سند الصرف',
  'tooltip_export_csv': 'تصدير CSV',
  'supplier_name_required': 'يرجى إدخال اسم المورّد',
  'create_new_purchase_invoice_title': 'إنشاء فاتورة شراء وتوريد جديدة',
  'create_new_purchase_invoice_desc':
      'إدخال بضائع جديدة، تسجيل التكاليف وإيداع المخزون الفوري',
  'invoice_number_label_req': 'رقم الفاتورة *',
  'due_date_optional': 'تاريخ الاستحقاق (آجل):',
  'immediate_or_open': 'فوري / غير محدد',
  'add_items_to_invoice_title': 'إضافة أصناف ومنتجات إلى الفاتورة:',
  'tax_vat_label': 'الضريبة / القيمة المضافة',
  'discount_commercial_label': 'الخصم التجاري',
  'shipping_freight_label': 'تكلفة الشحن / النقل',
  'advance_paid_amount_label': 'المبلغ المدفوع مقدماً',
  'net_invoice_total': 'صافي الفاتورة الكلي',
  'auto_replenish_stock_title':
      'إيداع فوري في المخزون وتحديث أرصدة الكتالوج تلقائياً',
  'auto_replenish_stock_desc':
      'سيتم زيادة أرصدة المنتجات فور حفظ الفاتورة وتوثيق حركة توريد رسمية',
  'invoice_notes_label': 'ملاحظات الفاتورة',
  'invoice_notes_hint': 'أي تفاصيل أو شروط خاصة بالشحنة...',
  'confirm_save_invoice_btn': 'حفظ وتأكيد الفاتورة',
  'invoice_saved_success_title': 'تم حفظ الفاتورة',
  'invoice_saved_success_msg':
      'تم تسجيل فاتورة الشراء وتحديث الحسابات والمخزون بنجاح.',
  'please_select_supplier_warning': 'يرجى اختيار المورّد',
  'add_at_least_one_item_warning': 'يجب إضافة صنف واحد على الأقل في الفاتورة',
  'enter_valid_quantity_warning': 'يرجى إدخال كمية صحيحة',
  'select_product_first_warning': 'يرجى اختيار صنف أولاً',
  'warehouse_reception_status': 'حالة استلام البضاعة:',
  'received_and_credited': 'تم الإيداع بالمخزن',
  'pending_receipt': 'معلقة في الانتظار',
  'line_items_count_title': 'الأصناف المشتراة ({count} أصناف):',
  'record_payment_for_supplier_title': 'تسجيل سند صرف / سداد لمورّد',
  'record_payment_for_supplier_desc':
      'سداد دفعة نقدية أو تحويل بنكي أو إنستاباي',
  'supplier_payee_label': 'المورّد / المستفيد *',
  'link_to_specific_invoice': 'ربط بسداد فاتورة معينة (اختياري):',
  'reference_tx_label': 'رقم الحوالة / العملية',
  'payment_notes_label': 'ملاحظات السداد',
  'confirm_payment_btn': 'تأكيد السداد',
  'supplier_statement_title': 'كشف حساب المورّد: {name}',
  'no_financial_records_supplier': 'لا توجد حركات مالية مسجلة لهذا المورّد بعد',
  'reason_cashier_error': 'خطأ في الحساب / الكاشير',
  'reason_flavor_swap': 'استبدال بنكهة / صنف آخر',
  'processing_dots': 'جاري التنفيذ...',
  'out_of_stock_badge': 'نفذ',
  'add_to_cart': 'إضافة للسلة',
  'print_barcode_stickers': 'طباعة استيكرات وملصقات الباركود',
  'print_barcode_stickers_desc':
      'توليد باركودات Code-128 عالية الدقة للطباعة على طابعات الملصقات الحرارية',
  'print_command_sent_title': '✅ تم إرسال أمر الطباعة',
  'print_command_sent_msg': 'جاري طباعة {count} ملصق باركود على {size}',
  'barcode_compatible_note':
      'الباركود متوافق 100% مع أجهزة قراءة الباركود اليدوية والكاميرا (Code-128).',
  'retry': 'إعادة المحاولة',
  'supplier_saved_success_msg': 'تم حفظ بيانات المورّد بنجاح',
  'all_categories_filter': 'الكل ({count})',
  'category_liquids': 'سوائل (Liquids)',
  'category_disposable': 'دسبوزابل (Disposable)',
  'category_devices': 'أجهزة (Devices)',
  'category_pods': 'بودات (Pods)',
  'category_coils': 'كويلات (Coils)',
  'category_accessories': 'إكسسوارات (Accessories)',
  'add_new_supplier': 'إضافة مورّد جديد',
  'supplier_form_desc': 'سجل الموردين والشركات المعتمدة في النظام',
  'contact_person_label': 'المسؤول / جهة الاتصال',
  'phone_whatsapp_label': 'رقم الهاتف / الواتساب',
  'email_address_label': 'البريد الإلكتروني',
  'address_warehouse_label': 'العنوان / المستودع',
  'tax_reg_num_label': 'السجل التجاري / الرقم الضريبي',
  'default_payment_terms_label': 'شروط السداد الافتراضية',
  'supplied_categories_label': 'الأصناف المورّدة (مفصولة بفواصل)',
  'rating_label': 'التقييم:',
  'supplier_status_label': 'حالة المورّد:',
  'notes_remarks_label': 'ملاحظات إضافية',
  'notes_remarks_hint': 'أي تفاصيل أو اتفاقيات خاصة...',
  'update_supplier_btn': 'حفظ التعديلات',
  'add_supplier_btn': 'إضافة المورّد',
  'saved_successfully': 'تم الحفظ بنجاح',

  // Low Stock & Supplier Financials Dashboard Cards
  'audit_log': 'سجل الحركات',
  'urgent_items_badge': '{count} أصناف ملحة (≤ {threshold})',
  'optimal_stock_badge': 'مخزون مثالي',
  'restock_btn': 'توريد',
  'general_brand': 'عام',
  'payables_due_badge': 'مديونية مستحقة للسداد',
  'all_settled_badge': 'حسابات مسددة بالكامل',
  'new_invoice_btn': '+ فاتورة توريد',
  'metric_accounts_payable_title': 'مستحقات الموردين (ديون على الإدارة)',
  'metric_accounts_payable_subtitle': 'مبالغ آجلة معلقة واجبة السداد للشركات',
  'metric_total_purchases_title': 'إجمالي تكلفة المشتريات والتوريد',
  'metric_active_suppliers_count': '{count} موردين معتمدين',
  'metric_total_disbursed_title': 'إجمالي المبالغ المسددة للموردين',
  'metric_settlement_rate': '{rate}% نسبة السداد',
  'inflow_settlement_ratio': 'معدل سداد مشتريات التوريد:',
  'settlement_progress_summary': '{rate}% مسدد • {remaining} متبقي',
  'view_full_directory': 'فتح الدليل الكامل ➔',
  'pay_btn_short': 'سداد',

  // Stock Movements & Audit Log Dialog
  'stock_movements_btn': 'سجل التوريدات',
  'stock_movements_dialog_title': 'سجل حركات المخزون والتوريدات',
  'stock_movements_dialog_subtitle': 'تتبع تفصيلي لجميع عمليات التوريد، مبيعات الطلبات، التالف، والتسويات الجردية',
  'total_restock_capital': 'تكلفة التوريدات الواردة',
  'units_count': '{count} قطعة',
  'units_short': 'وحدة',
  'search_stock_movements_hint': 'بحث بالـ SKU، اسم المنتج، المورّد، أو رقم الفاتورة...',
  'refresh_log_tooltip': 'تحديث السجل',
  'all_filter': 'الكل',
  'no_stock_movements_title': 'لا توجد حركات مخزون مسجلة',
  'no_stock_movements_desc': 'أي عملية توريد أو بيع أو تعديل جردي ستظهر هنا تلقائياً في السجل',

  // Quick Restock Dialog
  'smart_stock_replenishment': 'إعادة توريد المخزون الذكي',
  'single_sku_mode': 'توريد مفرد',
  'batch_matrix_mode': 'توريد مجمّع',
  'full_editor_btn': 'معالج الصنف',
  'confirm_batch_restock': 'تأكيد التوريد المجمّع',
  'confirm_restock': 'تأكيد التوريد',
  'select_variation_to_restock': 'اختر المتغير المراد توريده:',
  'current_stock_label': 'المخزون الحالي: {count} قطعة',
  'reorder_threshold_label': 'حد التنبيه: {count} قطع',
  'new_stock_label': 'الجديد: {count} قطعة',
  'quantity_to_add_label': 'الكمية الواردة للتوريد:',
  'batch_cost_price_label': 'سعر تكلفة الوحدة للدفعة (ج.م):',
  'total_inflow_expenditure': 'إجمالي تكلفة الشحنة: {amount}',
  'total_units_added': 'إجمالي القطع المضافة: {count} قطعة',
  'total_cost_label': 'إجمالي التكلفة: {amount}',
  'restock_notes_label': 'ملاحظات الشحنة',
  'restock_notes_hint': 'أي ملاحظات خاصة بالتوريد...',
  'plus_10_all': '+10 للكل',
  'cost_label': 'التكلفة',
  'qty_label': '+الكمية',
  'warning_title': 'تنبيه',
  'enter_valid_qty_msg': 'يرجى إدخال كمية توريد صحيحة أكبر من الصفر.',
  'enter_qty_for_at_least_one_msg': 'يرجى إدخال كمية توريد لمتغير واحد على الأقل.',
  'restock_confirmed_title': 'تم التوريد بنجاح',
  'restock_confirmed_msg': 'تم توريد المخزون وتوثيق حركة التوريد بنجاح.',
  'restock_product_success_msg': 'تم تحديث مخزون "{title}" وتسجيل حركة التوريد بنجاح.',
  'restock_failed_title': 'خطأ في التوريد',

  // Variation Image Dialog
  'variation_image_title': 'صورة المتغير ({sku})',
  'variation_image_subtitle': 'أضف رابط صورة مخصصة لهذا المتغير أو اختر من صور المنتج',
  'image_updated_title': 'تم تحديث الصورة',
  'image_updated_msg': 'تم تعيين صورة المتغير {sku} بنجاح.',
  'bulk_applied_title': 'تم التطبيق الجماعي',
  'applied_to_color_msg': 'تم تطبيق الصورة على جميع متغيرات اللون "{color}".',
  'applied_to_flavor_msg': 'تم تطبيق الصورة على جميع متغيرات نكهة "{flavor}".',
  'applied_to_all_title': 'تم التطبيق على الكل',
  'applied_to_all_msg': 'تم تطبيق هذه الصورة على جميع المتغيرات في المصفوفة.',
  'invalid_url_text': 'رابط غير صالح',
  'no_image_selected_text': 'لا توجد صورة محددة',
  'variation_image_url_label': 'رابط صورة المتغير (Image URL) *',
  'choose_from_existing_photos': 'أو اختر من صور المنتج الحالية:',
  'apply_to_all_color': 'تطبيق على كل ({color})',
  'apply_to_all_flavor': 'تطبيق على كل ({flavor})',
  'apply_to_all_variations': 'تطبيق على كل المتغيرات',
  'save_for_this_variation': 'حفظ لهذا المتغير',

  // Product Type Card Subtitles
  'type_subtitle_liquid': 'سولت وفري بيس',
  'type_subtitle_disposable': 'سحبات ونكهات جاهزة',
  'type_subtitle_device': 'مودات وبودات وكيت',
  'type_subtitle_pod': 'خراطيش وكويلات',
  'type_subtitle_accessory': 'بطاريات وملحقات',

  // General Expenses & OpEx
  'expenses': 'المصاريف العامة',
  'expenses_title': 'إدارة المصاريف العامة',
  'expenses_subtitle': 'تسجيل وتتبع كافة المصروفات التشغيلية والفواتير والصيانة',
  'permission_expenses': 'إدارة المصاريف',
  'add_expense_btn': 'إضافة مصروف جديد',
  'add_new_expense': 'تسجيل مصروف جديد',
  'edit_expense': 'تعديل بيانات المصروف',
  'expense_form_desc': 'أدخل تفاصيل المصروف والمبلغ والتصنيف وطريقة الدفع',
  'expense_title': 'بيان المصروف',
  'expense_title_hint': 'مثال: فاتورة كهرباء شهر 9، بنزين التوصيل، بوفيه...',
  'expense_amount_egp': 'المبلغ (جنيه)',
  'expense_category': 'تصنيف المصروف',
  'expense_date': 'تاريخ المصروف',
  'expense_recorded_by': 'القائم بالصرف / المسؤول',
  'expense_recorded_by_hint': 'اسم الموظف أو المدير',
  'expense_notes_hint': 'أي ملاحظات إضافية أو تفاصيل عن الصرف...',
  'save_expense': 'حفظ المصروف',
  'update_expense': 'تحديث المصروف',
  'expense_added_success': 'تم تسجيل المصروف بنجاح',
  'expense_updated_success': 'تم تحديث بيانات المصروف بنجاح',
  'expense_deleted_success': 'تم حذف المصروف بنجاح',
  'delete_expense_title': 'حذف المصروف',
  'delete_expense_confirm': 'هل أنت متأكد من رغبتك في حذف المصروف',
  'expenses_list_title': 'سجل المصروفات',
  'search_expenses_hint': 'ابحث في المصاريف بالبيان، الملاحظات، المسؤول...',
  'no_expenses_found': 'لا توجد مصاريف مسجلة حتى الآن',
  'add_first_expense': 'تسجيل أول مصروف',
  'kpi_expenses_this_month': 'مصاريف هذا الشهر',
  'kpi_expenses_today': 'مصاريف اليوم',
  'kpi_expenses_filtered_total': 'إجمالي المصاريف المحددة',
  'kpi_expenses_top_category': 'أعلى بند صرف',
  'filter_all_categories': 'جميع التصنيفات',
  'filter_date_range': 'الفترة الزمنية:',
  'filter_this_week': 'هذا الأسبوع',
  'filter_this_month': 'هذا الشهر',
  'filter_custom_date': 'تاريخ مخصص',
  'expense_cat_utilities': 'فواتير (كهرباء/مياه/نت)',
  'expense_cat_rent': 'إيجار المحل / المخزن',
  'expense_cat_supplies': 'مستلزمات ونظافة وبوفيه',
  'expense_cat_maintenance': 'صيانة وإصلاحات',
  'expense_cat_transportation': 'نقل وشحن وبنزين',
  'expense_cat_marketing': 'تسويق وإعلانات',
  'expense_cat_salaries': 'رواتب وأجور',
  'expense_cat_government': 'ضرائب وتراخيص',
  'expense_cat_other': 'نثريات ومصاريف أخرى',
  'payment_method_cash': 'نقدي (كاش)',
  'payment_method_instapay': 'إنستاباي (InstaPay)',
  'payment_method_vodafone_cash': 'فودافون كاش',
  'payment_method_bank_transfer': 'تحويل بنكي',
  'payment_method_card': 'فيزا / بطاقة بنكية',

  // Damaged Stock & Inventory Waste
  'damaged_stock': 'الهالك والتوالف',
  'damaged_stock_title': 'إدارة الهالك والتوالف المخزنية',
  'damaged_stock_subtitle': 'تسجيل وإتلاف البضائع التالفة مع خصمها التلقائي من المخزون وحساب الخسائر',
  'permission_damaged_stock': 'إدارة الهالك والتوالف',
  'log_damage_btn': 'تسجيل هالك وتالف جديد',
  'log_damage_title': 'تسجيل صنف تالف / هالك',
  'log_damage_subtitle': 'خصم الكمية من المخزون وحساب الخسائر المالية للتكلفة',
  'select_product_to_damage': 'اختر المنتج المراد إتلافه *',
  'select_variation': 'اختر الصنف / النكهة / الحجم *',
  'damage_quantity': 'الكمية التالفة (قطع)',
  'cost_price_per_unit': 'تكلفة القطعة (ج.م)',
  'total_damage_financial_loss': 'إجمالي الخسارة المالية',
  'damage_reason': 'سبب الهالك والتلف',
  'damage_reason_expired': 'انتهاء الصلاحية',
  'damage_reason_shipping': 'كسر / تلف شحن ونقل',
  'damage_reason_storage': 'تلف تخزين / حرارة ورطوبة',
  'damage_reason_factory': 'عيب صناعة / مصنعي',
  'damage_reason_customer': 'مرتجع عميل تالف',
  'damage_reason_theft': 'عجز جرد / فقدان',
  'damage_reason_other': 'أسباب أخرى',
  'filter_all_reasons': 'كافة الأسباب',
  'notes_and_explanation': 'ملاحظات وتفاصيل التلف',
  'damage_notes_hint': 'اكتب سبب التلف بالتفصيل أو رقم كرتونة الشحن...',
  'confirm_log_damage': 'تسجيل وإتلاف من المخزون',
  'damage_select_product_required': 'يرجى اختيار المنتج أولاً',
  'damage_qty_min_error': 'الكمية يجب أن تكون أكبر من صفر',
  'damage_qty_exceeds_stock': 'الكمية التالفة تتجاوز الرصيد المتوفر في المخزن',
  'available_stock_in_warehouse': 'الرصيد الحالي المتوفر بالمخزن',
  'units': 'قطع',
  'damage_recorded_success': 'تم تسجيل الهالك وخصم الكمية من المخزون بنجاح',
  'damage_record_deleted_success': 'تم حذف سجل الهالك بنجاح',
  'delete_damage_record_title': 'حذف سجل الهالك',
  'delete_damage_record_confirm': 'هل أنت متأكد من حذف سجل الهالك الخاص بمنتج',
  'restore_stock_on_delete': 'إعادة الكمية للمخزون (Restore Stock)',
  'restore_stock_on_delete_subtitle': 'تفعيل هذا الخيار سيعيد القطع المحذوفة إلى رصيد المنتج المتاح للبيع',
  'damaged_item_details': 'تفاصيل التالف المسجل',
  'search_damaged_stock_hint': 'ابحث باسم المنتج، كود الصنف SKU، الملاحظات، المسؤول...',
  'no_damaged_stock_found': 'لا توجد توالف أو هوالك مسجلة',
  'no_damaged_stock_subtitle': 'اضغط على زر تسجيل هالك جديد لإضافة بضائع تالفة وخصمها من المخزن',
  'kpi_total_damage_loss': 'إجمالي الخسائر المالية',
  'kpi_total_damaged_units': 'إجمالي القطع التالفة',
  'kpi_this_month_damage_loss': 'خسائر هالك هذا الشهر',
  'kpi_top_damage_reason': 'السبب الأكثر شيوعاً',
  'search_product_barcode_hint': 'ابحث باسم المنتج أو الباركود أو الماركة...',

  // HR, Employees & Payroll
  'employees': 'الموظفين والرواتب',
  'permission_employees': 'إدارة الموظفين والرواتب والسُلف',
  'employees_management_title': 'إدارة الموظفين والرواتب والسُلف',
  'employees_management_subtitle': 'سجل العاملين، صرف السُلف المالية، وإعداد مسيرات الرواتب الشهرية',
  'tab_employees': 'دليل الموظفين',
  'tab_salary_advances': 'سجل السُلف',
  'tab_payroll_history': 'مسيرات الرواتب',
  'add_employee_btn': 'إضافة موظف جديد',
  'disburse_advance_btn': 'صرف سُلفة',
  'disburse_payroll_btn': 'إصدار مسير راتب',
  'kpi_total_monthly_salaries': 'إجمالي كتلة الرواتب',
  'kpi_current_month_advances': 'سُلف الشهر الحالي',
  'kpi_disbursed_salaries_this_month': 'رواتب مسددة هذا الشهر',
  'kpi_active_employees_count': 'الموظفون النشطون',
  'month_period_label': 'شهر الاستحقاق:',
  'search_employees_hint': 'بحث باسم الموظف، الوظيفة، الهاتف، أو الرقم القومي...',
  'search_advances_hint': 'بحث باسم الموظف، الملاحظات، أو طريقة الصرف...',
  'search_payroll_hint': 'بحث باسم الموظف، شهر الراتب، أو المسؤول...',
  'no_employees_found': 'لا يوجد موظفون مسجلون',
  'no_advances_found': 'لا توجد سُلف مسجلة لهذا الشهر',
  'no_payroll_found': 'لا توجد مسيرات رواتب مصدرة لهذا الشهر',
  'add_first_employee': 'إضافة أول موظف',
  'employee_col_name': 'اسم الموظف',
  'employee_col_job': 'المسمى الوظيفي',
  'employee_col_phone': 'رقم الهاتف',
  'employee_col_salary': 'الراتب الأساسي',
  'employee_col_advances_balance': 'سُلف غير مسددة',
  'employee_col_status': 'الحالة',
  'employee_col_actions': 'الإجراءات',
  'advance_col_employee': 'الموظف',
  'advance_col_amount': 'مبلغ السُلفة',
  'advance_col_date': 'تاريخ الصرف',
  'advance_col_payment_method': 'طريقة الدفع',
  'advance_col_deducted': 'حالة الخصم',
  'payroll_col_employee': 'الموظف',
  'payroll_col_month': 'شهر المسير',
  'payroll_col_base': 'الأساسي',
  'payroll_col_bonuses': 'المكافآت',
  'payroll_col_advances': 'خصم السُلف',
  'payroll_col_deductions': 'الجزاءات/الخصومات',
  'payroll_col_net': 'صافي الراتب المستلم',
  'payroll_col_date': 'تاريخ الصرف',
  'settled_from_payroll': 'تم الخصم من الراتب',
  'unsettled_advance': 'معلقة (لم تخصم)',
  'active_employee': 'على رأس العمل',
  'inactive_employee': 'متوقف / غير نشط',
  'delete_employee_title': 'حذف موظف',
  'delete_employee_confirm': 'هل أنت متأكد من حذف بيانات الموظف',
  'employee_deleted_success': 'تم حذف بيانات الموظف بنجاح',
  'delete_advance_title': 'حذف سجل السُلفة',
  'delete_advance_confirm': 'هل أنت متأكد من حذف سُلفة بمبلغ',
  'for_employee': 'للموظف',
  'advance_deleted_success': 'تم حذف سجل السُلفة بنجاح',
  'delete_payroll_title': 'حذف مسير راتب',
  'delete_payroll_confirm': 'هل أنت متأكد من حذف مسير راتب',
  'payroll_deleted_success': 'تم حذف مسير الراتب بنجاح',
  'edit_employee_title': 'تعديل بيانات الموظف',
  'add_employee_title': 'إضافة موظف جديد',
  'employee_form_subtitle': 'تسجيل بيانات الموظف، الوظيفة، والراتب الأساسي',
  'employee_name': 'اسم الموظف بالكامل *',
  'employee_name_hint': 'مثال: أحمد محمد علي',
  'employee_phone': 'رقم الهاتف / الواتساب *',
  'national_id': 'الرقم القومي (14 رقم)',
  'national_id_hint': 'الرقم القومي للتحقق',
  'job_title_position': 'المسمى الوظيفي *',
  'job_title_hint': 'مثال: كاشير، بائع، أمين مخزن، مدير فرع',
  'base_monthly_salary': 'الراتب الشهري الأساسي (ج.م) *',
  'employee_address': 'العنوان بالتفصيل',
  'employee_address_hint': 'المدينة، المنطقة، الشارع...',
  'emergency_contact': 'هاتف الطوارئ / قريب',
  'employee_status_active': 'الموظف على رأس العمل ونشط',
  'employee_status_active_subtitle': 'يمكنه استلام سُلف ومرتبات شهرية',
  'employee_added_success': 'تمت إضافة الموظف بنجاح',
  'employee_updated_success': 'تم تعديل بيانات الموظف بنجاح',
  'disburse_advance_title': 'صرف سُلفة مالية لموظف',
  'disburse_advance_subtitle': 'تسجيل سُلفة نقدية وخصمها تلقائياً عند إصدار مسير الراتب الشهري',
  'select_employee': 'اختر الموظف *',
  'select_employee_required': 'يرجى اختيار الموظف أولاً',
  'advance_amount_egp': 'مبلغ السُلفة (ج.م) *',
  'advance_date': 'تاريخ استلام السُلفة',
  'confirm_disburse_advance': 'تأكيد صرف السُلفة',
  'advance_recorded_success': 'تم تسجيل وصرف السُلفة بنجاح',
  'disburse_payroll_title': 'إصدار مسير راتب شهري',
  'disburse_payroll_subtitle': 'حساب صافي الراتب بعد المكافآت وخصم السُلف والجزاءات وتسجيله كمصروف',
  'payroll_calculation_breakdown': 'تفاصيل واحتساب المسير',
  'bonuses_and_incentives': 'حوافز ومكافآت إضافية (ج.م)',
  'deductions_and_penalties': 'جزاءات وخصومات أخرى (ج.م)',
  'net_salary_to_pay': 'صافي المبلغ المستحق للصرف',
  'record_to_expenses_checkbox': 'تسجيل الراتب تلقائياً في بند المصاريف العامة (رواتب وأجور)',
  'record_to_expenses_subtitle': 'تضمين هذا المبلغ مباشرة في تقارير المصروفات والأرباح والخسائر',
  'confirm_disburse_payroll': 'اعتماد وصرف المسير',
  'payroll_disbursed_success': 'تم إصدار مسير الراتب وتسجيل المصروف بنجاح',
  'thermal_receipt': 'إيصال حراري',
  'send_push_to_all': 'إرسال إشعار لجميع المستخدمين',
  'confirm_and_select': 'تأكيد واختيار',
  'products_selected_count': 'تم تحديد {count} منتج',
  'passcodes_cannot_be_empty': 'لا يمكن ترك كلمات المرور فارغة',
  'add_and_select': 'إضافة واختيار',
  'add_resistance': 'إضافة المقاومة',
  'add_image': 'إضافة صورة',
  'select_from_picker': 'اختيار من المنتقي',
  'save_image': 'حفظ الصورة',

  // Dashboard HR & Payroll Card
  'payroll_hr_dashboard_title': 'إدارة الموظفين ومسيرات الرواتب',
  'payroll_hr_dashboard_subtitle': 'متابعة كتلة الرواتب، السُلف المنصرفة، والمسيرات المسددة خلال الفترة',
  'kpi_active_staff_title': 'الموظفون النشطون',
  'kpi_base_salaries_pool_title': 'كتلة الرواتب الشهرية',
  'kpi_advances_period_title': 'سُلف الفترة المحددة',
  'kpi_paid_payroll_period_title': 'مسيرات الرواتب المسددة',
  'payroll_execution_ratio': 'نسبة تنفيذ مسيرات الرواتب:',
  'payroll_execution_summary': 'تم صرف {paid} من إجمالي {pool} كتلة الرواتب',
  'manage_employees_hub_btn': 'دليل الموظفين والسُلف ➔',
  'disburse_advance_quick_btn': 'صرف سُلفة',
  'issue_payroll_quick_btn': 'إصدار مسير راتب',
  'staff_members_count': '{count} موظف على رأس العمل',

  // Dashboard Expenses & Damaged Goods Cards
  'expenses_dashboard_title': 'المصاريف التشغيلية (OpEx)',
  'expenses_dashboard_subtitle': 'تتبع بنود الصرف والفواتير والمصاريف الإدارية خلال الفترة',
  'damaged_goods_dashboard_title': 'الهالك والتوالف المخزنية',
  'damaged_goods_dashboard_subtitle': 'متابعة الخسائر المالية وتلف البضائع وإتلاف المخزون',
  'metric_total_expenses_title': 'إجمالي المصاريف',
  'metric_expenses_count_subtitle': '{count} عملية صرف مسجلة',
  'metric_top_expense_cat': 'أعلى بند صرف',
  'metric_damaged_loss_title': 'إجمالي خسائر الهالك',
  'metric_damaged_units_subtitle': '{count} قطعة تالفة مخصومة',
  'metric_top_damage_reason': 'السبب الرئيسي للتلف',
  'manage_expenses_hub_btn': 'سجل المصاريف العامة ➔',
  'manage_damaged_hub_btn': 'سجل الهالك والتوالف ➔',
  'add_expense_quick_btn': 'إضافة مصروف',
  'log_damage_quick_btn': 'تسجيل هالك',
  'no_expenses_in_period': 'لا توجد مصاريف مسجلة في هذه الفترة',
  'no_damage_in_period': 'لا توجد توالف مسجلة في هذه الفترة',

  // Filters & General Table Keys
  'filter_today': 'اليوم',
  'filter_category': 'تصنيف المصروف',
  'filter_category_label': 'تصنيف المصروف',
  'date_time': 'التاريخ والوقت',
  'records_found': 'سجل',
  'no_notes': 'بدون ملاحظات',
  'no_data_placeholder': 'لا يوجد',

  // Employees & HR Tabs & Tables
  'employees_tab': 'دليل الموظفين',
  'advances_tab': 'سجل السُلف',
  'payroll_tab': 'مسيرات الرواتب',
  'month_period': 'شهر الاستحقاق',
  'net_salary_due': 'صافي المستحق (ج.م)',
  'deducted_from_payroll': 'تم الخصم من الراتب',
  'pending_deduction': 'سُلفة معلقة (غير مخصومة)',
  'employees_list_title': 'سجل العاملين والموظفين',
  'advances_list_title': 'سجل السُلف المالية المنصرفة',
  'payroll_slips_history_title': 'سجل مسيرات الرواتب الصادرة',
  'payment_date': 'تاريخ الصرف',
  'bonuses_and_rewards': 'المكافآت والحوافز',
  'advances_deducted': 'خصم السُلف',
  'penalties_and_deductions': 'الجزاءات والخصومات',
  'net_paid': 'صافي المبلغ المستلم',
  'disbursed_by': 'القائم بالصرف',
  'current_month_advances': 'سُلف الشهر الحالي',
  'payroll_already_disbursed': 'تم صرف مسير الراتب لهذا الشهر بالفعل',
  'no_payroll_slips_found': 'لا توجد مسيرات رواتب مسجلة',
  'from_date': 'من تاريخ',
  'to_date': 'إلى تاريخ',
  'from_label': 'من:',
  'to_label': 'إلى:',
  'select_start_date': 'اختر تاريخ البداية (من تاريخ)',
  'select_end_date': 'اختر تاريخ النهاية (إلى تاريخ)',

  // Common / Suppliers / Invoices / Procurement & Payroll Keys
  'product_name': 'اسم المنتج',
  'sku_barcode': 'كود الصنف / الباركود',
  'product_variation': 'متغير المنتج',
  'recorded_by': 'القائم بالتسجيل',
  'invalid_amount': 'يرجى إدخال مبلغ صحيح',
  'advances_to_deduct': 'سُلف واجبة الخصم',
  'payment_method': 'طريقة الدفع',
  'record_payroll_as_expense': 'تسجيل الراتب في بند المصاريف العامة',
  'record_payroll_as_expense_subtitle': 'إدراج المسير تلقائياً ضمن مصاريف الرواتب التشغيلية',
  'notes': 'الملاحظات',
  'hire_date': 'تاريخ التعيين',
  'employee_active_status': 'حالة الموظف (نشط / متوقف)',
  'address': 'العنوان',
  'alert': 'تنبيه',
  'field_required': 'هذا الحقل مطلوب',
  'currency_egp': 'ج.م',
  'saving': 'جاري الحفظ...',
  'item': 'الصنف',
  'quantity': 'الكمية',
  'price': 'السعر',
  'invoice_ref_label': 'رقم الفاتورة / المرجع',
  'supplier_vendor_required': 'المورّد / الشركة *',
  'btn_new_supplier_short': '+ مورد جديد',
  'invoice_date_label': 'تاريخ الفاتورة',
  'payment_method_label_col': 'طريقة السداد',
  'select_product_hint_catalog': 'اختر منتجاً من الدليل...',
  'cost_price_label': 'سعر التكلفة (ج.م)',
  'add_btn': 'إضافة',
  'items_subtotal_label': 'إجمالي الأصناف:',
  'net_total_amount_label': 'المبلغ الإجمالي الصافي:',
  'balance_due_label': 'المبلغ المتبقي الآجل:',
  'print_preview_invoice_tooltip': 'معاينة وطباعة الفاتورة',
  'due_date_label': 'تاريخ الاستحقاق',
  'immediate': 'فوري',
  'print_export_btn': 'طباعة وتصدير',
  'record_payment_step_btn': 'تسجيل دفعة سداد',
  'enter_valid_amount_warning': 'يرجى إدخال مبلغ سداد صحيح أكبر من الصفر.',
  'payment_recorded_title': 'تم تسجيل السداد',
  'payment_recorded_msg': 'تم تسجيل سند الصرف وتحديث مديونية المورد بنجاح.',
  'record_payment_voucher_title': 'تسجيل سند صرف / سداد لمورّد',
  'record_payment_voucher_desc': 'توثيق دفعة مالية مسددة لحساب المورّد أو لفاتورة مشتريات محددة',
  'supplier_payee_req': 'المورّد المستلم *',
  'balance_due_badge': 'مستحق: {amount}',
  'link_invoice_optional': 'ربط بفاتورة توريد محددة (اختياري)',
  'remaining_badge': 'متبقي: {amount}',
  'amount_paid_req': 'المبلغ المسدد (ج.م) *',
  'amount_is_required': 'المبلغ مطلوب',
  'payment_method_field': 'طريقة الدفع *',
  'tx_ref_label': 'رقم المعاملة / الشيك / الحوالة',
  'payment_notes_field': 'ملاحظات الدفعة / السند',
  'payment_notes_hint': 'أي تفاصيل عن الحوالة أو السند أو المستلم...',
  'supplier_statement_name': 'كشف حساب: {name}',
  'print_statement_tooltip': 'طباعة وتصدير كشف الحساب',
  'total_purchases_kpi': 'إجمالي المشتريات',
  'total_paid_kpi': 'إجمالي المسدد',
  'balance_due_kpi': 'الرصيد المتبقي (مديونية)',
  'purchase_invoice_tx': 'فاتورة توريد مشتريات',
  'items_pieces_count_txt': '({items} أصناف • {pieces} قطعة)',
  'payment_voucher_tx': 'سند صرف وسداد نقدي',
  'ref_prefix': 'مرجع: {ref}',
  'supplier_payout': 'سداد مستحقات توريد',
  'paid_tag': 'مسدد',
  'print_invoice_tooltip': 'طباعة الفاتورة',
  'print_voucher_tooltip': 'طباعة سند الصرف',
  'print_statement_btn': 'طباعة كشف الحساب',
  'pay_vendor_btn': 'سداد دفعة للمورد',
  'printable_purchase_invoice': 'فاتورة شراء وتوريد بضاعة',
  'procurement_erp_title': 'نظام إدارة المشتريات والموردين',
  'supplier_label': 'المورّد:',
  'payment_label': 'الدفع:',
  'item_col': 'الصنف',
  'qty_col': 'الكمية',
  'unit_cost_col': 'سعر الوحدة',
  'subtotal_col': 'الإجمالي',
  'paid_col': 'المسدد',
  'remaining_col': 'المتبقي',
  'grand_total_col': 'الإجمالي الكلي',
  'print_invoice_action': 'طباعة الفاتورة',
  'export_csv_btn': 'تصدير CSV',
  'invoice_csv_downloaded': 'تم تحميل ملف الفاتورة CSV بنجاح',
  'copy_summary_tooltip': 'نسخ ملخص البيانات',
  'summary_copied_to_clipboard': 'تم نسخ ملخص البيانات إلى الحافظة',
  'payment_voucher_receipt': 'سند صرف ودفع نقدي للمورّد',
  'authorized_voucher': 'سند صرف مالي معتمد',
  'amount_paid_label': 'المبلغ المنصرف:',
  'payee_label': 'المستفيد / المورّد:',
  'date_label': 'التاريخ:',
  'method_label': 'طريقة الصرف:',
  'ref_num_label': 'رقم المرجع / الحوالة:',
  'description_label': 'البيان / الغرض:',
  'for_invoice_num': 'سداد لفاتورة مشتريات #{id}',
  'general_account_payment': 'دفعة تحت الحساب الجاري للمورّد',
  'notes_label': 'ملاحظات:',
  'print_voucher_action': 'طباعة سند الصرف',
  'voucher_csv_downloaded': 'تم تحميل سند الصرف CSV بنجاح',
  'supplier_statement_header': 'كشف حساب معاملات المورّد',
  'transaction_history_label': 'سجل الحركات والفواتير وسندات الصرف:',
  'statement_csv_downloaded': 'تم تحميل كشف الحساب CSV بنجاح',

  // POS Direct Variation Catalog Keys
  'grid_view': 'عرض شبكي',
  'list_view': 'عرض جدول / قائمة',
  'in_stock_only': 'المتوفر فقط',
  'items_available_count': '{count} صنف متاح',
  'low_stock_badge': '{count} متبقي فقط',
  'available_stock_badge': '{count} متاح',
  'add_item_btn': 'إضافة',
  'quick_add_tooltip': 'إضافة سريعة للفاتورة',
  'reset_filters': 'إلغاء الفلاتر والبحث',
  'show_cost_price_toggle': 'سعر الشراء (للأدمن)',
  'cost_prefix': 'شراء:',
  'regular_price_label': 'السعر الأصلي:',
  'sale_tag': 'سيل',
  'pos_col_item': 'الصنف والمواصفات',
  'pos_col_stock': 'المخزون المتاح',
  'pos_col_cost': 'سعر التكلفة',
  'pos_col_price': 'سعر البيع',
  'pos_col_action': 'إضافة للفاتورة',
  'pos_tab_catalog': 'المنتجات والمواصفات',
  'pos_tab_cart': 'سلة المبيعات',
};



