const Map<String, String> ar = {
  // App General
  'app_name': 'لوحة تحكم إيجو ستور',
  'dashboard': 'لوحة الإحصائيات',
  'products': 'كتالوج الفيب',
  'categories': 'الأقسام والماركات',
  'orders': 'الطلبات والشحن',
  'banners': 'البانرات الترويجية',
  'coupons': 'أكواد الخصم',
  'customers': 'بيانات العملاء',
  'notifications': 'الإشعارات الجماعية',
  'settings': 'إعدادات المتجر',
  'logout': 'تسجيل الخروج',
  'search': 'بحث سريع...',
  'quick_stats': 'مؤشرات المتجر المباشرة',
  'admin': 'المدير العام',
  'admin_email': 'admin@egostore.com',
  'english': 'English',
  'arabic': 'العربية',
  'live_store_status': 'المتجر يعمل • 99.9%',
  'switch_to_arabic': 'التحويل للعربية',
  'switch_to_english': 'Switch to English',
  'dark_theme': 'الوضع الليلي',
  'light_theme': 'الوضع النهاري',
  'collapse_sidebar': 'طي القائمة',
  'expand_sidebar': 'توسيع القائمة',
  'all_items': 'جميع الأصناف',
  'all_categories': 'جميع الأقسام',
  'reload': 'إعادة التحميل',
  'showing_entries': 'عرض {start}-{end} من {total} سجل',
  'page_x_of_y': 'صفحة {page} من {total}',
  'no_records_found': 'لا توجد سجلات مطابقة في قاعدة البيانات',
  'clear_search': 'مسح البحث',
  'items_count': '{count} عنصر',
  'products_count_label': '{count} منتج',
  'times_used': '{count} مرة',
  'devices_count': '{count} جهاز',
  'featured': 'مميز',
  'active': 'مفعل',
  'inactive': 'معطل',

  // Search Hints
  'search_hint_general': 'بحث سريع...',
  'search_products_hint': 'بحث باسم المنتج، الماركة، النكهة، أو الـ SKU...',
  'search_orders_hint': 'بحث برقم الطلب، اسم العميل، الهاتف، أو المدينة...',
  'search_customers_hint': 'بحث باسم العميل، البريد، الهاتف، أو المدينة...',
  'search_categories_hint': 'بحث في الأقسام...',
  'search_brands_hint': 'بحث في الماركات...',
  'search_coupons_hint': 'بحث بأكواد الخصم...',
  'search_banners_hint': 'بحث في البانرات...',
  'search_broadcasts_hint': 'بحث في الإشعارات الجماعية...',

  // Dashboard Screen
  'executive_overview': 'نظرة عامة تنفيذية',
  'executive_overview_sub': 'متابعة حية للعمليات، صحة مخزون الفيب، والمؤشرات المالية',
  'kpi_total_revenue': 'إجمالي الإيرادات',
  'kpi_today_orders': 'طلبات اليوم',
  'kpi_active_customers': 'العملاء النشطون',
  'kpi_avg_order_val': 'متوسط قيمة الطلب',
  'kpi_low_stock_alerts': 'تنبيهات انخفاض المخزون',
  'kpi_pending_dispatch': 'طلبات بانتظار الشحن',
  'revenue_analytics': 'مؤشرات المبيعات والإيرادات',
  'best_selling_categories': 'المبيعات حسب القسم',
  'brand_market_share': 'حصة الماركات (أجهزة وسوائل)',
  'recent_orders': 'أحدث الطلبات الواردة',
  'low_inventory_warnings': 'تنبيهات استكمال النواقص',
  'view_all': 'عرض الكل',
  'export_csv': 'تصدير التقرير',

  // Products & Variation Matrix
  'products_subtitle': 'إدارة السوائل الإلكترونية، الأجهزة والمودات، البودات، والكويلات مع مصفوفات المتغيرات',
  'add_product': 'إضافة منتج جديد',
  'edit_product': 'تعديل المنتج',
  'delete_product': 'حذف الصنف',
  'delete_product_confirm': 'هل أنت متأكد من حذف هذا الصنف من الكتالوج وقاعدة البيانات؟',
  'product_title': 'الصنف / Product',
  'product_type_col': 'النوع (Type)',
  'product_brand_col': 'الماركة / Brand',
  'product_price_col': 'السعر (ج.م)',
  'product_stock_col': 'المخزون',
  'product_vars_col': 'المتغيرات',
  'product_actions_col': 'الإجراءات',
  'view_product_details': 'عرض تفاصيل الصنف',
  'no_products_found': 'لا توجد منتجات مسجلة في الكتالوج حتى الآن',
  'flavors_label': 'نكهات:',
  'simple_product': 'بسيط (Simple)',
  'skus_count': '{count} SKUs',
  'product_desc': 'الوصف',
  'category': 'القسم',
  'brand': 'الماركة',
  'base_price': 'السعر الأساسي (ج.م)',
  'sale_price': 'سعر العرض (ج.م)',
  'total_stock': 'إجمالي المخزون',
  'sku': 'كود الصنف (SKU)',
  'is_featured': 'منتج مميز',
  'product_type': 'نوع المنتج',
  'simple': 'بسيط',
  'variable': 'متعدد المتغيرات (مصفوفة الفيب)',
  'liquid_matrix': 'مصفوفة الليكويد (النيكوتين والحجم)',
  'hardware_matrix': 'مصفوفة الأجهزة (اللون والمقاومة)',
  'nicotine_levels': 'نسب النيكوتين',
  'bottle_sizes': 'أحجام العبوات',
  'device_colors': 'ألوان الجهاز',
  'coil_resistances': 'مقاومات الكويل',
  'generate_matrix': 'توليد مصفوفة المتغيرات',
  'stock_status': 'حالة المخزون',
  'in_stock': 'متوفر',
  'low_stock': 'مخزون منخفض',
  'out_of_stock': 'نفد المخزون',
  'actions': 'الإجراءات',
  'delete': 'حذف',
  'edit': 'تعديل',
  'save': 'حفظ التغييرات',
  'cancel': 'إلغاء',
  'confirm': 'تأكيد',
  'confirm_delete': 'هل أنت متأكد من حذف هذا العنصر؟',
  'type_liquid': 'سوائل إلكترونية (E-Liquids)',
  'type_liquid_short': 'سوائل (Liquids)',
  'type_liquid_desc': 'سولت نيكوتين وفري بيز مع النكهات وسحب MTL/DL',
  'type_device': 'أجهزة ومودات (Devices & Mods)',
  'type_device_short': 'أجهزة (Devices)',
  'type_device_desc': 'أجهزة فيب وبود كيت مع خيارات الألوان والبطارية',
  'type_pod': 'بودات وخراطيش (Pods & Cartridges)',
  'type_pod_short': 'بودات (Pods)',
  'type_pod_desc': 'بودات وخراطيش أجهزة مع خيارات المقاومة والسعة',
  'type_coil': 'كويلات (Replacement Coils)',
  'type_coil_short': 'كويلات (Coils)',
  'type_coil_desc': 'كويلات مقاومة للشبكات مع خيارات المقاومة ونوع السلك',
  'type_accessory': 'إكسسوارات ومستلزمات (Accessories)',
  'type_accessory_short': 'إكسسوارات',
  'type_accessory_desc': 'بطاريات وشواحن وقطن وزجاج وأدوات الصيانة',
  'step_type': '١. اختيار النوع',
  'step_specs': '٢. المواصفات الديناميكية',
  'step_matrix': '٣. مصفوفة المتغيرات',
  'step_review': '٤. المراجعة والحفظ',
  'flavor': 'النكهة',
  'add_flavor': 'أضف نكهة جديدة',
  'new_flavor_title': 'إضافة نكهة جديدة',
  'vape_style': 'نوع السحبة (Vaping Style)',
  'style_mtl': 'MTL (سحبة سيجارة)',
  'style_dl': 'DL (سحبة شيشة مباشرة)',
  'style_both': 'كلاهما (MTL & DL)',
  'max_wattage': 'أقصى قدرة وات (Max Wattage)',
  'battery_type': 'نوع البطارية',
  'battery_integrated': 'بطارية مدمجة (Built-in)',
  'battery_external': 'بطاريات خارجية (18650 / 21700)',
  'pod_capacity': 'سعة البود (مل)',
  'pack_size': 'عدد القطع بالعلبة',
  'wire_material': 'نوع السلك',
  'accessory_sub': 'نوع الملحق',

  // Categories & Brands
  'vape_categories_title': 'أقسام الفيب',
  'categories_subtitle': 'إدارة أنظمة البود، السولت نيكوتين، الأجهزة والمستلزمات',
  'no_categories_found': 'لا توجد أقسام مسجلة. أضف قسمك الأول.',
  'add_category': 'إضافة قسم',
  'edit_category': 'تعديل القسم',
  'category_name': 'اسم القسم',
  'products_count': 'عدد المنتجات',
  'vape_brands_title': 'ماركات الفيب الرسمية',
  'brands_subtitle': 'الشركات المصنعة للأجهزة وماركات السوائل الإلكترونية',
  'no_brands_found': 'لا توجد ماركات مسجلة. أضف ماركتك الأولى.',
  'add_brand': 'إضافة ماركة',
  'edit_brand': 'تعديل الماركة',
  'brand_name': 'اسم الماركة',
  'catalog_items': 'أصناف الكتالوج',

  // Orders Screen
  'orders_title': 'إدارة وشحن طلبات الفيب',
  'orders_subtitle': 'متابعة الطلبات المباشرة مع عناوين العملاء وأرقام الهواتف وتفاصيل الأصناف',
  'no_orders_found': 'لا توجد طلبات مسجلة. ستظهر طلبات العملاء الجديدة هنا مباشرة.',
  'order_id': 'رقم الطلب',
  'order_number': 'طلب رقم #{id}',
  'current_status': 'الحالة الحالية',
  'customer': 'العميل',
  'customer_delivery_address': 'بيانات العميل وعنوان التوصيل',
  'payment': 'طريقة الدفع',
  'status': 'الحالة',
  'total': 'الإجمالي (ج.م)',
  'date': 'التاريخ',
  'items_ordered_count': '{count} صنف',
  'dispatch_action': 'تجهيز وشحن',
  'status_all': 'جميع الطلبات',
  'status_pending': 'قيد الانتظار',
  'status_processing': 'جاري التجهيز',
  'status_shipped': 'تم الشحن',
  'status_delivered': 'تم التسليم',
  'status_cancelled': 'ملغي',
  'update_status': 'تحديث حالة الطلب',
  'order_details': 'تفاصيل الطلب',
  'shipping_address': 'عنوان الشحن',
  'ordered_items': 'المنتجات المطلوبة',
  'ordered_items_label': 'الأصناف المطلوبة',
  'subtotal': 'المجموع الفرعي',
  'shipping_fee': 'مصاريف الشحن',
  'delivery_fee': 'مصاريف التوصيل',
  'free_delivery_notice': 'شحن مجاني',
  'discount': 'الخصم',
  'discount_applied': 'خصم ترويجي',
  'tax_fee': 'الضريبة / القيمة المضافة',
  'grand_total': 'الإجمالي النهائي',
  'phone': 'رقم الهاتف',
  'city': 'المدينة',
  'free_shipping_applied': 'شحن مجاني (للطلبات >= 2000 ج.م)',
  'copy_order_id': 'نسخ رقم الطلب',
  'copy_phone': 'نسخ الهاتف',
  'whatsapp_chat': 'محادثة واتساب',
  'customer_notes': 'ملاحظات العميل الخاصة',
  'no_customer_notes': 'لا توجد ملاحظات إضافية من العميل',
  'item_subtotal': 'الإجمالي: {amount}',
  'item_sku': 'كود: {sku}',
  'item_brand': 'الماركة: {brand}',
  'print_invoice': 'طباعة الفاتورة',
  'invoice_title': 'فاتورة طلب مبيعات',
  'payment_status_label': 'حالة السداد',
  'paid': 'تم السداد',
  'unpaid': 'غير مسدد',
  'cash_on_delivery': 'الدفع عند الاستلام',
  'raw_data_inspector': 'البيانات التقنية للطلب (Firestore)',
  'order_time': 'وقت إنشاء الطلب',
  'delivery_date_label': 'تاريخ التوصيل',
  'tracking_number_label': 'رقم التتبع والشحن',
  'copied_to_clipboard': 'تم النسخ إلى الحافظة',
  'no_items_in_order': 'لم يتم العثور على قائمة أصناف مفصلة لهذا الطلب',
  'view_order_details': 'عرض تفاصيل الطلب',
  'coupon_code_label': 'كود الخصم المستخدم',
  'share_with_courier': 'مشاركة مع المندوب',
  'share_order': 'مشاركة الطلب',
  'courier_share_title': 'مشاركة بيانات الطلب مع المندوب',
  'courier_share_subtitle': 'تجهيز وإرسال تفاصيل الطلب، العنوان، ورابط الخريطة',
  'send_via_whatsapp': 'إرسال عبر واتساب',
  'share_via_whatsapp_contacts': 'إرسال لواتساب (اختيار المندوب)',
  'select_courier_whatsapp': 'فتح واتساب لاختيار المندوب وإرسال الطلب فوراً',
  'share_via_system': 'مشاركة عبر التطبيقات الأخرى',
  'copy_courier_slip': 'نسخ ملخص التوصيل',

  'open_in_google_maps': 'فتح في خرائط جوجل',
  'call_customer': 'اتصال بالعميل',
  'courier_phone_hint': 'رقم هاتف المندوب (اختياري)...',
  'courier_phone_label': 'رقم المندوب',
  'share_slip_copied': 'تم نسخ ملخص التوصيل بنجاح',
  'preview_courier_slip': 'معاينة رسالة المندوب',
  'maps_link': 'رابط موقع الخريطة',
  'amount_to_collect': 'المبلغ المطلوب تحصيله',
  'open_maps': 'الخريطة',


  // Banners & Coupons
  'banners_title': 'البانرات الترويجية الرئيسية',
  'banners_subtitle': 'سلايدر العروض الترويجية المعروض في تطبيق وموقع إيجو ستور',
  'no_banners_found': 'لا توجد بانرات ترويجية. أنشئ بانرك الترويجي الأول.',
  'add_banner': 'إضافة بانر',
  'preview': 'المعاينة',
  'banner_title_col': 'عنوان البانر',
  'target_destination': 'وجهة التحويل',
  'banner_image': 'رابط صورة البانر',
  'target_screen': 'وجهة التحويل',
  'coupons_title': 'أكواد الخصم والعروض الترويجية',
  'coupons_subtitle': 'إدارة نسب الخصم والحد الأدنى للطلب وتواريخ الصلاحية',
  'no_coupons_found': 'لا توجد أكواد خصم. أنشئ كود خصم جديد.',
  'add_coupon': 'إنشاء كود خصم',
  'coupon_code': 'كود الخصم',
  'discount_percentage': 'نسبة الخصم',
  'min_cart_requirement': 'الحد الأدنى للطلب',
  'redemptions': 'مرات الاستخدام',
  'expiry_date': 'تاريخ الانتهاء',
  'no_minimum': 'بدون حد أدنى',
  'off_discount': '{percent}% خصم',

  // Notifications & Broadcasts
  'broadcasts_title': 'إشعارات FCM الجماعية',
  'broadcasts_subtitle': 'إرسال إعلانات مباشرة، عروض ترويجية وتنبيهات توفر المخزون للهواتف',
  'no_broadcasts_found': 'لم يتم إرسال إشعارات جماعية حتى الآن.',
  'compose_broadcast': 'إنشاء إشعار جماعي',
  'broadcast_title': 'عنوان الإشعار',
  'broadcast_body': 'نص رسالة الإشعار',
  'target_audience': 'الجمهور المستهدف',
  'devices_reached': 'الأجهزة المستلمة',
  'all_users': 'جميع مستخدمي التطبيق',
  'topic_salt_nic': 'محبو السالت نيكوتين',
  'topic_hardware': 'عروض الأجهزة والمودات',
  'send_broadcast': 'إرسال الإشعار الآن',
  'sent_history': 'سجل الإشعارات المرسلة',
  'sent_at': 'وقت الإرسال',

  // Customers Screen
  'customers_title': 'سجل وبيانات العملاء (CRM)',
  'customers_subtitle': 'سجل مشتريات العملاء، العناوين، إجمالي الإنفاق والصلاحيات',
  'no_customers_found': 'لا يوجد عملاء مسجلون في قاعدة البيانات.',
  'customer_name': 'اسم العميل',
  'email': 'البريد الإلكتروني',
  'city_col': 'المدينة',
  'total_orders': 'إجمالي الطلبات',
  'lifetime_spend': 'إجمالي الإنفاق (ج.م)',
  'customer_role': 'الدور',
  'view_profile': 'عرض الملف الشخصي',

  // Settings
  'contact_support_title': 'بيانات التواصل الرسمية للمتجر',
  'store_phone': 'هاتف خدمة العملاء',
  'whatsapp_number': 'رقم الواتساب الرسمي',
  'support_email': 'البريد الإلكتروني للدعم',
  'store_address': 'مقر المتجر الرئيسي',
  'regulatory_settings': 'الامتثال الصحي واللوائح',
  'age_verification': 'التحقق الإلزامي من العمر (18+ / 21+)',
  'nicotine_warning_banner': 'شريط التحذير الصحي الإلزامي للنيكوتين',
  'save_settings': 'حفظ إعدادات المتجر',

  // Feedback Alerts
  'success': 'تم بنجاح',
  'error': 'خطأ',
  'warning': 'تنبيه',
  'item_created': 'تم إنشاء العنصر بنجاح!',
  'item_updated': 'تم تحديث العنصر بنجاح!',
  'item_deleted': 'تم حذف العنصر بنجاح!',
  'order_status_updated': 'تم تحديث حالة الطلب وإرسال إشعار للعميل!',
  'broadcast_sent': 'تم إرسال الإشعار لجميع الأجهزة المستهدفة!',
  'settings_saved': 'تم حفظ إعدادات المتجر بنجاح!',
};
