const Map<String, String> en = {
  // App General
  'app_name': 'EGO Store Admin',
  'dashboard': 'Dashboard',
  'products': 'Vape Catalog',
  'categories': 'Categories & Brands',
  'orders': 'Orders & Dispatch',
  'banners': 'Hero Banners',
  'coupons': 'Promo Codes',
  'customers': 'Customers CRM',
  'notifications': 'Push Broadcasts',
  'settings': 'Store Settings',
  'logout': 'Sign Out',
  'search': 'Search anything...',
  'quick_stats': 'Live Store Metrics',
  'admin': 'Super Admin',
  'admin_email': 'admin@egostore.com',
  'english': 'English',
  'arabic': 'العربية',
  'live_store_status': 'Live Store • 99.9%',
  'switch_to_arabic': 'التحويل للعربية',
  'switch_to_english': 'Switch to English',
  'dark_theme': 'Dark Theme',
  'light_theme': 'Light Theme',
  'collapse_sidebar': 'Collapse Sidebar',
  'expand_sidebar': 'Expand Sidebar',
  'all_items': 'All Items',
  'all_categories': 'All Categories',
  'reload': 'Reload',
  'showing_entries': 'Showing {start}-{end} of {total} entries',
  'page_x_of_y': 'Page {page} of {total}',
  'no_records_found': 'No records found in database',
  'clear_search': 'Clear search',
  'items_count': '{count} items',
  'products_count_label': '{count} products',
  'times_used': '{count} times',
  'devices_count': '{count} devices',
  'featured': 'Featured',
  'active': 'Active',
  'inactive': 'Inactive',

  // Search Hints
  'search_hint_general': 'Search...',
  'search_products_hint': 'Search product, brand, flavor, SKU...',
  'search_orders_hint': 'Search order #, customer, city, phone...',
  'search_customers_hint': 'Search customer name, email, phone, city...',
  'search_categories_hint': 'Search categories...',
  'search_brands_hint': 'Search brands...',
  'search_coupons_hint': 'Search promo codes...',
  'search_banners_hint': 'Search banners...',
  'search_broadcasts_hint': 'Search push broadcasts...',

  // Dashboard Screen
  'executive_overview': 'Executive Overview',
  'executive_overview_sub': 'Real-time operations, vape inventory health & financial metrics',
  'kpi_total_revenue': 'Total Revenue',
  'kpi_today_orders': "Today's Orders",
  'kpi_active_customers': 'Active Customers',
  'kpi_avg_order_val': 'Avg. Order Value',
  'kpi_low_stock_alerts': 'Low Stock Warnings',
  'kpi_pending_dispatch': 'Pending Orders',
  'revenue_analytics': 'Revenue & Order Trends',
  'best_selling_categories': 'Sales by Category',
  'brand_market_share': 'Hardware & Liquid Brand Share',
  'recent_orders': 'Recent Live Orders',
  'low_inventory_warnings': 'Urgent Stock Replenishment',
  'view_all': 'View All',
  'export_csv': 'Export Report',

  // Products & Variation Matrix
  'products_subtitle': 'Manage e-liquids, vape devices, mods, pods, and coils with full variation matrix',
  'add_product': 'Add New Product',
  'edit_product': 'Edit Product',
  'delete_product': 'Delete Product',
  'delete_product_confirm': 'Are you sure you want to delete this product from catalog and database?',
  'product_title': 'Product / Item',
  'product_type_col': 'Type',
  'product_brand_col': 'Brand',
  'product_price_col': 'Price (EGP)',
  'product_stock_col': 'Stock',
  'product_vars_col': 'Variations',
  'product_actions_col': 'Actions',
  'view_product_details': 'View Product Details',
  'no_products_found': 'No products found in catalog yet',
  'flavors_label': 'Flavors:',
  'simple_product': 'Simple',
  'skus_count': '{count} SKUs',
  'product_desc': 'Description',
  'category': 'Category',
  'brand': 'Brand',
  'base_price': 'Base Price (EGP)',
  'sale_price': 'Sale Price (EGP)',
  'total_stock': 'Total Stock',
  'sku': 'SKU',
  'is_featured': 'Featured Product',
  'product_type': 'Product Type',
  'simple': 'Simple',
  'variable': 'Variable (Vape Matrix)',
  'liquid_matrix': 'E-Liquid Matrix (Nicotine & Size)',
  'hardware_matrix': 'Hardware Matrix (Color & Resistance)',
  'nicotine_levels': 'Nicotine Strengths',
  'bottle_sizes': 'Bottle Sizes',
  'device_colors': 'Device Colors',
  'coil_resistances': 'Coil Resistances',
  'generate_matrix': 'Generate Variations Matrix',
  'stock_status': 'Stock Status',
  'in_stock': 'In Stock',
  'low_stock': 'Low Stock',
  'out_of_stock': 'Out of Stock',
  'actions': 'Actions',
  'delete': 'Delete',
  'edit': 'Edit',
  'save': 'Save Changes',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'confirm_delete': 'Are you sure you want to delete this item?',
  'type_liquid': 'E-Liquids (SaltNic / Freebase)',
  'type_liquid_short': 'Liquids',
  'type_liquid_desc': 'E-liquids with custom flavors, MTL/DL styles & nicotine sizes',
  'type_device': 'Devices & Vape Mods',
  'type_device_short': 'Devices',
  'type_device_desc': 'Pod kits, box mods with battery & color finishes',
  'type_pod': 'Pods & Cartridges',
  'type_pod_short': 'Pods',
  'type_pod_desc': 'Replacement pods with capacity, resistance & compatibility',
  'type_coil': 'Replacement Coils',
  'type_coil_short': 'Coils',
  'type_coil_desc': 'Mesh & regular coils with resistance options and wire materials',
  'type_accessory': 'Vape Accessories',
  'type_accessory_short': 'Accessories',
  'type_accessory_desc': 'Batteries, chargers, cotton, replacement glass & toolkits',
  'step_type': '1. Choose Type',
  'step_specs': '2. Dynamic Specs',
  'step_matrix': '3. Variations Matrix',
  'step_review': '4. Review & Publish',
  'flavor': 'Flavor',
  'add_flavor': 'Add New Flavor',
  'new_flavor_title': 'Add Custom Flavor',
  'vape_style': 'Vaping Style',
  'style_mtl': 'MTL (Mouth-To-Lung)',
  'style_dl': 'DL (Direct-Lung)',
  'style_both': 'Both (MTL & DL)',
  'max_wattage': 'Max Wattage (W)',
  'battery_type': 'Battery System',
  'battery_integrated': 'Built-in Battery',
  'battery_external': 'External Cells (18650 / 21700)',
  'pod_capacity': 'Pod Capacity (ml)',
  'pack_size': 'Pack Size / Pieces',
  'wire_material': 'Wire Material',
  'accessory_sub': 'Accessory Type',

  // Categories & Brands
  'vape_categories_title': 'Vape Categories',
  'categories_subtitle': 'Manage pod systems, salt nic, hardware & accessories',
  'no_categories_found': 'No categories found. Create your first category.',
  'add_category': 'Add Category',
  'edit_category': 'Edit Category',
  'category_name': 'Category Name',
  'products_count': 'Products',
  'vape_brands_title': 'Official Vape Brands',
  'brands_subtitle': 'Hardware manufacturers & e-liquid brands',
  'no_brands_found': 'No brands found. Create your first brand.',
  'add_brand': 'Add Brand',
  'edit_brand': 'Edit Brand',
  'brand_name': 'Brand Name',
  'catalog_items': 'Catalog Items',

  // Orders Screen
  'orders_title': 'Vape Order Fulfillment & Dispatch',
  'orders_subtitle': 'Live orders feed with customer address, phone, and variation details',
  'no_orders_found': 'No orders found. New customer orders will appear here in real-time.',
  'order_id': 'Order ID',
  'order_number': 'Order #{id}',
  'current_status': 'Current Status',
  'customer': 'Customer',
  'customer_delivery_address': 'Customer & Delivery Address',
  'payment': 'Payment Method',
  'status': 'Status',
  'total': 'Total (EGP)',
  'date': 'Date',
  'items_ordered_count': '{count} items',
  'dispatch_action': 'Dispatch',
  'status_all': 'All Orders',
  'status_pending': 'Pending',
  'status_processing': 'Processing',
  'status_shipped': 'Shipped',
  'status_delivered': 'Delivered',
  'status_cancelled': 'Cancelled',
  'update_status': 'Update Order Status',
  'order_details': 'Order Details',
  'shipping_address': 'Shipping Address',
  'ordered_items': 'Ordered Items',
  'ordered_items_label': 'Ordered Items',
  'subtotal': 'Subtotal',
  'shipping_fee': 'Delivery Fee',
  'delivery_fee': 'Delivery Fee',
  'free_delivery_notice': 'Free',
  'discount': 'Discount',
  'discount_applied': 'Promo Discount',
  'tax_fee': 'Tax / VAT',
  'grand_total': 'Grand Total',
  'phone': 'Phone Number',
  'city': 'City',
  'free_shipping_applied': 'Free Shipping (Orders >= 2000 EGP)',
  'copy_order_id': 'Copy Order ID',
  'copy_phone': 'Copy Phone',
  'whatsapp_chat': 'WhatsApp Chat',
  'customer_notes': 'Customer Special Notes',
  'no_customer_notes': 'No special notes provided',
  'item_subtotal': 'Subtotal: {amount}',
  'item_sku': 'SKU: {sku}',
  'item_brand': 'Brand: {brand}',
  'print_invoice': 'Print Invoice',
  'invoice_title': 'Sales Order Invoice',
  'payment_status_label': 'Payment Status',
  'paid': 'Paid',
  'unpaid': 'Unpaid',
  'cash_on_delivery': 'Cash on Delivery',
  'raw_data_inspector': 'Technical Data Payload (Firestore)',
  'order_time': 'Order Placed At',
  'delivery_date_label': 'Delivery Date',
  'tracking_number_label': 'Tracking Number',
  'copied_to_clipboard': 'Copied to clipboard',
  'no_items_in_order': 'No detailed items list found for this order',
  'view_order_details': 'View Order Details',
  'coupon_code_label': 'Promo Code Applied',
  'share_with_courier': 'Share with Courier',
  'share_order': 'Share Order',
  'courier_share_title': 'Share Order with Courier',
  'courier_share_subtitle': 'Prepare & dispatch order details, address, and Google Maps link',
  'send_via_whatsapp': 'Send via WhatsApp',
  'share_via_whatsapp_contacts': 'Share to WhatsApp (Select Courier)',
  'select_courier_whatsapp': 'Open WhatsApp to pick courier from contacts',
  'share_via_system': 'Share via Other Apps',
  'copy_courier_slip': 'Copy Delivery Slip',

  'open_in_google_maps': 'Open in Google Maps',
  'call_customer': 'Call Customer',
  'courier_phone_hint': 'Courier phone number (optional)...',
  'courier_phone_label': 'Courier Phone',
  'share_slip_copied': 'Delivery slip copied to clipboard',
  'preview_courier_slip': 'Courier Message Preview',
  'maps_link': 'Google Maps Link',
  'amount_to_collect': 'Amount to Collect',
  'open_maps': 'Maps',


  // Banners & Coupons
  'banners_title': 'Hero Promotional Banners',
  'banners_subtitle': 'Top promotional sliders displayed on EGO Store mobile & web app home',
  'no_banners_found': 'No promotional banners found. Create your first banner slider.',
  'add_banner': 'Add Banner',
  'preview': 'Preview',
  'banner_title_col': 'Banner Title',
  'target_destination': 'Target Destination',
  'banner_image': 'Banner Image URL',
  'target_screen': 'Target Navigation Route',
  'coupons_title': 'Vape Promo Codes & Flash Sale Coupons',
  'coupons_subtitle': 'Configure percentage discounts, cart thresholds, and expiration dates',
  'no_coupons_found': 'No discount coupons found. Create your first promo code.',
  'add_coupon': 'Create Promo Code',
  'coupon_code': 'Promo Code',
  'discount_percentage': 'Discount',
  'min_cart_requirement': 'Min Cart Requirement',
  'redemptions': 'Redemptions',
  'expiry_date': 'Expiry Date',
  'no_minimum': 'No Minimum',
  'off_discount': '{percent}% OFF',

  // Notifications & Broadcasts
  'broadcasts_title': 'FCM Push Notification Broadcasts',
  'broadcasts_subtitle': 'Send direct announcements, promotional deals & stock alerts to customer devices',
  'no_broadcasts_found': 'No push notifications sent yet. Create your first broadcast announcement.',
  'compose_broadcast': 'Compose Broadcast',
  'broadcast_title': 'Notification Title',
  'broadcast_body': 'Message Body',
  'target_audience': 'Target Audience',
  'devices_reached': 'Devices Reached',
  'all_users': 'All App Users',
  'topic_salt_nic': 'SaltNic Vapers',
  'topic_hardware': 'Hardware Deals Seekers',
  'send_broadcast': 'Send Broadcast Now',
  'sent_history': 'Broadcast History',
  'sent_at': 'Sent Date',

  // Customers Screen
  'customers_title': 'EGO Customer CRM & Profiles',
  'customers_subtitle': 'View customer purchase history, addresses, lifetime value & roles',
  'no_customers_found': 'No registered customers found in database.',
  'customer_name': 'Customer Name',
  'email': 'Email',
  'city_col': 'City',
  'total_orders': 'Total Orders',
  'lifetime_spend': 'Lifetime Spend (EGP)',
  'customer_role': 'Role',
  'view_profile': 'View Profile',

  // Settings
  'contact_support_title': 'Store Official Contact Info',
  'store_phone': 'Customer Care Phone',
  'whatsapp_number': 'Official WhatsApp Line',
  'support_email': 'Support Email',
  'store_address': 'Store Headquarters Address',
  'regulatory_settings': 'Regulatory & Health Compliance',
  'age_verification': 'Mandatory 18+ Age Gate Policy',
  'nicotine_warning_banner': 'Statutory Nicotine Health Warning Header',
  'save_settings': 'Save Store Settings',

  // Feedback Alerts
  'success': 'Success',
  'error': 'Error',
  'warning': 'Warning',
  'item_created': 'Item created successfully!',
  'item_updated': 'Item updated successfully!',
  'item_deleted': 'Item deleted successfully!',
  'order_status_updated': 'Order status updated and notification sent!',
  'broadcast_sent': 'Push notification broadcasted to devices!',
  'settings_saved': 'Store settings saved successfully!',
};
