const Map<String, String> en = {
  // App General
  'app_name': 'EGO Store Admin',
  'dashboard': 'Dashboard',
  'products': 'Vape Catalog',
  'categories': 'Categories & Brands',
  'brands': 'Brands',
  'orders': 'Orders & Dispatch',
  'banners': 'Hero Banners',
  'coupons': 'Promo Codes',
  'customers': 'Customers CRM',
  'notifications': 'Push Broadcasts',
  'settings': 'Store Settings',
  'logout': 'Sign Out',
  'search': 'Search anything...',
  'quick_stats': 'Live Store Metrics',
  'admin': 'Super Admin',
  'admin_email': 'admin@egostore.com',
  'english': 'English',
  'arabic': 'العربية',
  'switch_to_arabic': 'التحويل للعربية',
  'switch_to_english': 'Switch to English',
  'dark_theme': 'Dark Theme',
  'light_theme': 'Light Theme',
  'collapse_sidebar': 'Collapse Sidebar',
  'expand_sidebar': 'Expand Sidebar',
  'all_items': 'All Items',
  'all_categories': 'All Categories',
  'reload': 'Reload',
  'showing_entries': 'Showing {start}-{end} of {total} entries',
  'page_x_of_y': 'Page {page} of {total}',
  'no_records_found': 'No records found in database',
  'clear_search': 'Clear search',
  'items_count': '{count} items',
  'products_count_label': '{count} products',
  'times_used': '{count} times',
  'devices_count': '{count} devices',
  'featured': 'Featured',
  'active': 'Active',
  'inactive': 'Inactive',
  'is_online': 'Publish to Online App',
  'is_online_desc': 'If disabled, the product will only be available in POS/Store and hidden from mobile app users',
  'online_status': 'Online Status',
  'published_online': 'Published in Online App',
  'pos_only': 'POS / Store Only',
  'online_and_pos': 'Online & POS',
  'sales_channel': 'Sales Channel',
  'all_channels': 'All Channels',
  'workspace_mode': 'Workspace Mode',
  'mode_all': 'All Modules',
  'mode_ecommerce': 'E-Commerce',
  'mode_erp': 'ERP Operations',
  'ecommerce_section': 'E-Commerce Management',
  'erp_section': 'ERP & Operations',
  'system_section': 'System & Settings',

  // Search Hints
  'search_hint_general': 'Search...',
  'search_products_hint': 'Search product, brand, flavor, SKU...',
  'search_orders_hint': 'Search order #, customer, city, phone...',
  'search_customers_hint': 'Search customer name, email, phone, city...',
  'search_categories_hint': 'Search categories...',
  'search_brands_hint': 'Search brands...',
  'search_coupons_hint': 'Search promo codes...',
  'search_banners_hint': 'Search banners...',
  'search_broadcasts_hint': 'Search push broadcasts...',

  // Dashboard Screen
  'executive_overview': 'Executive Overview',
  'executive_overview_sub':
      'Real-time operations, vape inventory health & financial metrics',
  'kpi_total_revenue': 'Total Revenue',
  'kpi_net_profit': 'Net Profit',
  'kpi_supplier_payables': 'Supplier Payables (Due)',
  'kpi_supplier_purchases': 'Inflow Purchases Cost',
  'kpi_supplier_paid': 'Paid to Suppliers',
  'kpi_cogs': 'Cost of Goods Sold (COGS)',
  'kpi_profit_margin': 'Profit Margin',
  'cost_price': 'Cost Price',
  'profit_margin': 'Profit Margin',
  'net_profit': 'Net Profit',
  'kpi_today_orders': "Today's Orders",
  'kpi_active_customers': 'Active Customers',
  'kpi_avg_order_val': 'Avg. Order Value',
  'kpi_low_stock_alerts': 'Low Stock Warnings',
  'kpi_pending_dispatch': 'Pending Orders',
  'supplier_financials_title': 'Supplier Payables & Inflow Financials',
  'supplier_financials_subtitle':
      'Track stock purchases volume, payments disbursed, and outstanding liabilities',
  'supplier_balance_due_desc':
      'Total outstanding balance owed to suppliers by admin',
  'top_due_suppliers': 'Top Suppliers with Balance Due',
  'all_suppliers_settled':
      'All supplier accounts are settled in full. No outstanding balance.',
  'pay_supplier_btn': 'Pay Vendor',
  'view_suppliers_hub': 'Open Suppliers Hub',
  'revenue_analytics': 'Revenue & Order Trends',
  'best_selling_categories': 'Sales by Category',
  'brand_market_share': 'Hardware & Liquid Brand Share',
  'recent_orders': 'Recent Live Orders',
  'export_csv': 'Export Report',

  // Dashboard Sub-components & Analytics
  'dashboard_date_filter_title': 'Sales & Profit Timeframe:',
  'kpi_status_active': 'Active',
  'kpi_status_opex': 'OpEx',
  'kpi_status_due': 'Due',
  'kpi_status_settled': 'Settled',
  'kpi_orders_count_today': '{count} today',
  'kpi_orders_count_badge': '{count} Orders',
  'kpi_low_stock_urgent': '{count} urgent',
  'kpi_low_stock_healthy': 'Healthy',
  'kpi_items_count_badge': '{count} Items',
  'sales_channel_title': 'Sales & Net Profit by Channel',
  'sales_channel_subtitle': 'Breakdown of Online App vs In-Store POS vs Total Performance',
  'channel_online_share': 'Online App: {percent}%',
  'channel_pos_share': 'Branch POS: {percent}%',
  'channel_online_title': 'Online App (App)',
  'channel_online_subtitle': 'Delivery & Dispatch Orders',
  'channel_pos_title': 'Branch POS (POS)',
  'channel_pos_subtitle': 'In-Store Walk-in Sales',
  'channel_total_title': 'Consolidated Total (Total)',
  'channel_total_subtitle': 'Online + In-Store POS',
  'transactions_count_badge': '{count} transactions',
  'metric_total_sales_label': 'Total Revenue:',
  'metric_cogs_label': 'Cost of Goods Sold (COGS):',
  'metric_net_profit_label': 'Net Profit:',
  'metric_avg_ticket_label': 'Avg. Ticket Value:',
  'metric_refunds_label': 'Refunds & Returns ({count}):',
  'btn_view_product_sales': 'View Itemized Product Sales Breakdown',
  'products_sold_count_badge': '{count} Products Sold',
  'btn_view_product_sales_subtitle': 'View quantity sold, unit costs, and net profit per SKU',
  'revenue_chart_title': 'Revenue & Sales Trajectory',
  'revenue_chart_subtitle': 'Weekly revenue performance in Egyptian Pounds (EGP)',
  'last_7_days': 'Last 7 Days',
  'no_revenue_history_7_days': 'No revenue history for the last 7 days yet',
  'brand_share_title': 'Brand Market Distribution',
  'brand_share_subtitle': 'Hardware & E-Liquid catalog share',
  'no_brand_distribution_data': 'No brand distribution data available',
  'live_orders_feed_title': 'Live Order Dispatch Feed',
  'real_time_stream_badge': 'Real-Time Stream',
  'order_items_summary': '{count} item(s) • {method} • {city}',
  'product_sales_report_title': 'Itemized Product Sales Report',
  'product_sales_report_subtitle': 'Sold units, cost prices, and net profit per product',
  'total_units_sold_title': 'Total Units Sold',
  'units_count_label': '{count} units',
  'from_x_products': 'from {count} unique products',
  'total_product_sales_title': 'Total Products Revenue',
  'total_cost_subtitle': 'Cost: {cost}',
  'total_product_profit_title': 'Total Products Net Profit',
  'profit_margin_subtitle': 'Profit Margin: {margin}%',
  'search_product_sales_hint': 'Search by title, SKU, or brand...',
  'filter_channel_all': 'All Channels',
  'filter_channel_online': 'Online App Only',
  'filter_channel_pos': 'Branch POS Only',
  'col_product_and_sku': 'Product & SKU',
  'col_units_sold': 'Units Sold',
  'col_sales_revenue': 'Sales Revenue',
  'col_sales_cost': 'Cost (COGS)',
  'col_sales_profit': 'Net Profit',
  'col_sales_margin': 'Profit Margin',
  'col_sales_actions': 'Orders',
  'view_orders_btn': 'View Orders',
  'no_product_sales_found': 'No product sales found in selected range',
  'try_changing_date_or_filters': 'Try changing the date filter or clearing search filters',
  'total_sold_label': 'Total Sold',
  'total_sales_label': 'Total Sales',
  'net_profit_label': 'Net Profit',
  'orders_count_badge': 'Orders ({count})',
  'online_badge_with_count': '📱 Online: {count}',
  'pos_badge_with_count': '🏪 POS: {count}',
  'item_qty_count': 'Qty: {qty} pcs',
  'orders_and_invoices_for': 'Orders & Invoices: {title}',
  'total_matching_orders': 'Total {count} order(s) / invoice(s)',
  'no_orders_for_product': 'No orders found for this product',
  'order_num_badge': 'Order #{id}',
  'pos_invoice_badge': 'POS Invoice #{id}',
  'summary_report_badge': 'KPIs & Trends',
  'orders_manifest_badge': '{count} Orders',
  'inventory_report_badge': '{count} Products',
  'master_report_badge': 'All Datasets',
  'executive_summary_file': 'Executive Summary',
  'orders_manifest_file': 'Orders & Sales Manifest',
  'inventory_status_file': 'Inventory & Low Stock Status',
  'master_full_file': 'Master Report',

  // Products & Variation Matrix
  'products_subtitle':
      'Manage e-liquids, vape devices, mods, pods, and coils with full variation matrix',
  'add_product': 'Add New Product',
  'edit_product': 'Edit Product',
  'delete_product': 'Delete Product',
  'delete_product_confirm':
      'Are you sure you want to delete this product from catalog and database?',
  'product_title': 'Product / Item',
  'product_type_col': 'Type',
  'product_brand_col': 'Brand',
  'product_price_col': 'Price (EGP)',
  'price_range': 'Price Range',
  'min_max_price': 'Min - Max Price',
  'product_stock_col': 'Stock',
  'product_vars_col': 'Variations',
  'product_actions_col': 'Actions',
  'view_product_details': 'View Product Details',
  'no_products_found': 'No products found in catalog yet',
  'flavors_label': 'Flavors:',
  'simple_product': 'Simple',
  'skus_count': '{count} SKUs',
  'product_desc': 'Description',
  'category': 'Category',
  'brand': 'Brand',
  'base_price': 'Base Price (EGP)',
  'sale_price': 'Sale Price (EGP)',
  'total_stock': 'Total Stock',
  'sku': 'SKU',
  'is_featured': 'Featured Product',
  'product_type': 'Product Type',
  'simple': 'Simple',
  'variable': 'Variable (Vape Matrix)',
  'liquid_matrix': 'E-Liquid Matrix (Nicotine & Size)',
  'hardware_matrix': 'Hardware Matrix (Color & Resistance)',
  'nicotine_levels': 'Nicotine Strengths',
  'bottle_sizes': 'Bottle Sizes',
  'device_colors': 'Device Colors',
  'coil_resistances': 'Coil Resistances',
  'generate_matrix': 'Generate Variations Matrix',
  'stock_status': 'Stock Status',
  'in_stock': 'In Stock',
  'low_stock': 'Low Stock',
  'out_of_stock': 'Out of Stock',
  'actions': 'Actions',
  'delete': 'Delete',
  'edit': 'Edit',
  'save': 'Save Changes',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'confirm_delete': 'Are you sure you want to delete this item?',
  'type_liquid': 'E-Liquids (SaltNic / Freebase)',
  'type_liquid_short': 'Liquids',
  'type_liquid_desc':
      'E-liquids with custom flavors, MTL/DL styles & nicotine sizes',
  'type_device': 'Devices & Vape Mods',
  'type_device_short': 'Devices',
  'type_device_desc': 'Pod kits, box mods with battery & color finishes',
  'type_pod': 'Pods & Cartridges',
  'type_pod_short': 'Pods',
  'type_pod_desc': 'Replacement pods with capacity, resistance & compatibility',
  'type_coil': 'Replacement Coils',
  'type_coil_short': 'Coils',
  'type_coil_desc':
      'Mesh & regular coils with resistance options and wire materials',
  'type_accessory': 'Vape Accessories',
  'type_accessory_short': 'Accessories',
  'type_accessory_desc':
      'Batteries, chargers, cotton, replacement glass & toolkits',
  'step_type': '1. Choose Type',
  'step_specs': '2. Dynamic Specs',
  'step_matrix': '3. Variations Matrix',
  'step_review': '4. Review & Publish',
  'flavor': 'Flavor',
  'add_flavor': 'Add New Flavor',
  'new_flavor_title': 'Add Custom Flavor',
  'vape_style': 'Vaping Style',
  'style_mtl': 'MTL (Mouth-To-Lung)',
  'style_dl': 'DL (Direct-Lung)',
  'style_both': 'Both (MTL & DL)',
  'max_wattage': 'Max Wattage (W)',
  'battery_type': 'Battery System',
  'battery_integrated': 'Built-in Battery',
  'battery_external': 'External Cells (18650 / 21700)',
  'pod_capacity': 'Pod Capacity (ml)',
  'pack_size': 'Pack Size / Pieces',
  'wire_material': 'Wire Material',
  'accessory_sub': 'Accessory Type',

  // Categories & Brands
  'vape_categories_title': 'Vape Categories',
  'categories_subtitle': 'Manage pod systems, salt nic, hardware & accessories',
  'no_categories_found': 'No categories found. Create your first category.',
  'add_category': 'Add Category',
  'edit_category': 'Edit Category',
  'category_name': 'Category Name',
  'products_count': 'Products',
  'vape_brands_title': 'Official Vape Brands',
  'brands_subtitle': 'Hardware manufacturers & e-liquid brands',
  'no_brands_found': 'No brands found. Create your first brand.',
  'add_brand': 'Add Brand',
  'edit_brand': 'Edit Brand',
  'brand_name': 'Brand Name',
  'brand_id_exists': 'Brand already exists with ID ({id})',
  'brand_name_exists': 'Brand name "{name}" already exists!',
  'brand_name_used': 'Brand name "{name}" is already used by another brand!',
  'catalog_items': 'Catalog Items',
  'sort_order': 'Display Order',
  'sort_order_hint':
      'Order in customer app (e.g. 1, 2, 3 - lower numbers appear first)',
  'sort_by': 'Sort by',
  'sort_name': 'Brand Name',
  'sort_products_count': 'Catalog Items',
  'sort_status': 'Status',
  'sort_asc': 'Ascending',
  'sort_desc': 'Descending',
  'playlist_reorder_mode': 'Playlist Reorder (Drag & Drop)',
  'table_mode': 'Table View',
  'drag_to_reorder': 'Catch & drag to reorder brands like a playlist',
  'delete_brand_title': 'Delete Brand',
  'delete_brand_confirm':
      'Are you sure you want to delete brand "{name}"? Products will be unlinked.',
  'brand_logo_url': 'Brand Logo URL',
  'brand_name_hint': 'e.g. Vaporesso, GeekVape, Voopoo',
  'total_registered_brands': 'Total Registered Brands',
  'featured_active_brands': 'Featured / Active Brands',
  'total_linked_products': 'Total Linked Products',
  'brands_unit': 'Brands',
  'featured_unit': 'Active',
  'products_unit': 'Products',
  'required': 'Required',
  'add_brand_subtitle': 'Register a new manufacturer or e-liquid brand',
  'edit_brand_subtitle': 'Update brand name, logo, and featured status',
  'brand_logo_url_hint': 'https://example.com/logo.png',
  'featured_brand_desc':
      'Display prominently in customer app featured sections',
  'error_occurred': 'An unexpected error occurred. Please try again.',

  // Orders Screen
  'orders_title': 'Vape Order Fulfillment & Dispatch',
  'orders_subtitle':
      'Live orders feed with customer address, phone, and variation details',
  'no_orders_found':
      'No orders found. New customer orders will appear here in real-time.',
  'order_id': 'Order ID',
  'order_number': 'Order #{id}',
  'current_status': 'Current Status',
  'customer': 'Customer',
  'customer_delivery_address': 'Customer & Delivery Address',
  'payment': 'Payment Method',
  'status': 'Status',
  'total': 'Total (EGP)',
  'date': 'Date',
  'items_ordered_count': '{count} items',
  'dispatch_action': 'Dispatch',
  'status_all': 'All Orders',
  'status_pending': 'Pending',
  'status_processing': 'Processing',
  'status_shipped': 'Shipped',
  'status_delivered': 'Delivered',
  'status_cancelled': 'Cancelled',
  'update_status': 'Update Order Status',
  'order_details': 'Order Details',
  'shipping_address': 'Shipping Address',
  'ordered_items': 'Ordered Items',
  'ordered_items_label': 'Ordered Items',
  'subtotal': 'Subtotal',
  'shipping_fee': 'Delivery Fee',
  'delivery_fee': 'Delivery Fee',
  'free_delivery_notice': 'Free',
  'discount': 'Discount',
  'discount_applied': 'Promo Discount',
  'tax_fee': 'Tax / VAT',
  'grand_total': 'Grand Total',
  'phone': 'Phone Number',
  'city': 'City',
  'free_shipping_applied': 'Free Shipping (Orders >= 2000 EGP)',
  'copy_order_id': 'Copy Order ID',
  'copy_phone': 'Copy Phone',
  'whatsapp_chat': 'WhatsApp Chat',
  'customer_notes': 'Customer Special Notes',
  'no_customer_notes': 'No special notes provided',
  'item_subtotal': 'Subtotal: {amount}',
  'item_sku': 'SKU: {sku}',
  'item_brand': 'Brand: {brand}',
  'print_invoice': 'Print Invoice',
  'invoice_title': 'Sales Order Invoice',
  'payment_status_label': 'Payment Status',
  'paid': 'Paid',
  'unpaid': 'Unpaid',
  'cash_on_delivery': 'Cash on Delivery',
  'raw_data_inspector': 'Technical Data Payload (Firestore)',
  'order_time': 'Order Placed At',
  'delivery_date_label': 'Delivery Date',
  'tracking_number_label': 'Tracking Number',
  'copied_to_clipboard': 'Copied to clipboard',
  'no_items_in_order': 'No detailed items list found for this order',
  'view_order_details': 'View Order Details',
  'coupon_code_label': 'Promo Code Applied',
  'share_with_courier': 'Share with Courier',
  'share_order': 'Share Order',
  'courier_share_title': 'Share Order with Courier',
  'courier_share_subtitle':
      'Prepare & dispatch order details, address, and Google Maps link',
  'send_via_whatsapp': 'Send via WhatsApp',
  'share_via_whatsapp_contacts': 'Share to WhatsApp (Select Courier)',
  'select_courier_whatsapp': 'Open WhatsApp to pick courier from contacts',
  'share_via_system': 'Share via Other Apps',
  'copy_courier_slip': 'Copy Delivery Slip',

  'open_in_google_maps': 'Open in Google Maps',
  'call_customer': 'Call Customer',
  'courier_phone_hint': 'Courier phone number (optional)...',
  'courier_phone_label': 'Courier Phone',
  'share_slip_copied': 'Delivery slip copied to clipboard',
  'preview_courier_slip': 'Courier Message Preview',
  'maps_link': 'Google Maps Link',
  'amount_to_collect': 'Amount to Collect',
  'open_maps': 'Maps',

  // Banners & Coupons
  'banners_title': 'Hero Promotional Banners',
  'banners_subtitle':
      'Top promotional sliders displayed on EGO Store mobile & web app home',
  'no_banners_found':
      'No promotional banners found. Create your first banner slider.',
  'add_banner': 'Add Banner',
  'preview': 'Preview',
  'delete_banner': 'Delete Banner',
  'remove_banner': 'Remove Banner',
  'delete_banner_title': 'Delete Banner',
  'delete_banner_confirm':
      'Are you sure you want to delete this promotional banner? This action cannot be undone.',
  'delete_banner_confirm_with_title':
      'Are you sure you want to delete the banner "{title}"? This action cannot be undone.',
  'invalid_image_url': 'Invalid image URL',
  'banner_title_hint': 'e.g. Vaporesso XROS 4 Special Deal',
  'banner_title_col': 'Banner Title',
  'target_destination': 'Target Destination',
  'banner_image': 'Banner Image URL',
  'target_screen': 'Target Navigation Route',
  'target_type': 'Destination Type',
  'target_product': 'Product Details',
  'target_sale': 'Sales & Offers',
  'target_new_arrivals': 'New Products',
  'target_popular': 'Popular Products',
  'target_custom_screen': 'Custom / General Screen',
  'select_product': 'Select Product to Sponsor',
  'select_product_hint': 'Choose a product from catalog...',
  'selected_product': 'Sponsored Product',
  'change_product': 'Change Product',
  'no_product_selected': 'Please select a product to link with this banner',
  'product_details_dest': 'Product Details Screen',
  'fill_from_product': 'Autofill from Product',
  'coupons_title': 'Vape Promo Codes & Flash Sale Coupons',
  'coupons_subtitle':
      'Configure percentage discounts, cart thresholds, and expiration dates',
  'no_coupons_found':
      'No discount coupons found. Create your first promo code.',
  'add_coupon': 'Create Promo Code',
  'edit_coupon': 'Edit Promo Code',
  'edit_cupon': 'Edit Promo Code',
  'delete_coupon': 'Delete Promo Code',
  'delete_cupon': 'Delete Promo Code',
  'delete_coupon_title': 'Delete Promo Code',
  'delete_coupon_confirm':
      'Are you sure you want to delete this promo code? This action cannot be undone.',
  'delete_coupon_confirm_with_code':
      'Are you sure you want to delete promo code "{code}"? This action cannot be undone.',
  'coupon_code': 'Promo Code',
  'coupon_preview': 'Voucher Live Preview',
  'generate_code': 'Generate Code',
  'generate_random_code': 'Generate Random Code',
  'preset_discounts': 'Quick Discount Presets',
  'active_status_desc': 'Active — customers can apply this code at checkout',
  'inactive_status_desc':
      'Inactive — this coupon is paused and cannot be applied',
  'discount_percentage': 'Discount',
  'min_cart_requirement': 'Min Purchase Amount (EGP)',
  'min_purchase_amount': 'Minimum Purchase Amount to Use Promo',
  'min_purchase_hint': 'e.g. 500',
  'min_purchase_help':
      'How much money the customer must spend in total to use this promo (0 or leave empty for no minimum)',
  'redemptions': 'Redemptions',
  'start_date': 'Start Date',
  'end_date': 'End Date',
  'expiry_date': 'Expiry Date',
  'expired': 'Expired',
  'scheduled': 'Scheduled',
  'invalid_date_range': 'End date must be after start date',
  'no_minimum': 'No Minimum',
  'off_discount': '{percent}% OFF',
  'valid_duration': 'Valid for {days} days',
  'duration_days': '{days} Days',
  'one_year': '1 Year',
  'no_min_threshold': 'No minimum order requirement',
  'min_order_threshold': 'Min order: {amount} EGP',
  'save_coupon': 'Save Promo Code',
  'used_times_count': 'Used {count} times',

  // Notifications & Broadcasts
  'broadcasts_title': 'FCM Push Notification Broadcasts',
  'broadcasts_subtitle':
      'Send direct announcements, promotional deals & stock alerts to customer devices',
  'no_broadcasts_found':
      'No push notifications sent yet. Create your first broadcast announcement.',
  'compose_broadcast': 'Compose Broadcast',
  'broadcast_title': 'Notification Title',
  'broadcast_body': 'Message Body',
  'target_audience': 'Target Audience',
  'devices_reached': 'Devices Reached',
  'all_users': 'All App Users',
  'topic_salt_nic': 'SaltNic Vapers',
  'topic_hardware': 'Hardware Deals Seekers',
  'send_broadcast': 'Send Broadcast Now',
  'sent_history': 'Broadcast History',
  'sent_at': 'Sent Date',

  // Customers Screen
  'customers_title': 'EGO Customer CRM & Profiles',
  'customers_subtitle':
      'View customer purchase history, addresses, lifetime value & roles',
  'no_customers_found': 'No registered customers found in database.',
  'customer_name': 'Customer Name',
  'email': 'Email',
  'city_col': 'City',
  'total_orders': 'Total Orders',
  'lifetime_spend': 'Lifetime Spend (EGP)',
  'customer_role': 'Role',
  'view_profile': 'View Profile',

  // Settings
  'settings_title': 'Store Settings & Configuration',
  'settings_subtitle':
      'Manage official contact channels, delivery rates, product badges, and store policies',
  'contact_support_title': 'Store Official Contact Info',
  'contact_support_subtitle':
      'Official customer care channels and store headquarters',
  'store_phone': 'Customer Care Phone',
  'store_phone_hint': '+20 100 123 4567',
  'whatsapp_number': 'Official WhatsApp Line',
  'whatsapp_number_hint': '+20 100 123 4567',
  'support_email': 'Support Email',
  'support_email_hint': 'support@egostore.com',
  'store_address': 'Store Headquarters Address',
  'store_address_hint': 'Nasr City, Cairo, Egypt',
  'shipping_delivery_title': 'Shipping & Delivery Rates',
  'shipping_delivery_subtitle':
      'Control flat delivery fee, free shipping threshold, and fulfillment speed',
  'flat_delivery_fee': 'Flat Delivery Fee (EGP)',
  'flat_delivery_fee_hint': '60',
  'flat_delivery_fee_help':
      'Base shipping cost charged when free delivery is not qualified.',
  'free_shipping_threshold': 'Free Shipping Minimum Order (EGP)',
  'free_shipping_threshold_hint': '2000',
  'free_shipping_threshold_help':
      'Orders at or above this amount automatically receive free shipping (0 EGP).',
  'estimated_delivery_time': 'Estimated Delivery Window',
  'estimated_delivery_time_hint': 'e.g. 24 - 48 Hours',
  'estimated_delivery_time_help':
      'Average transit time communicated to customers at checkout.',
  'regulatory_settings': 'Regulatory & Health Compliance',
  'regulatory_subtitle':
      'Age restriction policy and statutory nicotine warnings',
  'age_verification': 'Mandatory 18+ Age Gate Policy',
  'age_verification_desc':
      'Enforce age verification gate for customers before browsing catalog',
  'nicotine_warning_banner': 'Statutory Nicotine Health Warning Header',
  'nicotine_warning_banner_desc':
      'Display statutory health disclaimer on product detail pages',
  'badges_card_desc':
      'Configure and customize dynamic badges such as SALE, NEW, and EXCLUSIVE to highlight products in the app.',
  'firestore_sync_title': 'Firestore Data Persistence',
  'firestore_sync_desc':
      'Synchronized with collection: /Settings/store_settings',
  'check_sync_status': 'Verify Firestore Sync',
  'firestore_sync_active': 'Firestore settings are active and synchronized.',
  'save_settings': 'Save Store Settings',
  'reload_settings': 'Reload Settings',
  'required_field': 'This field is required',

  // Badges Management
  'badges': 'Product Badges',
  'manage_badges': 'Manage Badges',
  'badges_subtitle':
      'Manage promotional labels, tags, and badges displayed on products',
  'add_badge': 'Add Badge',
  'edit_badge': 'Edit Badge',
  'delete_badge': 'Delete Badge',
  'delete_badge_confirm': 'Are you sure you want to delete this badge?',
  'badge_preview': 'Preview',
  'badge_name_en': 'English Label',
  'badge_name_ar': 'Arabic Label',
  'badge_color': 'Color',
  'badge_status': 'Active Status',
  'badge_active': 'Active',
  'badge_inactive': 'Inactive',
  'badge_status_app_hint':
      'Only active badges can be assigned to products and shown in the user app.',
  'no_badges_found': 'No badges configured yet',
  'no_badges_desc':
      'Add promotional badges like SALE or NEW to highlight products in the app.',
  'choose_preset_or_custom':
      'Choose from common presets or type a custom badge name:',
  'save_badge_changes': 'Save Changes',
  'badge_name_required': 'Please enter a badge name',

  // Feedback Alerts
  'success': 'Success',
  'error': 'Error',
  'warning': 'Warning',
  'item_created': 'Item created successfully!',
  'item_updated': 'Item updated successfully!',
  'item_deleted': 'Item deleted successfully!',
  'order_status_updated': 'Order status updated and notification sent!',
  'broadcast_sent': 'Push notification broadcasted to devices!',
  'settings_saved': 'Store settings saved successfully!',

  // Additional UI & Navigation Keys
  'close': 'Close',
  'remove': 'Remove',
  'previous_page': 'Previous Page',
  'next_page': 'Next Page',
  'edit_banner': 'Edit Banner',
  'target_product_short': 'Target Product',
  'vape_admin_suite': 'Vape Admin Suite',
  'version_pro_suite': 'v1.2.0 • Pro Suite',
  'route_shop': 'Shop',
  'route_categories': 'Categories',
  'route_brands': 'Brands',
  'route_cart': 'Cart',
  'route_profile': 'Profile',
  'route_deals': 'Deals & Offers',
  'route_new_arrivals': 'New Arrivals',
  'route_popular': 'Popular Items',
  'route_custom': 'Custom Link',
  'flavors_available_label': 'Flavors:',
  'member_since': 'Member Since {date}',
  'notification_body_col': 'Notification Body',
  'product_description_col': 'Description',
  'stock': 'Stock',
  'store_settings_saved': 'Store settings saved successfully!',
  'technical_specs': 'Technical Specs',
  'variation_matrix': 'Variation Matrix',
  'orders_selected': '{count} orders selected',
  'bulk_status_update': 'Update Status',
  'bulk_share_courier': 'Courier Manifest',
  'clear_selection': 'Clear Selection',
  'bulk_update_success': 'Successfully updated {count} orders',
  'select_bulk_status_prompt': 'Select new status for selected orders:',
  'bulk_courier_copied':
      'Courier manifest for {count} orders copied to clipboard',

  // Store Branches & Locations
  'store_branches': 'Store Branches & Locations',
  'store_branches_subtitle':
      'Manage branch addresses, contact numbers, and Google Maps links with live GPS capture',
  'add_branch': 'Add New Branch',
  'edit_branch': 'Edit Branch',
  'delete_branch': 'Delete Branch',
  'delete_branch_confirm': 'Are you sure you want to delete this branch?',
  'branch_name': 'Branch Name',
  'branch_name_hint': 'e.g. Maadi Branch / Main Store',
  'branch_phone': 'Branch Phone Number',
  'branch_phone_hint': 'e.g. 01012345678',
  'branch_address': 'Detailed Branch Address',
  'branch_address_hint': 'e.g. El-Nasr St, Maadi, Cairo',
  'maps_link_hint': 'https://maps.google.com/?q=lat,lng',
  'get_live_location': 'Get Current Live Location (GPS)',
  'locating': 'Acquiring GPS location...',
  'location_acquired': 'Location acquired successfully!',
  'preview_map': 'Preview on Map',
  'is_primary_branch': 'Set as Primary Branch',
  'no_branches_added': 'No branches added yet',
  'no_branches_desc':
      'Add store branches so customers can view your physical locations, call, and get Google Maps directions.',
  'primary_branch_badge': 'Main Branch',

  // Egyptian Governorates & Delivery Pricing
  'governorates_delivery_title': 'Egypt Governorates & Delivery Pricing',
  'governorates_delivery_subtitle':
      'Enable supported shipping zones and customize delivery fees per Egyptian governorate',
  'search_governorates_hint': 'Search governorate by Arabic or English name...',
  'active_delivery_zones': '{active} of {total} governorates enabled',
  'enable_all_governorates': 'Enable All',
  'disable_all_governorates': 'Disable All',
  'set_bulk_fee': 'Set Bulk Price',
  'reset_governorates_default': 'Reset Defaults',
  'bulk_fee_title': 'Set Uniform Delivery Fee',
  'bulk_fee_desc':
      'Enter the delivery fee to apply to all active governorates:',
  'apply': 'Apply',
  'delivery_available': 'Delivery Available',
  'delivery_unavailable': 'Disabled',
  'shipping_fee_egp': 'Delivery Fee',
  'egp_currency': 'EGP',
  'no_governorates_match': 'No governorates match your search',
  // Roles & Permissions System
  'super_admin': 'Super Admin (Owner)',
  'super_admin_desc':
      'Full unrestricted access across all modules, financials, settings, and team management',
  'admin_role': 'Admin (Manager)',
  'admin_role_desc':
      'Manage products, brands, banners, coupons, and orders without sensitive store settings',
  'staff_role': 'Store Staff (Guest)',
  'staff_role_desc': 'Restricted access: Orders & shipping fulfillment only',
  'roles_permissions': 'Roles & Permissions',
  'roles_management_subtitle':
      'Configure role permissions, access levels, and team member assignments',
  'permissions_matrix': 'Permissions Matrix',
  'team_members_roles': 'Team Members & Staff',
  'module_permission': 'Module / Permission',
  'super_admin_full_access':
      'Super Admin has permanent full access to all system modules',
  'current_active_role': 'Active Role',
  'switch_role': 'Switch Active Role',
  'reset_defaults': 'Reset Defaults',
  'save_changes': 'Save Changes',
  'role_assigned_success': 'Permissions Updated Successfully',
  'permissions_saved_desc':
      'Role permissions saved to cloud database and enforced immediately',
  'permissions_reset_desc': 'Permissions restored to default configuration',
  'search_staff_hint': 'Search team members by name, email, or phone...',
  'all_roles': 'All Roles',
  'no_staff_found': 'No team members matching your search',
  'permission_dashboard': 'Financial Analytics Dashboard',
  'pos_cashier': 'Cashier',
  'permission_pos': 'Cashier & In-Store Sales',
  'permission_products': 'Products & Inventory Catalog',
  'permission_brands': 'Brands & Categories',
  'permission_orders': 'Orders & Fulfillment',
  'permission_banners': 'Promotional Banners',
  'permission_coupons': 'Discount Coupons',
  'permission_customers': 'Customer Directory',
  'permission_notifications': 'Push Notifications Broadcast',
  'permission_settings': 'Store Settings & Shipping',
  'permission_roles': 'Roles & Permissions Management',
  'permission_view_cost_price': 'View Cost & Purchase Price in POS & Products',
  'access_denied_title': 'Access Restricted',
  'access_denied_desc':
      'Your current role does not have permission to access this module.',

  'security_passcodes_tab': 'Security Passcodes',
  'security_passcodes_title': 'Role Security Passcodes',
  'security_passcodes_subtitle':
      'Configure PINs/passwords required to elevate from Store Staff to Admin or Super Admin',
  'super_admin_passcode_label': 'Super Admin Master PIN',
  'super_admin_passcode_hint': 'e.g. 999999',
  'super_admin_passcode_desc':
      'Grants full unrestricted access to financial dashboard, settings, and team management',
  'admin_passcode_label': 'Admin Manager PIN',
  'admin_passcode_hint': 'e.g. 123456',
  'admin_passcode_desc':
      'Allows managing catalog, products, orders, and promotions without sensitive store settings',
  'default_to_staff_label': 'Default to Store Staff on launch',
  'default_to_staff_desc':
      'Ensures the admin panel opens in restricted Staff mode (orders only) until elevated with a PIN',
  'enter_passcode_title': 'Enter Security Passcode',
  'enter_passcode_prompt': 'Enter passcode to elevate to {role}:',
  'passcode_hint': 'Security Passcode...',
  'invalid_passcode': 'Invalid passcode! Access denied.',
  'role_elevated_success': 'Unlocked and elevated to {role} successfully 🔓',
  'lock_to_staff': 'Lock Session (Store Staff)',
  'session_locked': 'Session locked to Store Staff mode (Orders only) 🔒',
  'unlock_elevate': 'Unlock & Elevate',
  'elevate_role': 'Elevate Role',
  'passcodes_saved_success':
      'Security passcodes updated successfully in cloud database',
  'inventory_stock_settings': 'Inventory & Stock Alerts',
  'inventory_stock_settings_subtitle':
      'Configure low stock alert thresholds and urgent replenishment notifications',
  'low_stock_threshold_label': 'Low Stock Alert Threshold (Units)',
  'low_stock_threshold_hint': 'e.g. 10',
  'low_stock_threshold_help':
      'Products with total stock at or below this number will trigger urgent warnings in Dashboard.',
  'quick_restock': 'Quick Restock',
  'quick_restock_desc': 'Add units directly to current inventory',
  'add_units': 'Add Units',
  'enter_quantity_to_add': 'Quantity to add to inventory',
  'stock_updated_success': 'Product stock updated successfully!',
  'open_full_editor': 'Open Full Product Editor',
  'healthy_stock_desc':
      'All inventory levels are healthy (Stock > {threshold} units)',
  'current_stock_is': 'Current Stock: {count} units',
  'warning_threshold_is': 'Warning Threshold: {count} units',
  'export_report_title': 'Export Business Reports',
  'export_report_desc':
      'Select a data report to export and download as CSV for Excel analysis',
  'export_executive_summary': 'Executive & Financial Overview',
  'export_executive_summary_desc':
      'KPIs, weekly revenue trend, and brand market distribution',
  'export_orders_report': 'Orders & Sales Manifest',
  'export_orders_report_desc':
      'Full log of orders, customer details, cities, and payment totals',
  'export_inventory_report': 'Inventory & Stock Health Report',
  'export_inventory_report_desc':
      'Stock quantities per product, category, pricing, and alert status',
  'export_master_report': 'All-in-One Master Report',
  'export_master_report_desc':
      'Combined dataset including financials, orders, and inventory',
  'export_download_success': 'Report "{name}" downloaded successfully!',
  'download_csv': 'Download CSV',

  // Stock Movements & Restock Engine
  'stock_movements_title': 'Stock Movements & Audit Log',
  'stock_movements_subtitle':
      'Complete audit trail of all restocks, sales, damages, and inventory adjustments',
  'stock_audit_log': 'Stock Audit Log',
  'quick_restock_title': 'Smart Stock Replenishment',
  'batch_restock': 'Batch Restock',
  'single_restock': 'Single Restock',
  'supplier_name_label': 'Supplier / Vendor Name',
  'invoice_number_label': 'Invoice / Reference #',
  'batch_cost_price': 'Batch Cost Price (EGP)',
  'total_inflow_capital': 'Total Restock Capital',
  'total_restocked_units': 'Total Restocked Units',
  'total_outflow_units': 'Total Outflow Units',

  // Suppliers & Purchase Invoices Hub
  'suppliers': 'Suppliers',
  'permission_suppliers': 'Suppliers & Invoices Hub',
  'suppliers_title': 'Suppliers & Purchase Invoices Hub',
  'suppliers_subtitle':
      'Vendor directory, purchase invoices, accounts payable, and payment vouchers',
  'add_supplier': 'Add New Supplier',
  'edit_supplier': 'Edit Supplier',
  'create_invoice': 'Create Purchase Invoice',
  'record_payment': 'Record Payment Voucher',
  'statement_of_account': 'Supplier Statement of Account',
  'balance_due': 'Balance Due',
  'total_purchases': 'Total Purchases',
  'total_paid': 'Total Paid',
  'payment_terms': 'Payment Terms',
  'supplier_name': 'Supplier Name',
  'contact_person': 'Contact Person',
  'phone_whatsapp': 'Phone / WhatsApp',
  'invoice_number': 'Invoice #',
  'invoice_date': 'Invoice Date',
  'due_date': 'Due Date',
  'auto_stock_inflow': 'Auto-replenish stock and catalog quantities',
  'status_paid': 'Paid in Full',
  'status_partial': 'Partially Paid',
  'status_unpaid': 'Unpaid',
  'status_overdue': 'Overdue',

  // POS & Cashier Register
  'pos_register': 'Cashier',
  'pos_register_title': 'Cashier',
  'pos_register_subtitle': 'Fast in-store sales & live barcode scanner',
  'shortcut_f2_scan': 'Scan Barcode',
  'shortcut_f4_pay': 'Complete & Pay',
  'shortcut_f8_returns': 'Sales Returns',
  'shortcut_f9_clear': 'Clear Cart',
  'current_bill_cart': 'Current Sale Cart',
  'items_pieces_count': '{count} pcs',
  'clear_cart': 'Clear Cart',
  'empty_cart_title': 'Cart is empty',
  'empty_cart_desc': 'Scan product barcode or tap from catalog to start sale',
  'barcode_search_hint': 'Scan or enter barcode / product name (F2)...',
  'walk_in_customer': 'Walk-in Customer',
  'customer_name_optional': 'Customer Name (Optional)',
  'customer_phone_optional': 'Customer Phone (Optional)',
  'payment_cash': 'Cash',
  'payment_card': 'Card / POS',
  'payment_instapay': 'InstaPay / E-Wallet',
  'payment_split': 'Split Payment',
  'paid_amount_label': 'Paid Amount (EGP)',
  'change_amount_label': 'Change to Customer',
  'complete_sale_btn': 'Complete Sale & Print Receipt',
  'sale_completed_success': 'POS Sale recorded successfully',
  'pos_returns_title': 'POS Sales Returns & Refunds',
  'pos_returns_subtitle':
      'Look up invoice, select items to return and refund cash to customer',
  'lookup_invoice_hint': 'Enter receipt # or scan barcode...',
  'search_invoice_btn': 'Search Invoice',
  'return_items_selected': 'Return Selected Items',
  'total_refund_due': 'Total Refund Due',
  'process_refund_btn': 'Process Refund & Restock',
  'refund_completed_success':
      'Refund processed and stock returned successfully',
  'print_thermal_receipt_label': 'Thermal Receipt (80mm)',
  'print_a4_invoice_label': 'A4 Invoice',

  // Barcode Label Stickers Printing
  'print_barcode_stickers_title': 'Print Product Barcode Labels',
  'print_barcode_stickers_subtitle':
      'Generate crisp Code-128 vector barcodes for thermal label printers',
  'label_paper_size': 'Label Size / Roll Type:',
  'compact_roll_38x25': 'Compact Thermal Roll (38 x 25 mm)',
  'standard_roll_50x30': 'Standard Thermal Roll (50 x 30 mm)',
  'large_roll_58x40': 'Large Thermal Roll (58 x 40 mm)',
  'a4_sheet_grid': 'A4 Sheet (24 Stickers - 3x8 Grid)',
  'number_of_copies': 'Number of Copies:',
  'variations_and_quantities': 'Variations & Quantities:',
  'select_all': 'Select All',
  'by_stock_level': 'By Stock Level',
  'live_sticker_preview': 'Live Sticker Preview:',
  'barcode_scanner_compatible_note':
      'Barcode is 100% compatible with 1D/2D POS handheld scanners & cameras.',
  'print_stickers_btn': 'Print ({count} Labels)',
  'print_job_dispatched': 'Print job sent for {count} labels on {size}',
  'please_select_at_least_one_item':
      'Please select at least one item with copies > 0',

  // Order Returns & Sharing
  'order_return_title': 'Process Order Return / Refund',
  'order_return_subtitle':
      'Select items, specify return reason, and choose whether to restock inventory',
  'return_reason_label': 'Return Reason:',
  'reason_defective': 'Defective / Damaged Product',
  'reason_wrong_item': 'Item not matching order',
  'reason_customer_changed_mind': 'Customer changed mind',
  'reason_delivery_error': 'Shipping / Delivery error',
  'reason_unwanted': 'Unwanted / Incompatible item',
  'reason_other': 'Other (specify in notes)',
  'return_notes_hint': 'Additional return notes or courier details...',
  'restock_to_inventory_label': 'Automatically return items to catalog stock',
  'refund_amount_label': 'Refund Amount to Customer (EGP):',
  'confirm_return_submission': 'Confirm Return & Refund',
  'order_return_recorded_success': 'Order return processed successfully',
  'share_order_title': 'Share Order with Courier',
  'share_order_subtitle':
      'Send order slip to courier or customer via WhatsApp or copy text',
  'copy_slip_text': 'Copy Courier Slip',
  'open_whatsapp': 'Send via WhatsApp',

  // Suppliers & Ledger
  'tab_suppliers': 'Suppliers Directory',
  'tab_invoices': 'Purchase Invoices',
  'tab_payments': 'Payment Vouchers',
  'supplier_rating_label': 'Supplier Rating',
  'supplier_supplied_categories': 'Supplied Categories (comma separated)',
  'supplier_tax_number': 'Tax / Registration #',
  'supplier_address': 'Address / Headquarters',
  'supplier_contact_name': 'Contact Person Name',
  'supplier_saved_success': 'Supplier details saved successfully',
  'delete_supplier_confirm': 'Are you sure you want to delete this supplier?',
  'item_deleted_success': 'Deleted successfully',
  'add_purchase_item_btn': 'Add Item to Invoice',
  'select_product_prompt': 'Select Product',
  'unit_cost_price': 'Unit Cost Price (EGP)',
  'invoice_total_amount': 'Invoice Total Amount',
  'payment_voucher_record': 'Record Payment Voucher',
  'amount_paid_egp': 'Amount Paid (EGP)',
  'payment_source': 'Payment Source / Account',
  'payment_reference_hint': 'Receipt # / Bank transfer ref...',
  'voucher_recorded_success': 'Payment voucher recorded successfully',
  'statement_ledger_title': 'Statement of Account Ledger',
  'financial_transactions_history': 'Financial Transactions & Invoices History',

  // Additional Detailed POS & Scanner Keys
  'pos_barcode_search_bar_hint':
      'Scan barcode with hardware scanner, or search product / SKU...',
  'enter_key_submit': 'Enter (Submit)',
  'barcode_scanned_title': 'Barcode Scan',
  'barcode_scan_alert': 'Scan Alert',
  'pos_sale_error': 'POS Sale Error',
  'checkout_sale_title': 'Complete POS Sale & Payment',
  'items_count_total_meta': 'Items: {count} • Total: {total}',
  'payment_method_label': 'Payment Method:',
  'payment_cash_tab': 'Cash',
  'payment_card_tab': 'Card / Visa',
  'payment_instapay_tab': 'InstaPay / E-Wallet',
  'cash_change_calculator': 'Cash & Change Calculator',
  'exact_amount': 'Exact Amount',
  'cash_received_from_customer': 'Cash Received from Customer (EGP)',
  'remaining_amount_to_pay': 'Remaining to Collect:',
  'change_to_customer': 'Change to Customer:',
  'auto_print_receipt_after_sale':
      'Automatically print cashier receipt upon completion',
  'processing_sale': 'Processing sale...',
  'pos_branch_returns_title': 'Branch Sales Returns & Refund (POS)',
  'pos_branch_returns_desc':
      'Return invoice items, restock inventory, and refund cash to customer',
  'scan_or_type_invoice_hint':
      'Scan invoice barcode or enter number (e.g. POS-12345)...',
  'invoice_not_found_err':
      'No invoice found with number: {query}. Verify number or scan barcode.',
  'search_error_prefix': 'Search error: {error}',
  'invoice_title_num': 'Invoice #{id}',
  'invoice_date_prefix': 'Date: {date} • Customer: {customer}',
  'original_total': 'Original Total: {amount}',
  'select_items_quantities_to_return': 'Select items and quantities to return:',
  'item_price_and_purchased_qty': 'Price: {price} • Purchased: {qty}',
  'refund_payment_method': 'Refund Method:',
  'refund_cash': 'Cash Refund',
  'refund_card': 'Card / Bank Refund',
  'refund_store_credit': 'Store Credit',
  'restock_items_to_inventory': 'Restock returned items',
  'print_thermal_return_receipt': 'Print thermal return receipt',
  'refund_amount_summary': 'Refund Amount: {amount}',
  'confirm_return_and_print': 'Confirm Return & Print Receipt',
  'pos_return_initial_prompt':
      'Scan invoice barcode or enter number to start return',
  'pos_return_success_title': 'Return Processed Successfully',
  'pos_return_success_msg':
      'Returned {count} items for {amount} and restocked inventory!',
  'pos_return_failed_title': 'Failed to Process Return',
  'select_at_least_one_item_return':
      'Please select at least one item to return',
  'available_stock_count': 'Available in Stock: {count}',
  'max_quantity': 'Max Qty',
  'add_discount': 'Add Discount',
  'item_discount_badge': 'Disc: {amount} EGP',
  'item_discount_title': 'Item Discount',
  'item_discount_input_label': 'Discount per Unit (EGP)',
  'apply_discount': 'Apply Discount',
  'items_subtotal': 'Items Subtotal:',
  'total_discount_label': 'Total Discount:',
  'net_grand_total': 'Net Grand Total:',
  'complete_sale_pay_amount': 'Complete Sale & Pay ({amount})',
  'confirm_clear_cart_title': 'Clear Sale Cart',
  'confirm_clear_cart_msg':
      'Are you sure you want to clear all items in the active cart?',
  'clear': 'Clear',
  'available_options_count': '{count} options available',
  'search_variations_hint': 'Search options (flavor, nicotine, color, SKU)...',
  'all_variations_count': 'All ({count})',
  'filtered_of_total_options': '{filtered} of {total} options',
  'no_matching_variations': 'No options matching your search',
  'show_all_variations': 'Show All Options',
  'no_matching_products': 'No matching products found',
  'no_matching_products_desc':
      'Make sure the spelling is correct or try selecting a different category.',
  'matching_vars_count': 'Matches {count} of {total}',
  'options_count_badge': '{count} options',

  // Barcode Printing & Order Share
  'total_requested_labels': 'Total Requested: {count} labels',
  'print_labels_count_btn': 'Print ({count} Labels)',
  'stock_and_price_label': 'Stock: {stock} • Price: {price}',
  'store_brand_tag': 'EGO VAPE STORE',
  'process_order_return_title': 'Process Return for Order #{id}',
  'order_return_customer_meta': 'Customer: {name} • Order Total: {amount}',
  'unit_price_and_shipped_qty': 'Unit Price: {price} • Shipped: {qty}',
  'unselect_all': 'Unselect All',
  'return_reason_and_notes': 'Return reason and notes:',
  'return_notes_detail_hint':
      'Additional details about condition or customer feedback...',
  'restock_title': 'Restock to Inventory',
  'restock_desc': 'Automatically add units back to product stock',
  'selected_items_total': 'Selected Items Total: {amount}',
  'full_return_type': 'Operation: Full Order Return',
  'partial_return_type': 'Operation: Partial Return',
  'whatsapp_copied_slip_msg':
      'WhatsApp opened and order details copied to clipboard',
  'slip_copied_to_clipboard_msg':
      'Order slip copied to clipboard (paste directly into WhatsApp)',

  // Suppliers & Hub Keys
  'suppliers_inflow_hub': 'Suppliers & Inflow Hub',
  'suppliers_inflow_desc':
      'Vendor directory, purchase invoices, payment vouchers, and accounts payable',
  'btn_new_supplier': '+ New Supplier',
  'btn_new_invoice': '+ New Invoice',
  'btn_pay_vendor': 'Pay Vendor',
  'kpi_active_vendors': 'Active Vendors',
  'kpi_authorized_suppliers': 'Authorized suppliers',
  'kpi_purchases_volume': 'Purchases Volume',
  'kpi_invoices_logged': '{count} invoices logged',
  'kpi_total_paid_out': 'Total Paid Out',
  'kpi_payment_vouchers': '{count} payment vouchers',
  'kpi_outstanding_payables': 'Outstanding Payables',
  'kpi_pending_invoices': '{count} pending invoices',
  'tab_suppliers_dir_count': 'Suppliers Directory ({count})',
  'tab_invoices_count': 'Purchase Invoices ({count})',
  'tab_payments_count': 'Payments Ledger ({count})',
  'suppliers_table_title': 'Suppliers & Vendors Directory',
  'suppliers_table_subtitle': 'View and manage vendor contacts and balance due',
  'suppliers_search_hint': 'Search supplier name, contact, phone...',
  'no_suppliers_found': 'No suppliers found',
  'col_supplier_name': 'Supplier / Company',
  'col_contact_person': 'Contact Person',
  'col_phone': 'Phone',
  'col_payment_terms': 'Payment Terms',
  'col_purchases': 'Purchases',
  'col_balance_due': 'Balance Due (Credit)',
  'col_rating': 'Rating',
  'col_status': 'Status',
  'status_active': 'Active',
  'status_inactive': 'Inactive',
  'tooltip_statement': 'Statement of Account',
  'tooltip_print_statement': 'Print Statement',
  'confirm_delete_supplier_title': 'Confirm Delete Supplier',
  'confirm_delete_supplier_msg':
      'Are you sure you want to delete supplier "{name}"?',
  'invoices_table_title': 'Purchase Invoices & Inflow Orders',
  'invoices_table_subtitle':
      'Track procurement shipments, costs, and payment dues',
  'invoices_search_hint': 'Search invoice #, supplier, items...',
  'filter_all': 'All',
  'filter_unpaid': 'Unpaid',
  'filter_partial': 'Partial',
  'filter_paid': 'Paid',
  'no_invoices_found': 'No purchase invoices found',
  'col_invoice_number': 'Invoice #',
  'col_date': 'Date',
  'col_items_count': 'Items Count',
  'col_total': 'Total (EGP)',
  'col_paid': 'Paid',
  'col_remaining': 'Remaining',
  'col_payment_status': 'Payment Status',
  'tooltip_view_details': 'View Details',
  'tooltip_print_invoice': 'Print Invoice',
  'confirm_delete_invoice_title': 'Confirm Delete Invoice',
  'confirm_delete_invoice_msg':
      'Are you sure you want to delete purchase invoice "{number}"?',
  'payments_table_title': 'Supplier Payments & Payout Ledger',
  'payments_table_subtitle':
      'Documented payment vouchers, bank transfers, and cash receipts',
  'payments_search_hint': 'Search supplier, transaction ref...',
  'no_payments_found': 'No payment vouchers recorded',
  'col_payment_date': 'Payment Date',
  'col_linked_invoice': 'Linked Invoice',
  'col_payment_method': 'Payment Method',
  'col_ref_num': 'Ref / Tx #',
  'col_amount_paid': 'Amount Paid',
  'general_account_payout': 'General Account Payout',
  'tooltip_print_voucher': 'Print Voucher',
  'tooltip_export_csv': 'Export CSV',
  'supplier_name_required': 'Supplier name is required',
  'create_new_purchase_invoice_title': 'Create New Purchase Invoice',
  'create_new_purchase_invoice_desc':
      'Add new goods, log costs, and instant stock replenishment',
  'invoice_number_label_req': 'Invoice Number *',
  'due_date_optional': 'Due Date (Credit):',
  'immediate_or_open': 'Immediate / Open',
  'add_items_to_invoice_title': 'Add items to invoice:',
  'tax_vat_label': 'Tax / VAT (EGP)',
  'discount_commercial_label': 'Commercial Discount (EGP)',
  'shipping_freight_label': 'Shipping / Freight (EGP)',
  'advance_paid_amount_label': 'Advance Paid Amount (EGP)',
  'net_invoice_total': 'Net Invoice Total',
  'auto_replenish_stock_title': 'Auto-replenish stock and catalog quantities',
  'auto_replenish_stock_desc':
      'Stock quantities will immediately increase upon saving and log an audit movement',
  'invoice_notes_label': 'Invoice Notes',
  'invoice_notes_hint': 'Any notes or terms related to this shipment...',
  'confirm_save_invoice_btn': 'Confirm & Save Invoice',
  'invoice_saved_success_title': 'Invoice Created Successfully',
  'invoice_saved_success_msg':
      'Purchase invoice recorded and stock synchronized successfully.',
  'please_select_supplier_warning': 'Please select a supplier',
  'add_at_least_one_item_warning': 'Add at least one item to invoice',
  'enter_valid_quantity_warning': 'Please enter a valid quantity',
  'select_product_first_warning': 'Please select a product first',
  'warehouse_reception_status': 'Warehouse Reception:',
  'received_and_credited': 'Received & Credited',
  'pending_receipt': 'Pending Receipt',
  'line_items_count_title': 'Purchased Items ({count} items):',
  'record_payment_for_supplier_title': 'Record Payment Voucher for Supplier',
  'record_payment_for_supplier_desc':
      'Log cash payment, bank transfer, or InstaPay payout',
  'supplier_payee_label': 'Supplier / Payee *',
  'link_to_specific_invoice': 'Link to Specific Invoice (Optional):',
  'reference_tx_label': 'Reference / Tx #',
  'payment_notes_label': 'Payment Notes',
  'confirm_payment_btn': 'Confirm Payment',
  'supplier_statement_title': 'Supplier Statement: {name}',
  'no_financial_records_supplier': 'No financial records for this supplier yet',
  'reason_cashier_error': 'Cashier / Calculation Error',
  'reason_flavor_swap': 'Swap Flavor / Item',
  'processing_dots': 'Processing...',
  'out_of_stock_badge': 'Out',
  'add_to_cart': 'Add to Cart',
  'print_barcode_stickers': 'Print Barcode Stickers',
  'print_barcode_stickers_desc':
      'Generate crisp Code-128 vector barcodes for thermal label printers',
  'print_command_sent_title': 'Print Command Sent',
  'print_command_sent_msg': 'Printing {count} barcode labels on {size}',
  'barcode_compatible_note':
      'Barcode is 100% compatible with 1D/2D POS handheld scanners & cameras (Code-128).',
  'retry': 'Retry',
  'supplier_saved_success_msg': 'Supplier details saved successfully',
  'all_categories_filter': 'All ({count})',
  'category_liquids': 'Liquids',
  'category_disposable': 'Disposable',
  'category_devices': 'Devices',
  'category_pods': 'Pods',
  'category_coils': 'Coils',
  'category_accessories': 'Accessories',
  'add_new_supplier': 'Add New Supplier',
  'supplier_form_desc': 'Manage authorized vendors and supplier directory',
  'contact_person_label': 'Contact Person',
  'phone_whatsapp_label': 'Phone / WhatsApp',
  'email_address_label': 'Email Address',
  'address_warehouse_label': 'Address / Warehouse',
  'tax_reg_num_label': 'Tax / Reg #',
  'default_payment_terms_label': 'Default Payment Terms',
  'supplied_categories_label': 'Supplied Categories (comma separated)',
  'rating_label': 'Rating:',
  'supplier_status_label': 'Status:',
  'notes_remarks_label': 'Notes & Remarks',
  'notes_remarks_hint': 'Any vendor terms or notes...',
  'update_supplier_btn': 'Update Supplier',
  'add_supplier_btn': 'Add Supplier',
  'saved_successfully': 'Saved successfully',

  // Low Stock & Supplier Financials Dashboard Cards
  'audit_log': 'Audit Log',
  'urgent_items_badge': '{count} Urgent (≤ {threshold})',
  'optimal_stock_badge': 'Optimal',
  'restock_btn': 'Restock',
  'general_brand': 'General',
  'payables_due_badge': 'Payables Due',
  'all_settled_badge': 'All Settled',
  'new_invoice_btn': '+ New Invoice',
  'metric_accounts_payable_title': 'Accounts Payable (Due to Vendors)',
  'metric_accounts_payable_subtitle': 'Outstanding liabilities owed to vendors',
  'metric_total_purchases_title': 'Total Purchases Volume',
  'metric_active_suppliers_count': '{count} active suppliers',
  'metric_total_disbursed_title': 'Total Disbursed to Vendors',
  'metric_settlement_rate': '{rate}% settlement rate',
  'inflow_settlement_ratio': 'Inflow Settlement Ratio:',
  'settlement_progress_summary': '{rate}% Settled • {remaining} Remaining',
  'view_full_directory': 'View Full Directory ➔',
  'pay_btn_short': 'Pay',

  // Stock Movements & Audit Log Dialog
  'stock_movements_btn': 'Stock Movements',
  'stock_movements_dialog_title': 'Stock Movements & Audit Log',
  'stock_movements_dialog_subtitle': 'Complete audit trail of all restocks, sales, damages, and inventory adjustments',
  'total_restock_capital': 'Total Restock Capital',
  'units_count': '{count} Units',
  'units_short': 'units',
  'search_stock_movements_hint': 'Search by SKU, product name, supplier, or invoice #...',
  'refresh_log_tooltip': 'Refresh Log',
  'all_filter': 'All',
  'no_stock_movements_title': 'No stock movements recorded yet',
  'no_stock_movements_desc': 'Any restock, sale, or adjustment will automatically appear in this audit log',

  // Quick Restock Dialog
  'smart_stock_replenishment': 'Smart Stock Replenishment',
  'single_sku_mode': 'Single SKU',
  'batch_matrix_mode': 'Batch Matrix',
  'full_editor_btn': 'Full Editor',
  'confirm_batch_restock': 'Confirm Batch',
  'confirm_restock': 'Confirm Restock',
  'select_variation_to_restock': 'Select Variation to Restock:',
  'current_stock_label': 'Current Stock: {count} Units',
  'reorder_threshold_label': 'Reorder Threshold: {count} Units',
  'new_stock_label': 'New: {count} Units',
  'quantity_to_add_label': 'Quantity to Add:',
  'batch_cost_price_label': 'Batch Cost Price per Unit (EGP):',
  'total_inflow_expenditure': 'Total Inflow Expenditure: {amount}',
  'total_units_added': 'Total Units Added: {count} Units',
  'total_cost_label': 'Total Cost: {amount}',
  'restock_notes_label': 'Restock Notes',
  'restock_notes_hint': 'Optional notes...',
  'plus_10_all': '+10 to All',
  'cost_label': 'Cost',
  'qty_label': '+Qty',
  'warning_title': 'Warning',
  'enter_valid_qty_msg': 'Please enter a valid restock quantity greater than zero.',
  'enter_qty_for_at_least_one_msg': 'Please enter a quantity for at least one variation.',
  'restock_confirmed_title': 'Restock Confirmed',
  'restock_confirmed_msg': 'Stock replenished and audit movement logged.',
  'restock_product_success_msg': 'Stock updated and restock movement logged for "{title}".',
  'restock_failed_title': 'Restock Failed',

  // Variation Image Dialog
  'variation_image_title': 'Variation Image ({sku})',
  'variation_image_subtitle': 'Add custom image URL for this variation or choose from product photos',
  'image_updated_title': 'Image Updated',
  'image_updated_msg': 'Variation image for {sku} set successfully.',
  'bulk_applied_title': 'Bulk Applied',
  'applied_to_color_msg': 'Image applied to all "{color}" variations.',
  'applied_to_flavor_msg': 'Image applied to all "{flavor}" variations.',
  'applied_to_all_title': 'Applied to All',
  'applied_to_all_msg': 'Image applied to all matrix variations.',
  'invalid_url_text': 'Invalid URL',
  'no_image_selected_text': 'No image specified',
  'variation_image_url_label': 'Variation Image URL *',
  'choose_from_existing_photos': 'Or choose from current product images:',
  'apply_to_all_color': 'Apply to all ({color})',
  'apply_to_all_flavor': 'Apply to all ({flavor})',
  'apply_to_all_variations': 'Apply to All Variations',
  'save_for_this_variation': 'Save for this variation',

  // Product Type Card Subtitles
  'type_subtitle_liquid': 'Salt & Freebase Nic',
  'type_subtitle_disposable': 'Disposable Vapes & Puffs',
  'type_subtitle_device': 'Pods, Mods & Kits',
  'type_subtitle_pod': 'Coils & Cartridges',
  'type_subtitle_accessory': 'Batteries & Accessories',

  // General Expenses & OpEx
  'expenses': 'Expenses',
  'expenses_title': 'General Expenses',
  'expenses_subtitle': 'Track & manage store operational costs, utilities, rent & maintenance',
  'permission_expenses': 'Manage Expenses',
  'add_expense_btn': 'Add Expense',
  'add_new_expense': 'Record New Expense',
  'edit_expense': 'Edit Expense Details',
  'expense_form_desc': 'Enter expense details, amount, category and payment method',
  'expense_title': 'Expense Title / Description',
  'expense_title_hint': 'e.g., September Electricity, Delivery Fuel, Office Tea...',
  'expense_amount_egp': 'Amount (EGP)',
  'expense_category': 'Expense Category',
  'expense_date': 'Expense Date',
  'expense_recorded_by': 'Recorded By / Staff',
  'expense_recorded_by_hint': 'Staff or Manager Name',
  'expense_notes_hint': 'Any additional notes or invoice details...',
  'save_expense': 'Save Expense',
  'update_expense': 'Update Expense',
  'expense_added_success': 'Expense recorded successfully',
  'expense_updated_success': 'Expense updated successfully',
  'expense_deleted_success': 'Expense deleted successfully',
  'delete_expense_title': 'Delete Expense',
  'delete_expense_confirm': 'Are you sure you want to delete expense',
  'expenses_list_title': 'Expenses Ledger',
  'search_expenses_hint': 'Search expenses by title, notes, staff...',
  'no_expenses_found': 'No expenses recorded yet',
  'add_first_expense': 'Record First Expense',
  'kpi_expenses_this_month': 'Expenses This Month',
  'kpi_expenses_today': 'Today Expenses',
  'kpi_expenses_filtered_total': 'Filtered Total',
  'kpi_expenses_top_category': 'Top Expense Category',
  'filter_all_categories': 'All Categories',
  'filter_date_range': 'Date Range:',
  'filter_this_week': 'This Week',
  'filter_this_month': 'This Month',
  'filter_custom_date': 'Custom Range',
  'expense_cat_utilities': 'Utilities (Power/Water/Net)',
  'expense_cat_rent': 'Store / Warehouse Rent',
  'expense_cat_supplies': 'Supplies & Buffet',
  'expense_cat_maintenance': 'Maintenance & Repairs',
  'expense_cat_transportation': 'Logistics & Fuel',
  'expense_cat_marketing': 'Marketing & Ads',
  'expense_cat_salaries': 'Salaries & Wages',
  'expense_cat_government': 'Taxes & Licenses',
  'expense_cat_other': 'Miscellaneous / Other',
  'payment_method_cash': 'Cash',
  'payment_method_instapay': 'InstaPay',
  'payment_method_vodafone_cash': 'Vodafone Cash',
  'payment_method_bank_transfer': 'Bank Transfer',
  'payment_method_card': 'Credit / Debit Card',

  // Damaged Stock & Inventory Waste
  'damaged_stock': 'Damaged Goods',
  'damaged_stock_title': 'Damaged Goods & Waste',
  'damaged_stock_subtitle': 'Log inventory damage with automatic stock write-off & financial loss tracking',
  'permission_damaged_stock': 'Manage Damaged Stock',
  'log_damage_btn': 'Log Damaged Stock',
  'log_damage_title': 'Record Damaged / Waste Item',
  'log_damage_subtitle': 'Deduct quantity from stock and compute cost financial loss',
  'select_product_to_damage': 'Select Product to Write Off *',
  'select_variation': 'Select Variation / Flavor / Size *',
  'damage_quantity': 'Damaged Quantity (Units)',
  'cost_price_per_unit': 'Unit Cost Price (EGP)',
  'total_damage_financial_loss': 'Total Financial Loss',
  'damage_reason': 'Damage Reason',
  'damage_reason_expired': 'Expired Product',
  'damage_reason_shipping': 'Broken / Shipping Damage',
  'damage_reason_storage': 'Storage / Humidity / Heat',
  'damage_reason_factory': 'Manufacturing Defect',
  'damage_reason_customer': 'Customer Return (Damaged)',
  'damage_reason_theft': 'Inventory Shortage / Lost',
  'damage_reason_other': 'Other Reasons',
  'filter_all_reasons': 'All Reasons',
  'notes_and_explanation': 'Notes & Details',
  'damage_notes_hint': 'Explain damage reason or shipping box number...',
  'confirm_log_damage': 'Confirm & Write Off Stock',
  'damage_select_product_required': 'Please select a product first',
  'damage_qty_min_error': 'Quantity must be greater than 0',
  'damage_qty_exceeds_stock': 'Damaged quantity exceeds available warehouse stock',
  'available_stock_in_warehouse': 'Current Available Stock in Warehouse',
  'units': 'Units',
  'damage_recorded_success': 'Damaged item recorded and stock deducted successfully',
  'damage_record_deleted_success': 'Damaged item record deleted successfully',
  'delete_damage_record_title': 'Delete Damaged Record',
  'delete_damage_record_confirm': 'Are you sure you want to delete damaged record for',
  'restore_stock_on_delete': 'Restore Stock on Delete',
  'restore_stock_on_delete_subtitle': 'Checking this will add the quantity back to available selling stock',
  'damaged_item_details': 'Damaged Item Details',
  'search_damaged_stock_hint': 'Search by product name, SKU, notes, staff...',
  'no_damaged_stock_found': 'No damaged stock recorded yet',
  'no_damaged_stock_subtitle': 'Click Log Damaged Stock to write off damaged items from inventory',
  'kpi_total_damage_loss': 'Total Financial Loss',
  'kpi_total_damaged_units': 'Total Damaged Units',
  'kpi_this_month_damage_loss': 'This Month Loss',
  'kpi_top_damage_reason': 'Top Damage Reason',
  'search_product_barcode_hint': 'Search product by name, barcode or brand...',

  // HR, Employees & Payroll
  'employees': 'Employees & Payroll',
  'permission_employees': 'Manage Employees & Payroll',
  'employees_management_title': 'Employees & Payroll Management',
  'employees_management_subtitle': 'Staff directory, salary advances ledger, and monthly payroll disbursement',
  'tab_employees': 'Staff Directory',
  'tab_salary_advances': 'Salary Advances',
  'tab_payroll_history': 'Payroll Slips',
  'add_employee_btn': 'Add Employee',
  'disburse_advance_btn': 'Disburse Advance',
  'disburse_payroll_btn': 'Disburse Payroll',
  'kpi_total_monthly_salaries': 'Total Base Salaries',
  'kpi_current_month_advances': 'Current Month Advances',
  'kpi_disbursed_salaries_this_month': 'Paid Salaries This Month',
  'kpi_active_employees_count': 'Active Employees',
  'month_period_label': 'Payroll Month:',
  'search_employees_hint': 'Search by name, job title, phone, or national ID...',
  'search_advances_hint': 'Search advances by employee, notes, or payment method...',
  'search_payroll_hint': 'Search payroll by employee, month, or staff...',
  'no_employees_found': 'No employees registered yet',
  'no_advances_found': 'No salary advances for this month',
  'no_payroll_found': 'No payroll slips issued for this month',
  'add_first_employee': 'Add First Employee',
  'employee_col_name': 'Employee Name',
  'employee_col_job': 'Job Title',
  'employee_col_phone': 'Phone Number',
  'employee_col_salary': 'Base Salary',
  'employee_col_advances_balance': 'Unsettled Advances',
  'employee_col_status': 'Status',
  'employee_col_actions': 'Actions',
  'advance_col_employee': 'Employee',
  'advance_col_amount': 'Advance Amount',
  'advance_col_date': 'Disbursed Date',
  'advance_col_payment_method': 'Payment Method',
  'advance_col_deducted': 'Deduction Status',
  'payroll_col_employee': 'Employee',
  'payroll_col_month': 'Payroll Month',
  'payroll_col_base': 'Base Salary',
  'payroll_col_bonuses': 'Bonuses',
  'payroll_col_advances': 'Advances Deducted',
  'payroll_col_deductions': 'Other Deductions',
  'payroll_col_net': 'Net Salary Paid',
  'payroll_col_date': 'Payment Date',
  'settled_from_payroll': 'Deducted from Payroll',
  'unsettled_advance': 'Unsettled (Pending)',
  'active_employee': 'Active',
  'inactive_employee': 'Inactive',
  'delete_employee_title': 'Delete Employee',
  'delete_employee_confirm': 'Are you sure you want to delete employee',
  'employee_deleted_success': 'Employee deleted successfully',
  'delete_advance_title': 'Delete Salary Advance',
  'delete_advance_confirm': 'Are you sure you want to delete advance of',
  'for_employee': 'for employee',
  'advance_deleted_success': 'Salary advance deleted successfully',
  'delete_payroll_title': 'Delete Payroll Slip',
  'delete_payroll_confirm': 'Are you sure you want to delete payroll slip for',
  'payroll_deleted_success': 'Payroll slip deleted successfully',
  'edit_employee_title': 'Edit Employee',
  'add_employee_title': 'Add New Employee',
  'employee_form_subtitle': 'Enter employee details, job title, and base salary',
  'employee_name': 'Full Employee Name *',
  'employee_name_hint': 'e.g. John Doe',
  'employee_phone': 'Phone / WhatsApp *',
  'national_id': 'National ID',
  'national_id_hint': 'National Identification number',
  'job_title_position': 'Job Title / Role *',
  'job_title_hint': 'e.g. Cashier, Sales rep, Warehouse clerk',
  'base_monthly_salary': 'Base Monthly Salary (EGP) *',
  'employee_address': 'Residential Address',
  'employee_address_hint': 'City, District, Street...',
  'emergency_contact': 'Emergency Contact Phone',
  'employee_status_active': 'Employee is actively working',
  'employee_status_active_subtitle': 'Eligible for salary advances and payroll',
  'employee_added_success': 'Employee added successfully',
  'employee_updated_success': 'Employee updated successfully',
  'disburse_advance_title': 'Disburse Salary Advance',
  'disburse_advance_subtitle': 'Record cash advance to be deducted from monthly payroll',
  'select_employee': 'Select Employee *',
  'select_employee_required': 'Please select an employee',
  'advance_amount_egp': 'Advance Amount (EGP) *',
  'advance_date': 'Disbursement Date',
  'confirm_disburse_advance': 'Confirm Advance Disbursement',
  'advance_recorded_success': 'Salary advance recorded successfully',
  'disburse_payroll_title': 'Disburse Monthly Payroll',
  'disburse_payroll_subtitle': 'Compute net salary with bonuses, advance deductions, and record as expense',
  'payroll_calculation_breakdown': 'Payroll Calculation Breakdown',
  'bonuses_and_incentives': 'Bonuses & Incentives (EGP)',
  'deductions_and_penalties': 'Penalties & Other Deductions (EGP)',
  'net_salary_to_pay': 'Net Salary to Disburse',
  'record_to_expenses_checkbox': 'Auto-record to General Expenses (Salaries & Wages)',
  'record_to_expenses_subtitle': 'Include directly in OpEx reports and P&L financial statements',
  'confirm_disburse_payroll': 'Confirm & Disburse Payroll',
  'payroll_disbursed_success': 'Payroll disbursed and recorded to expenses successfully',
  'thermal_receipt': 'Thermal Receipt',
  'send_push_to_all': 'Send Push to All Users',
  'confirm_and_select': 'Confirm & Select',
  'products_selected_count': '{count} Products Selected',
  'passcodes_cannot_be_empty': 'Passcodes cannot be empty',
  'add_and_select': 'Add & Select',
  'add_resistance': 'Add Resistance',
  'add_image': 'Add Image',
  'select_from_picker': 'Select from Picker',
  'save_image': 'Save Image',

  // Dashboard HR & Payroll Card
  'payroll_hr_dashboard_title': 'Staff, Payroll & HR Overview',
  'payroll_hr_dashboard_subtitle': 'Monitor total payroll commitments, advances disbursed, and paid wages',
  'kpi_active_staff_title': 'Active Staff',
  'kpi_base_salaries_pool_title': 'Monthly Salaries Pool',
  'kpi_advances_period_title': 'Period Salary Advances',
  'kpi_paid_payroll_period_title': 'Paid Payroll in Period',
  'payroll_execution_ratio': 'Payroll Execution Rate:',
  'payroll_execution_summary': '{paid} Disbursed of {pool} Base Pool',
  'manage_employees_hub_btn': 'Staff & Payroll Hub ➔',
  'disburse_advance_quick_btn': 'Quick Advance',
  'issue_payroll_quick_btn': 'Issue Payroll',
  'staff_members_count': '{count} active staff members',

  // Dashboard Expenses & Damaged Goods Cards
  'expenses_dashboard_title': 'Operational Expenses (OpEx)',
  'expenses_dashboard_subtitle': 'Track administrative costs, utilities & store operational expenses',
  'damaged_goods_dashboard_title': 'Damaged Goods & Waste',
  'damaged_goods_dashboard_subtitle': 'Monitor financial loss from write-offs & defective stock',
  'metric_total_expenses_title': 'Total OpEx',
  'metric_expenses_count_subtitle': '{count} recorded expenses',
  'metric_top_expense_cat': 'Top Expense Category',
  'metric_damaged_loss_title': 'Total Waste Loss',
  'metric_damaged_units_subtitle': '{count} written-off units',
  'metric_top_damage_reason': 'Top Damage Cause',
  'manage_expenses_hub_btn': 'Expenses Ledger ➔',
  'manage_damaged_hub_btn': 'Damaged Stock Log ➔',
  'add_expense_quick_btn': 'Add Expense',
  'log_damage_quick_btn': 'Log Damaged Stock',
  'no_expenses_in_period': 'No expenses in this period',
  'no_damage_in_period': 'No inventory waste in this period',

  // Filters & General Table Keys
  'filter_today': 'Today',
  'filter_category': 'Expense Category',
  'filter_category_label': 'Expense Category',
  'date_time': 'Date & Time',
  'records_found': 'records',
  'no_notes': 'No notes',
  'no_data_placeholder': 'None',

  // Employees & HR Tabs & Tables
  'employees_tab': 'Staff Directory',
  'advances_tab': 'Salary Advances',
  'payroll_tab': 'Payroll History',
  'month_period': 'Salary Month',
  'net_salary_due': 'Net Salary Due (EGP)',
  'deducted_from_payroll': 'Deducted from Payroll',
  'pending_deduction': 'Pending (Not Deducted)',
  'employees_list_title': 'Staff & Employees Directory',
  'advances_list_title': 'Salary Advances Ledger',
  'payroll_slips_history_title': 'Issued Payroll Slips History',
  'payment_date': 'Disbursement Date',
  'bonuses_and_rewards': 'Bonuses & Incentives',
  'advances_deducted': 'Advance Deductions',
  'penalties_and_deductions': 'Penalties & Deductions',
  'net_paid': 'Net Disbursed Amount',
  'disbursed_by': 'Disbursed By',
  'current_month_advances': 'Current Month Advances',
  'payroll_already_disbursed': 'Payroll already disbursed for this month',
  'no_payroll_slips_found': 'No payroll slips issued yet',
  'from_date': 'From Date',
  'to_date': 'To Date',
  'from_label': 'From:',
  'to_label': 'To:',
  'select_start_date': 'Select Start Date',
  'select_end_date': 'Select End Date',

  // Common / Suppliers / Invoices / Procurement & Payroll Keys
  'product_name': 'Product Name',
  'sku_barcode': 'SKU / Barcode',
  'product_variation': 'Product Variation',
  'recorded_by': 'Recorded By',
  'invalid_amount': 'Please enter a valid amount',
  'advances_to_deduct': 'Advances to Deduct',
  'payment_method': 'Payment Method',
  'record_payroll_as_expense': 'Record Payroll as General Expense',
  'record_payroll_as_expense_subtitle': 'Automatically include payroll slip in operational expense ledger',
  'notes': 'Notes',
  'hire_date': 'Hire Date',
  'employee_active_status': 'Employee Status (Active / Inactive)',
  'address': 'Address',
  'alert': 'Alert',
  'field_required': 'This field is required',
  'currency_egp': 'EGP',
  'saving': 'Saving...',
  'item': 'Item',
  'quantity': 'Quantity',
  'price': 'Price',
  'invoice_ref_label': 'Invoice / Reference #',
  'supplier_vendor_required': 'Supplier / Vendor *',
  'btn_new_supplier_short': '+ New Supplier',
  'invoice_date_label': 'Invoice Date',
  'payment_method_label_col': 'Payment Method',
  'select_product_hint_catalog': 'Select product from catalog...',
  'cost_price_label': 'Cost Price (EGP)',
  'add_btn': 'Add',
  'items_subtotal_label': 'Items Subtotal:',
  'net_total_amount_label': 'Net Total Amount:',
  'balance_due_label': 'Balance Due (Payable):',
  'print_preview_invoice_tooltip': 'Preview & Print Purchase Invoice',
  'due_date_label': 'Due Date',
  'immediate': 'Immediate',
  'print_export_btn': 'Print & Export',
  'record_payment_step_btn': 'Record Payment',
  'enter_valid_amount_warning': 'Please enter a valid payment amount greater than zero.',
  'payment_recorded_title': 'Payment Recorded',
  'payment_recorded_msg': 'Payment voucher logged and supplier payable balance updated successfully.',
  'record_payment_voucher_title': 'Record Supplier Payment Voucher',
  'record_payment_voucher_desc': 'Log disbursement to supplier account or settle a specific purchase invoice',
  'supplier_payee_req': 'Payee Supplier *',
  'balance_due_badge': 'Due: {amount}',
  'link_invoice_optional': 'Link to Specific Invoice (Optional)',
  'remaining_badge': 'Remaining: {amount}',
  'amount_paid_req': 'Amount Paid (EGP) *',
  'amount_is_required': 'Amount is required',
  'payment_method_field': 'Payment Method *',
  'tx_ref_label': 'Transaction / Cheque / Transfer #',
  'payment_notes_field': 'Payment Voucher Notes',
  'payment_notes_hint': 'Any transfer details or remarks...',
  'supplier_statement_name': 'Statement of Account: {name}',
  'print_statement_tooltip': 'Print & Export Account Statement',
  'total_purchases_kpi': 'Total Purchases',
  'total_paid_kpi': 'Total Paid',
  'balance_due_kpi': 'Balance Due (Payables)',
  'purchase_invoice_tx': 'Purchase Supply Invoice',
  'items_pieces_count_txt': '({items} items • {pieces} units)',
  'payment_voucher_tx': 'Cash / Bank Payment Voucher',
  'ref_prefix': 'Ref: {ref}',
  'supplier_payout': 'Supplier Purchase Settlement',
  'paid_tag': 'Paid',
  'print_invoice_tooltip': 'Print Invoice',
  'print_voucher_tooltip': 'Print Payment Voucher',
  'print_statement_btn': 'Print Statement',
  'pay_vendor_btn': 'Pay Supplier',
  'printable_purchase_invoice': 'Purchase Supply Invoice',
  'procurement_erp_title': 'Procurement & Vendor Management',
  'supplier_label': 'Supplier:',
  'payment_label': 'Payment:',
  'item_col': 'Item',
  'qty_col': 'Quantity',
  'unit_cost_col': 'Unit Cost',
  'subtotal_col': 'Subtotal',
  'paid_col': 'Paid',
  'remaining_col': 'Remaining',
  'grand_total_col': 'Grand Total',
  'print_invoice_action': 'Print Invoice',
  'export_csv_btn': 'Export CSV',
  'invoice_csv_downloaded': 'Invoice CSV downloaded successfully',
  'copy_summary_tooltip': 'Copy Data Summary',
  'summary_copied_to_clipboard': 'Summary copied to clipboard',
  'payment_voucher_receipt': 'Supplier Disbursement Voucher',
  'authorized_voucher': 'Authorized Financial Voucher',
  'amount_paid_label': 'Amount Paid:',
  'payee_label': 'Payee / Supplier:',
  'date_label': 'Date:',
  'method_label': 'Payment Method:',
  'ref_num_label': 'Ref / Transfer #:',
  'description_label': 'Description / Purpose:',
  'for_invoice_num': 'Payment for Purchase Invoice #{id}',
  'general_account_payment': 'On-account advance / settlement payment',
  'notes_label': 'Notes:',
  'print_voucher_action': 'Print Payment Voucher',
  'voucher_csv_downloaded': 'Payment voucher CSV downloaded successfully',
  'supplier_statement_header': 'Supplier Statement of Account',
  'transaction_history_label': 'Transactions, Invoices & Payment Vouchers:',
  'statement_csv_downloaded': 'Account statement CSV downloaded successfully',

  // POS Direct Variation Catalog Keys
  'grid_view': 'Grid View',
  'list_view': 'List / Table View',
  'in_stock_only': 'In Stock Only',
  'items_available_count': '{count} items available',
  'low_stock_badge': '{count} left',
  'available_stock_badge': '{count} in stock',
  'add_item_btn': 'Add',
  'quick_add_tooltip': 'Quick add to register cart',
  'reset_filters': 'Reset Filters & Search',
  'show_cost_price_toggle': 'Cost Price (Admin)',
  'cost_prefix': 'Cost:',
  'regular_price_label': 'Original:',
  'sale_tag': 'Sale',
  'pos_col_item': 'Item & Specs',
  'pos_col_stock': 'Stock Available',
  'pos_col_cost': 'Cost Price',
  'pos_col_price': 'Selling Price',
  'pos_col_action': 'Quick Add',
  'pos_tab_catalog': 'Products & Specs',
  'pos_tab_cart': 'Cart & Register',

  // ERP Accounting, Reports & Inventory Audit
  'accounting': 'Treasury & Accounts',
  'reports': 'Reports & Analytics',
  'permission_accounting': 'Manage Treasury & Accounting',
  'permission_reports': 'View Financial & Stock Reports',
  'treasury_safe_balances': 'Treasury & Cash Safe Balances',
  'record_cash_flow': 'Record Cash Movement',
  'cash_drawer_safe': 'Cash Drawer & Safe',
  'cash_in_drawer_note': 'Physical cash in cashier register & safe',
  'pos_card_bank': 'Card / POS Bank Account',
  'visa_mastercard_note': 'Card transactions & bank settlements',
  'instapay_account': 'Instapay Account',
  'instapay_transfers_note': 'Instant electronic deposits',
  'vodafone_cash_wallets': 'Vodafone Cash & Wallets',
  'mobile_wallets_note': 'Mobile wallet cash balances',
  'total_liquid_capital': 'Total Liquid Capital',
  'all_channels_sum': 'Sum of all liquid payment channels',
  'inventory_cost_value': 'Inventory Value (at Cost)',
  'inventory_retail_value': 'Inventory Value (at Retail)',
  'stock_at_cost_price': 'Total warehouse stock value at cost price',
  'supplier_payables_debt': 'Supplier Payables (Debts)',
  'unpaid_invoices_balance': 'Total outstanding purchase debt',
  'net_working_capital': 'Net Working Capital',
  'liquid_plus_inventory_minus_debt': 'Liquid + Inventory - Supplier Debt',
  'income_statement_pnl': 'Income Statement (P&L)',
  'net_margin': 'Net Profit Margin',
  'sales_revenue': '1. Sales Revenue',
  'gross_sales': 'Gross Sales',
  'discounts_deductions': 'Discounts & Deductions',
  'net_sales_revenue': 'Net Sales Revenue',
  'cogs_title': '2. Cost of Goods Sold (COGS)',
  'cogs_purchased_cost': 'Cost basis of items sold',
  'gross_profit': 'Gross Profit',
  'operating_overheads': '3. Operating Overheads & Costs',
  'operating_expenses': 'Operating Expenses',
  'employee_salaries_payroll': 'Salaries & Advances',
  'damaged_inventory_losses': 'Damaged Stock Losses',
  'net_operating_profit': 'Net Operating Profit',
  'orders_completed': 'Orders Completed',
  'items_sold': 'Units Sold',
  'financial_period': 'Financial Period:',
  'record_treasury_entry': 'Record Treasury Entry',
  'transaction_type': 'Transaction Type',
  'payment_channel': 'Payment Channel / Safe',
  'amount_egp': 'Amount (EGP)',
  'reason_or_description': 'Reason / Description',
  'transaction_notes_hint': 'Enter reason or details for this cash flow...',
  'reference_receipt_number': 'Receipt / Reference # (Optional)',
  'save_entry': 'Save Entry',
  'recent_treasury_movements': 'Recent Treasury Movements',
  'no_transactions_found': 'No treasury transactions recorded yet',
  'transaction_recorded_successfully': 'Transaction recorded successfully',
  'stock_adjustment_audit': 'Inventory Audit & Stock Adjustment',
  'system_recorded_stock': 'System Recorded Stock',
  'physical_counted_stock': 'Physically Counted Stock',
  'enter_valid_stock': 'Enter valid counted stock',
  'audit_variance': 'Variance (Surplus / Shortage)',
  'adjustment_reason_type': 'Adjustment Reason / Type',
  'notes_optional': 'Additional Notes (Optional)',
  'audit_notes_hint': 'Audit notes, discrepancy reasons, and details...',
  'confirm_adjustment': 'Confirm & Apply Adjustment',
  'stock_adjusted_successfully': 'Stock adjusted and logged successfully',
  'top_products_sales_margins': 'Top Selling Products & Margins',
  'products_sold': 'Products Sold',
  'units_sold': 'Units Sold',
  'total_revenue': 'Revenue',
  'cogs_cost': 'COGS Cost',
  'units_in_stock': 'Units in Stock',
  'unique_variations': 'Unique Variations / SKUs',
  'potential_gross_profit': 'Potential Gross Profit',
  'potential_margin': 'Expected Margin',
  'stock_health_distribution': 'Stock Health Distribution',
  'in_stock_healthy': 'Well Stocked',
  'low_stock_warning': 'Low Stock Warning',
  'out_of_stock_critical': 'Out of Stock (Zero)',
  'supplier_purchasing_summary': 'Supplier Procurement & Debt Summary',
  'active_suppliers': 'Suppliers',
  'invoices_count': 'Invoices Count',
  'expense_breakdown_by_category': 'Operating Expenses by Category',
  'report_period': 'Report Period:',
  'sales_and_margins': 'Sales & Margins',
  'inventory_valuation': 'Inventory Valuation',
  'supplier_procurement': 'Purchasing & Suppliers',
  'expense_analysis': 'Expense Analysis',
  'no_sales_in_period': 'No sales recorded during this period',
  'no_expenses_recorded': 'No expenses recorded during this period',

  // Step 2 & 4 & 5: Physical Stocktake, Shift Tracking, Multi-Branch & Permissions
  'physical_stocktake_btn': 'Physical Stocktake',
  'physical_stocktake_audit_title': 'Physical Stocktake & Discrepancy Audit',
  'physical_stocktake_audit_subtitle':
      'Audit physical stock, reconcile discrepancies, and record atomic adjustments with audit log',
  'audited_items_count': 'Audited Items',
  'discrepancy_items_count': 'Discrepant Items',
  'net_variance_units': 'Net Variance (Units)',
  'net_cost_impact': 'Net Cost Impact',
  'search_stocktake_hint': 'Search by product title, barcode, or SKU...',
  'show_discrepancies_only': 'Show Discrepancies Only',
  'no_matching_stocktake_items': 'No matching stocktake items found',
  'sku_spec': 'SKU / Barcode',
  'system_stock': 'System Stock',
  'counted_stock': 'Counted Stock',
  'variance_diff': 'Variance',
  'cost_impact': 'Cost Impact',
  'apply_stock_adjustments': 'Apply Adjustments',
  'no_discrepancies_found': 'No inventory discrepancies found to adjust',
  'stocktake_completed_success':
      'Physical stocktake and adjustments recorded successfully!',
  'cashier_shifts': 'Cashier Shifts',
  'permission_shifts': 'Cashier Shifts & Drawer Reconciliation',
  'permission_stock_audit': 'Stocktake & Inventory Adjustments',
  'cashier_shifts_title': 'Cashier Shifts & Cash Drawer',
  'cashier_shifts_subtitle':
      'Track branch cashier shifts, drawer cash reconciliation, and closing reports',
  'search_shifts_hint': 'Search by cashier name, branch, or shift ID...',
  'open_shift_btn': 'Open New Shift',
  'close_shift_btn': 'Close Shift',
  'shift_start_time': 'Opened At',
  'difference_reconciliation': 'Cash Reconciliation',
  'shift_status': 'Shift Status',
  'shift_in_progress': 'In Progress...',
  'shift_open': 'Open',
  'shift_closed': 'Closed',
  'all_branches': 'All Branches',
  'no_active_shift_warning':
      'Warning: No cashier shift is currently active. Please open a shift before selling.',
  'shift_duration': 'Shift Duration',
  'cash_in_out_btn': 'Cash In / Out',
  'open_cashier_shift_title': 'Open Cashier Shift',
  'select_branch': 'Select Branch',
  'cashier_name': 'Cashier Name',
  'opening_drawer_cash': 'Opening Drawer Float (EGP)',
  'opening_notes_optional': 'Opening Notes (Optional)',
  'shift_notes_hint': 'e.g. Received drawer float in full...',
  'start_shift_btn': 'Start Shift',
  'shift_opened_success': 'Shift opened successfully!',
  'shift_closed_success': 'Shift closed and cash reconciled successfully!',
  'close_shift_reconciliation_title': 'Close Shift & Cash Reconciliation',
  'pos_cash_sales': 'Cash Sales',
  'card_visa_sales': 'Card / Visa Sales',
  'instapay_vodafone_sales': 'Instapay / Wallets',
  'drawer_cash_ins': 'Drawer Cash In (+)',
  'drawer_cash_outs': 'Drawer Cash Out / Refunds (-)',
  'expected_drawer_cash': 'Expected Drawer Cash',
  'physical_counted_drawer_cash': 'Counted Physical Cash in Drawer',
  'drawer_balanced': 'Drawer Fully Balanced',
  'drawer_cash_surplus': 'Cash Drawer Surplus',
  'drawer_cash_shortage': 'Cash Drawer Shortage',
  'closing_notes_optional': 'Closing & Reconciliation Notes (Optional)',
  'shift_reconciliation_notes_hint':
      'Reasons for any cash variance or handover notes...',
  'confirm_close_shift_btn': 'Confirm & Close Shift',
  'shift_cash_in_title': 'Record Cash In (Drawer Deposit)',
  'shift_cash_out_title': 'Record Cash Out (Drawer Withdrawal)',
  'drawer_cash_in_btn': 'Cash In (Deposit)',
  'drawer_cash_out_btn': 'Cash Out (Withdrawal)',
  'cash_in_recorded_success': 'Cash In recorded successfully!',
  'cash_out_recorded_success': 'Cash Out recorded successfully!',
  'cash_in_reason_hint': 'e.g. Adding petty change / extra float...',
  'cash_out_reason_hint': 'e.g. Courier payment / petty store expense...',
  'record_cash_in_btn': 'Record Cash In',
  'record_cash_out_btn': 'Record Cash Out',
  'shortcut_f6_shift': 'Shift',
  'delete_transaction': 'Delete Treasury Movement',
  'confirm_delete_treasury_tx': 'Are you sure you want to delete this treasury entry? Its financial impact and linked expense will be reversed.',
  'transaction_deleted_success': 'Treasury movement deleted successfully!',
  'transaction_updated_successfully': 'Treasury movement updated successfully!',
  'previous_shift_closing_cash': 'Previous Shift Closing Balance:',
  'no_previous_shift_found': 'No previous closed shift found for this branch (First shift)',
  'previous_shift_closed_by': 'Closed by: {name}',
  'previous_shift_auto_filled_hint': 'Opening float auto-filled from last shift closing balance. Please physically count the cash in drawer to verify.',
  'fetching_drawer_balance': 'Fetching previous shift closing balance...',
  'drawer_auto_reconciled': 'Auto-Reconciled Opening Float',
  'network_url_tab': 'Network URL',
  'upload_file_tab': 'Upload File',
  'no_image': 'No Image',
  'shortcut_f7_transfers': 'Branch Transfers',
  'transfer_dialog_title': 'Inter-Branch Stock Transfers & Requests',
  'transfer_current_branch_label': 'Current Branch',
  'transfer_tab_new_request': 'New Transfer Request',
  'transfer_tab_history': 'Transfers & Shipments Log',
  'transfer_route_title': 'Transfer Routing',
  'transfer_from_branch': 'Request From (Source Branch / Warehouse)',
  'transfer_select_source_hint': 'Select source branch or warehouse...',
  'transfer_main_warehouse': 'Main Central Warehouse',
  'transfer_to_branch': 'Requesting Branch (Destination)',
  'transfer_current_branch': 'Current POS Branch',
  'transfer_priority_label': 'Request Priority:',
  'transfer_priority_normal': 'Normal',
  'transfer_priority_urgent': 'Urgent (Out of Stock)',
  'transfer_priority_next_shipment': 'Next Shipment',
  'transfer_add_products_title': 'Add Products & Flavors to Request',
  'transfer_search_product_hint': 'Search by product name, brand, flavor, or SKU...',
  'transfer_no_items_selected': 'No items added to the transfer request yet',
  'transfer_requested_items': 'Requested Items',
  'transfer_total_qty': 'Total Requested Units',
  'transfer_notes_hint': 'Notes or special dispatch instructions...',
  'transfer_submit_btn': 'Send Transfer Request',
  'transfer_filter_incoming': 'Incoming to Branch',
  'transfer_filter_outgoing': 'Outgoing from Branch',
  'transfer_from': 'From',
  'transfer_to': 'To',
  'transfer_confirm_receipt_btn': 'Confirm Receipt',
  'transfer_confirm_receipt_title': 'Confirm Receipt of Goods at Branch',
  'transfer_confirm_receipt_msg': 'Do you confirm receiving and verifying all items for shipment {num}?',
  'transfer_confirm_btn': 'Yes, Confirm Receipt',
  'transfer_cancel_title': 'Cancel Transfer Request',
  'transfer_cancel_msg': 'Are you sure you want to cancel this transfer request?',
  'transfer_status_pending': 'Pending Approval',
  'transfer_status_approved': 'Approved',
  'transfer_status_in_transit': 'In Transit / Shipping',
  'transfer_status_received': 'Received at Branch',
  'transfer_status_rejected': 'Rejected',
  'transfer_status_cancelled': 'Cancelled',
  'transfer_no_records': 'No transfer requests recorded for this branch',
  'more_items': 'more items',
  'inventory_transfers': 'Merchandise Transfers',
  'permission_transfers': 'Manage Inter-Branch Transfers',
  'transfer_screen_title': 'Inter-Branch Stock Transfers & Logistics',
  'transfer_screen_subtitle': 'Track branch transfer requests, dispatch shipments, and reconcile inventory',
  'all_branches_warehouses': 'All Branches & Warehouses',
  'transfer_create_new_btn': 'New Transfer Request',
  'transfer_kpi_total': 'Total Transfers',
  'transfer_kpi_pending': 'Pending Approval',
  'transfer_kpi_in_transit': 'In Transit',
  'transfer_kpi_received': 'Received & Reconciled',
  'transfer_search_hint': 'Search by transfer #, branch, product, or SKU...',
  'transfer_col_number': 'Transfer #',
  'transfer_col_from': 'From Branch',
  'transfer_col_to': 'To Branch',
  'transfer_col_items': 'Items',
  'transfer_col_priority': 'Priority',
  'transfer_col_status': 'Status',
  'transfer_col_date': 'Date',
  'transfer_col_actions': 'Actions',
  'transfer_action_approve': 'Approve Request',
  'transfer_action_dispatch': 'Dispatch Shipment',
  'transfer_action_reject': 'Reject Request',
  'transfer_approve_confirm_msg': 'Do you approve preparing and dispatching transfer {num}?',
  'transfer_dispatch_confirm_msg': 'Do you confirm shipment {num} has left the source warehouse and is in transit?',
  'transfer_courier_notes_hint': 'Courier / driver name or waybill # (optional)...',
  'transfer_reject_confirm_msg': 'Please provide a reason for rejecting this transfer:',
  'transfer_reject_reason_hint': 'Rejection reason...',
  'requested_by': 'Requested By',

  // Multi-Branch Inventory Matrix & Tracking
  'branch_stock_label': 'Branch Stock',
  'branch_stock_title': 'Branch & Warehouse Inventory',
  'branch_stock_updated_success': 'Branch {branch} stock updated to {qty} pcs.',
  'set_branch_stock_title': 'Set Branch Stock',
  'branch': 'Branch',
  'variation': 'Variation / Flavor',
  'new_stock_quantity': 'New Stock Quantity',
  'pcs': 'pcs',
  'branch_stock_matrix_badge': 'Multi-Branch Stock Matrix',
  'total_all_branches_stock': 'Total Across All Branches',
  'branches_stock_overview_tab': 'Branches & Warehouses Overview',
  'variations_stock_matrix_tab': 'Variations & Flavors Matrix',
  'warehouse_type_label': 'Warehouse',
  'retail_store_label': 'Retail Store',
  'decrement_1': 'Decrement 1',
  'increment_1': 'Increment 1',
  'edit_qty_btn': 'Set Qty',
  'transfer_to_branch_btn': 'Transfer Stock',
  'branch_stock_action_tooltip': 'Multi-Branch Stock Matrix',

  // Purchase Invoice Batch Variations Selection
  'single_variation_mode': 'Single Item',
  'batch_variations_mode': 'Batch Add All Variations',
  'select_all_variations': 'Select All',
  'deselect_all_variations': 'Deselect All',
  'apply_uniform_qty': 'Uniform Qty:',
  'apply_btn': 'Apply',
  'apply_uniform_cost': 'Uniform Cost:',
  'add_selected_vars_btn': 'Add Selected Variations ({count} items)',
  'no_vars_selected_warning': 'Please select at least one variation and enter a quantity > 0',
  'vars_added_success_msg': 'Added {count} variations to invoice successfully',
  'search_vars_hint': 'Search flavor, resistance, or SKU...',
  'current_warehouse_stock_badge': 'Stock: {count} pcs',
  'batch_vars_summary': 'Selected {selected} of {total} variations • Total: {qty} pcs • {amount}',
  'qty_short': 'Qty',
  'cost_short': 'Cost',

  // Invoice Payment Validation & Quick Pay
  'paid_amount_exceeds_total_error': 'Paid amount ({paid}) cannot exceed invoice total ({total})',
  'paid_exceeds_total_hint': 'Exceeds total (Max: {max})',
  'pay_full_total_tooltip': 'Pay full invoice amount',
  'pay_full_btn': 'Pay Full (100%)',
  'pay_half_btn': 'Pay 50%',
  'pay_zero_btn': 'Credit (0)',
  'paid_exceeds_warning_banner': 'Warning: Paid amount ({paid}) exceeds invoice total ({total})!',
};




